{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"dms_if_nicednr_live_car\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "ko-KR",
    "cultures": [
      {
        "name": "ko-KR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "36aff095-3507-45b0-a9af-5951b2da10dc",
        "fromColumn": "dms_reg_dt",
        "fromTable": "dms_if_nicednr_live_car",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_8badf1cf-10bb-4686-8110-a46ffe56e4f3"
      },
      {
        "name": "89c89561-837b-4e98-86e1-35a4a1c6b24d",
        "fromColumn": "dms_upd_dt",
        "fromTable": "dms_if_nicednr_live_car",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_04ec9ba3-8762-4ecf-9587-a808e501f99f"
      }
    ],
    "sourceQueryCulture": "ko-KR",
    "tables": [
      {
        "name": "dms_if_nicednr_live_car",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "탐색"
          }
        ],
        "columns": [
          {
            "name": "nice_row_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5e265326-76e9-4f03-a9a0-800f81ab3223",
            "sourceColumn": "nice_row_id",
            "summarizeBy": "sum"
          },
          {
            "name": "molit_reg_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39c017f3-e364-4803-9d6f-1423345f1c3f",
            "sourceColumn": "molit_reg_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "nice_extract_de",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "02324b41-5061-49c0-95b7-f19d7d523a95",
            "sourceColumn": "nice_extract_de",
            "summarizeBy": "none"
          },
          {
            "name": "import_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b33c1d6-8ca0-4780-84d0-a0956be54896",
            "sourceColumn": "import_yn",
            "summarizeBy": "none"
          },
          {
            "name": "org_car_maker_kor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95bb7c53-8f16-4b32-9ff2-ed73ac3a5e6f",
            "sourceColumn": "org_car_maker_kor",
            "summarizeBy": "none"
          },
          {
            "name": "org_car_maker_eng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95383bba-a3be-467f-a8b6-855b2478983d",
            "sourceColumn": "org_car_maker_eng",
            "summarizeBy": "none"
          },
          {
            "name": "car_maker_kor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a20c5b3e-223a-4576-b265-92d619cf9a00",
            "sourceColumn": "car_maker_kor",
            "summarizeBy": "none"
          },
          {
            "name": "org_car_nation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25f3db9e-71ec-464e-820b-a5f24843bcd7",
            "sourceColumn": "org_car_nation",
            "summarizeBy": "none"
          },
          {
            "name": "car_nation",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9b985494-8813-4bb7-9e26-4be7f73a6338",
            "sourceColumn": "car_nation",
            "summarizeBy": "none"
          },
          {
            "name": "car_moel_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98fb6a3c-fd8d-4dec-9f77-29a0e7d0d952",
            "sourceColumn": "car_moel_dt",
            "summarizeBy": "none"
          },
          {
            "name": "car_moel_dt_eng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "412d2e86-785d-44b0-87ad-26ea1752edf4",
            "sourceColumn": "car_moel_dt_eng",
            "summarizeBy": "none"
          },
          {
            "name": "car_model_kor",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "185b039c-8bd4-438b-8fce-d15c0dc06aa3",
            "sourceColumn": "car_model_kor",
            "summarizeBy": "none"
          },
          {
            "name": "car_model_eng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58734549-17ba-446f-b589-baf810d675d5",
            "sourceColumn": "car_model_eng",
            "summarizeBy": "none"
          },
          {
            "name": "project_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "367fa81a-7d63-437f-8239-40d26d4c5b00",
            "sourceColumn": "project_cd",
            "summarizeBy": "none"
          },
          {
            "name": "cnm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fd7ef48a-23ff-4b86-89e5-5b8bf62b4b34",
            "sourceColumn": "cnm",
            "summarizeBy": "none"
          },
          {
            "name": "spcf_model_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6b0a140c-b648-424a-96e6-3c9009e0fdd1",
            "sourceColumn": "spcf_model_year",
            "summarizeBy": "none"
          },
          {
            "name": "frst_regist_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7579f2c6-2c52-453d-b4ed-9b74d3888951",
            "sourceColumn": "frst_regist_year",
            "summarizeBy": "none"
          },
          {
            "name": "frst_regist_de",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e16ece9-9620-4427-bed2-4f631fe48394",
            "sourceColumn": "frst_regist_de",
            "summarizeBy": "none"
          },
          {
            "name": "ybl_md",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb1a5f8c-720d-45f5-970b-7f1d4e08baaf",
            "sourceColumn": "ybl_md",
            "summarizeBy": "none"
          },
          {
            "name": "js",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb41e589-5a46-4b51-8572-2bbebf1d8e2f",
            "sourceColumn": "js",
            "summarizeBy": "none"
          },
          {
            "name": "jgyh",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b0102aa6-3f64-40ea-8074-b270098090ce",
            "sourceColumn": "jgyh",
            "summarizeBy": "none"
          },
          {
            "name": "sssgb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5ad1a92-59a1-4d65-938b-c9e1529a94e2",
            "sourceColumn": "sssgb",
            "summarizeBy": "none"
          },
          {
            "name": "car_sz",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "504f3561-8110-40fd-8efd-e738a34597a8",
            "sourceColumn": "car_sz",
            "summarizeBy": "none"
          },
          {
            "name": "car_bt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e317d5d-906a-4bfc-bd95-eabebcfeb2d4",
            "sourceColumn": "car_bt",
            "summarizeBy": "none"
          },
          {
            "name": "fuel1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8966ca55-c142-46a1-bc23-63d975ce6006",
            "sourceColumn": "fuel1",
            "summarizeBy": "none"
          },
          {
            "name": "fuel2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c7c022c-2010-4ee4-acab-8e58aaea59e3",
            "sourceColumn": "fuel2",
            "summarizeBy": "none"
          },
          {
            "name": "dsplvl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "88d5b45d-6cbc-40bb-b9b4-10121246fb5b",
            "sourceColumn": "dsplvl",
            "summarizeBy": "sum"
          },
          {
            "name": "grbx_knd_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1353bc00-e24f-4a4a-ba6c-3510f0bc26cd",
            "sourceColumn": "grbx_knd_nm",
            "summarizeBy": "none"
          },
          {
            "name": "cbd_lt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c381ec81-a4fb-4aca-be6c-914945c85b7f",
            "sourceColumn": "cbd_lt",
            "summarizeBy": "sum"
          },
          {
            "name": "cbd_bt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9a54a281-7947-4ddb-87b2-7c5d47c10fd9",
            "sourceColumn": "cbd_bt",
            "summarizeBy": "sum"
          },
          {
            "name": "cbd_hg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ab64a4a9-b16e-4a8c-8939-a5b476aa4ea1",
            "sourceColumn": "cbd_hg",
            "summarizeBy": "sum"
          },
          {
            "name": "whlb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f9a7d0c3-eadb-4911-8e2e-a00acab6bafc",
            "sourceColumn": "whlb",
            "summarizeBy": "sum"
          },
          {
            "name": "tkcar_pscap_co",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "325c55b4-f50f-451a-9fac-59c274391043",
            "sourceColumn": "tkcar_pscap_co",
            "summarizeBy": "sum"
          },
          {
            "name": "mxmm_ldg",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "24acd0ca-580c-4067-a451-5c4a45722aac",
            "sourceColumn": "mxmm_ldg",
            "summarizeBy": "sum"
          },
          {
            "name": "cvgb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6acec5af-3c47-4f99-a2bd-c8060366b869",
            "sourceColumn": "cvgb",
            "summarizeBy": "none"
          },
          {
            "name": "cv_maker",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1657ccc6-539f-47fc-9ab8-f54122bc01d1",
            "sourceColumn": "cv_maker",
            "summarizeBy": "none"
          },
          {
            "name": "reg_section",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9a0ab67-479c-4e8c-8457-c1e9b76bb3f8",
            "sourceColumn": "reg_section",
            "summarizeBy": "none"
          },
          {
            "name": "ydgb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46efb2d1-a336-4423-aa10-5dc46bc0add7",
            "sourceColumn": "ydgb",
            "summarizeBy": "none"
          },
          {
            "name": "car_use",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9ccdca78-869b-45f6-bdbb-66ccfd7955f5",
            "sourceColumn": "car_use",
            "summarizeBy": "none"
          },
          {
            "name": "car_use_detal",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "13c59714-f94f-434c-97f3-6829ed2d8efe",
            "sourceColumn": "car_use_detal",
            "summarizeBy": "none"
          },
          {
            "name": "acqs_amount",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f01c3ced-7922-43c3-8061-99b324a7a594",
            "sourceColumn": "acqs_amount",
            "summarizeBy": "sum"
          },
          {
            "name": "bf_sou_gb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21883571-dc2e-4174-bfb0-0eb7c66a8e06",
            "sourceColumn": "bf_sou_gb",
            "summarizeBy": "none"
          },
          {
            "name": "bf_sou_age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bf56411-eb75-4ddd-90dd-ec5b7b8c4401",
            "sourceColumn": "bf_sou_age",
            "summarizeBy": "none"
          },
          {
            "name": "bf_sou_gen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "862149fa-89f9-4e13-a897-626e4d02ce03",
            "sourceColumn": "bf_sou_gen",
            "summarizeBy": "none"
          },
          {
            "name": "sou_gb",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89f54635-285d-4033-be0c-d974d44ec422",
            "sourceColumn": "sou_gb",
            "summarizeBy": "none"
          },
          {
            "name": "sou_age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a23aa898-2dc9-46b4-8290-6911dd0ff268",
            "sourceColumn": "sou_age",
            "summarizeBy": "none"
          },
          {
            "name": "sou_gen",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc43724c-a210-4a79-ac0e-c2d0bba0e99e",
            "sourceColumn": "sou_gen",
            "summarizeBy": "none"
          },
          {
            "name": "bf_use_strnghld_adres_nm_sd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30f065c9-6f91-4662-9ec0-d2b83886723f",
            "sourceColumn": "bf_use_strnghld_adres_nm_sd",
            "summarizeBy": "none"
          },
          {
            "name": "bfchg_use_strnghld_adres_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b6231dbd-bfe7-42f2-854f-748ac3c01d47",
            "sourceColumn": "bfchg_use_strnghld_adres_nm",
            "summarizeBy": "none"
          },
          {
            "name": "use_strnghld_adres_nm_sd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6012bb95-9ac2-45cc-ae18-b6a727b50bea",
            "sourceColumn": "use_strnghld_adres_nm_sd",
            "summarizeBy": "none"
          },
          {
            "name": "use_strnghld_adres_nm_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b43ebf1f-e2b1-4845-bd76-af66a121134b",
            "sourceColumn": "use_strnghld_adres_nm_nm",
            "summarizeBy": "none"
          },
          {
            "name": "owner_adres_nm_sd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5cb48751-5be9-4cea-abc4-1c6adae724f0",
            "sourceColumn": "owner_adres_nm_sd",
            "summarizeBy": "none"
          },
          {
            "name": "owner_adres_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "968d8f3d-02ba-4ecd-94d9-1e60c94b158f",
            "sourceColumn": "owner_adres_nm",
            "summarizeBy": "none"
          },
          {
            "name": "trvl_dstnc",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2abcd510-ae39-4f61-83c1-4b0aeecce547",
            "sourceColumn": "trvl_dstnc",
            "summarizeBy": "sum"
          },
          {
            "name": "maximum_rpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7568c397-b237-49cd-8e95-00427d5e7836",
            "sourceColumn": "maximum_rpm",
            "summarizeBy": "sum"
          },
          {
            "name": "fuel_rate",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "43b3e936-04bc-4090-9256-75a364ed3538",
            "sourceColumn": "fuel_rate",
            "summarizeBy": "sum"
          },
          {
            "name": "weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ed28c30c-25bf-4974-9cfa-c5229f549c39",
            "sourceColumn": "weight",
            "summarizeBy": "sum"
          },
          {
            "name": "total_weight",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fb869544-9d98-4df1-8628-cbdec867b943",
            "sourceColumn": "total_weight",
            "summarizeBy": "none"
          },
          {
            "name": "rpm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6785d9ef-c0bf-44e4-8b9f-449490c33f8e",
            "sourceColumn": "rpm",
            "summarizeBy": "none"
          },
          {
            "name": "front_tire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4911cba1-d4ea-4447-8e8c-3fb4441abe5e",
            "sourceColumn": "front_tire",
            "summarizeBy": "none"
          },
          {
            "name": "rear_tire",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4b8cf459-34ed-4fa1-8d3a-ef70d9e6e60d",
            "sourceColumn": "rear_tire",
            "summarizeBy": "none"
          },
          {
            "name": "drive_sys",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef93359f-8c00-4ac7-aa62-e16e62a10922",
            "sourceColumn": "drive_sys",
            "summarizeBy": "none"
          },
          {
            "name": "dms_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "78c14dca-64d2-4672-9131-9dda5ce92ac1",
            "sourceColumn": "dms_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_8badf1cf-10bb-4686-8110-a46ffe56e4f3"
                },
                "isDefault": true,
                "relationship": "36aff095-3507-45b0-a9af-5951b2da10dc"
              }
            ]
          },
          {
            "name": "dms_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "b36db22c-612e-4cc3-b510-ffb256213989",
            "sourceColumn": "dms_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "변형",
                "defaultHierarchy": {
                  "hierarchy": "날짜 계층",
                  "table": "LocalDateTable_04ec9ba3-8762-4ecf-9587-a808e501f99f"
                },
                "isDefault": true,
                "relationship": "89c89561-837b-4e98-86e1-35a4a1c6b24d"
              }
            ]
          },
          {
            "name": "reg_if_batch_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6a3447d4-4897-4d0a-9e42-29b9bbf2dc06",
            "sourceColumn": "reg_if_batch_cd",
            "summarizeBy": "none"
          },
          {
            "name": "reg_if_batch_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1609417e-0a1c-4eb9-8bc5-e5626b149e13",
            "sourceColumn": "reg_if_batch_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "upd_if_batch_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ae29866-19e6-4196-be8b-09fab8f28660",
            "sourceColumn": "upd_if_batch_cd",
            "summarizeBy": "none"
          },
          {
            "name": "upd_if_batch_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "19e5b2ff-a680-4fca-934e-a0e66c01d860",
            "sourceColumn": "upd_if_batch_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "sido",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "\"서울특별시\"",
            "isDataTypeInferred": true,
            "lineageTag": "d5a6870d-8fbc-42a3-87f7-5a89aeb8e22c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "76bbdef0-c0de-43dc-a4f9-c45da7d1b20e",
        "partitions": [
          {
            "name": "dms_if_nicednr_live_car",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    원본 = Odbc.DataSource(\"dsn=aws-rds\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = 원본{[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_if_nicednr_live_car_Table = dev_twice_Schema{[Name=\"dms_if_nicednr_live_car\",Kind=\"Table\"]}[Data],",
                "    #\"추가된 인덱스\" = Table.AddIndexColumn(dms_if_nicednr_live_car_Table, \"인덱스\", 0, 1, Int64.Type),",
                "    #\"제거된 열 수\" = Table.RemoveColumns(#\"추가된 인덱스\",{\"인덱스\"}),",
                "    #\"추가된 사용자 지정 항목\" = Table.AddColumn(#\"제거된 열 수\", \"사용자 지정\", each [bfchg_use_strnghld_adres_nm]),",
                "    #\"이름을 바꾼 열 수\" = Table.RenameColumns(#\"추가된 사용자 지정 항목\",{{\"use_strnghld_adres_nm\", \"sido\"}}),",
                "    #\"제거된 열 수1\" = Table.RemoveColumns(#\"이름을 바꾼 열 수\",{\"사용자 지정\"}),",
                "    #\"이름을 바꾼 열 수1\" = Table.RenameColumns(#\"제거된 열 수1\",{{\"sido\", \"use_strnghld_adres_nm_nm\"}}),",
                "    #\"중복된 열\" = Table.DuplicateColumn(#\"이름을 바꾼 열 수1\", \"use_strnghld_adres_nm_nm\", \"use_strnghld_adres_nm_nm - 복사\"),",
                "    #\"이름을 바꾼 열 수2\" = Table.RenameColumns(#\"중복된 열\",{{\"use_strnghld_adres_nm_nm - 복사\", \"sido\"}}),",
                "    #\"제거된 열 수2\" = Table.RemoveColumns(#\"이름을 바꾼 열 수2\",{\"sido\"})",
                "in",
                "    #\"제거된 열 수2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_cf54104e-01a2-428f-bba3-42038d98d618",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dd3eba62-4bd1-482c-9a1e-c4b1b5a120d5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "ff355bed-729f-4bfb-93c6-6053d58cda38",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "12a28187-497c-4b7a-b6da-e72fba4eef9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "1d849914-7928-4c50-bf28-e56834efe016",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "5647af6c-16d6-4a07-8ef9-e88f4539e24f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2c4f89ae-c0d4-455d-9a8e-53d7da4a9628",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "758e8a79-453d-4191-8793-87ac9ccd62f1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "2e2f026a-6f88-4710-8ebb-dce67d4b8022",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "ad23dbe9-559e-4c92-ae22-9b4dbeda3fa7",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "b714e0c0-462f-4c56-a9ea-07a50d1d516d",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "3023e415-1abe-42eb-8332-4b42717c46f2",
                "ordinal": 3
              }
            ],
            "lineageTag": "6aed2d21-71f0-4e7b-8de4-5936937fa27c"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "9508f500-cb9c-46ca-ad19-2cd96569e6cb",
        "partitions": [
          {
            "name": "DateTableTemplate_cf54104e-01a2-428f-bba3-42038d98d618",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_8badf1cf-10bb-4686-8110-a46ffe56e4f3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a40bec30-d51e-45a0-9867-9ebcf9768fc5",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "9a54c420-c02f-4911-b75a-a2bbd362c700",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "46b8ad3f-0d90-4eb9-aab1-30148b9c2942",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "fa309edc-b61d-494a-8b8b-82bb6bc103c6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "da299f83-75a9-40cb-bee2-2d5a01f43f67",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f2e70742-ab3e-4a04-a7b8-aeb8d931e095",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "4c34cd9b-f889-4413-ad63-fde421937dad",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "01e3615e-55dc-4fdd-8051-a2bc57018821",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "dd13b479-bd86-411b-a6af-b53078003822",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "dc9c722b-41a9-4734-bcac-71ed9924f1b1",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "321edaba-d10f-4a56-b8ed-3a1365eddc4e",
                "ordinal": 3
              }
            ],
            "lineageTag": "f34f119e-abff-47b6-a1b9-5efb01154fe8"
          }
        ],
        "isHidden": true,
        "lineageTag": "8c92d91b-4a6e-4f62-b821-17eda80990d9",
        "partitions": [
          {
            "name": "LocalDateTable_8badf1cf-10bb-4686-8110-a46ffe56e4f3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_if_nicednr_live_car'[dms_reg_dt])), 1, 1), Date(Year(MAX('dms_if_nicednr_live_car'[dms_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_04ec9ba3-8762-4ecf-9587-a808e501f99f",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "formatString": "General Date",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "4c755369-f0a2-458d-ae45-ddc590148f8a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "연도",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "fef64bc7-91b1-42cd-8ab6-64c437dd451b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "c2035835-b12f-414a-95da-4e632bfa0d49",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "월",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "866cffba-5764-41cd-bfce-aaa11e3f48cf",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "769c74fb-d433-4109-90c7-4a94794bc699",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "분기",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"분기 \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c188422b-0f24-4c53-8b8e-7765b229ed1f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "일",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "formatString": "0",
            "isHidden": true,
            "lineageTag": "60fcf456-bd59-459e-94d4-05831211f332",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "날짜 계층",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "연도",
                "column": "연도",
                "lineageTag": "ca05b08f-7057-41d4-abd3-2d4fbd5425c3",
                "ordinal": 0
              },
              {
                "name": "분기",
                "column": "분기",
                "lineageTag": "745e8243-167f-460a-84ff-c171f638e0b5",
                "ordinal": 1
              },
              {
                "name": "월",
                "column": "월",
                "lineageTag": "e8fe2358-5863-40ee-8606-76166f3c9248",
                "ordinal": 2
              },
              {
                "name": "일",
                "column": "일",
                "lineageTag": "49a2a188-51cf-427d-853f-336d7561db90",
                "ordinal": 3
              }
            ],
            "lineageTag": "e8be7ab2-1a16-444f-a3d9-1ea8b822aca1"
          }
        ],
        "isHidden": true,
        "lineageTag": "3fe31028-1d55-4c9a-ae25-f0390e2b9d18",
        "partitions": [
          {
            "name": "LocalDateTable_04ec9ba3-8762-4ecf-9587-a808e501f99f",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_if_nicednr_live_car'[dms_upd_dt])), 1, 1), Date(Year(MAX('dms_if_nicednr_live_car'[dms_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}