{
  "compatibilityLevel": 1567,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"measure(Service)\",\"dms_co_brand\",\"dms_co_code\",\"dms_co_vehic\",\"dms_sales_contract\",\"dms_svc_kpi_resource\",\"dms_svc_resv\",\"dms_svc_ro\",\"dms_co_variant\",\"dms_svc_ro_sales\",\"dms_svc_act8_cust_v\",\"v_dim_calendar\",\"v_dim_dealer\",\"v_fact_dealer_sales_target\",\"v_fact_svc_type_detail\",\"v_dim_dealer_l\",\"v_dim_dealer_t\",\"v_dim_group\",\"dms_svc_act8_cust_retail_year_v\",\"v_fact_capa_kpi\",\"dms_co_variant_v\",\"dms_sales_customer_traffic\",\"dms_sales_kpi_resource_day\",\"dms_sales_testdrive\",\"v_fact_contract_conversion_daily_sales\",\"v_fact_local_stock_sales\",\"dms_co_report_variant_v\",\"dms_sales_kpi_history\",\"dms_co_kpi_resource\",\"dms_sales_kpi_resource\",\"v_dim_dealer_sales\",\"v_dim_group_sales\",\"v_fact_stock_info\",\"v_sales_contract_forecast\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.126.1261.0 (24.02)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "ko-KR",
    "cultures": [
      {
        "name": "ko-KR",
        "linguisticMetadata": {}
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "relationships": [
      {
        "name": "e3e90591-3d75-4683-b071-d01a876768ea",
        "fromColumn": "regist_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_ee3385bf-1cae-4dfa-bd65-d63cb8fba3b8"
      },
      {
        "name": "4674d163-68f7-4446-9a38-9fa88f43fcca",
        "fromColumn": "lineoff_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_17b78f12-9094-407e-b503-34fac1d122a6"
      },
      {
        "name": "dc6a4502-bd1d-461c-9baa-ec8e20992e61",
        "fromColumn": "delivery_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_08351f4d-4d3c-4b9c-8dcb-1f9b7cf93194"
      },
      {
        "name": "3f7c178a-877c-4470-83da-b4379e69ca53",
        "fromColumn": "real_resv_dt",
        "fromTable": "dms_svc_resv",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6ccbc330-3633-4ff8-8015-ab2c92b5c621"
      },
      {
        "name": "d1d40580-aeee-4c1f-b9ad-4fb2bed013d9",
        "fromColumn": "resv_reg_dt",
        "fromTable": "dms_svc_resv",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_25c3233b-52b3-4306-9c62-d2fc8ef22e46"
      },
      {
        "name": "551dec2d-df40-4e34-a654-7dd4ed6d4fb8",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_svc_ro",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "ed4a71b9-1654-4ccc-b59a-4b423d052582",
        "fromColumn": "sales_dt",
        "fromTable": "dms_svc_ro_sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_2265f050-6358-412e-aba6-8fab6e0db912"
      },
      {
        "name": "969eb54c-9ff2-4628-991d-3f96199daf5a",
        "fromColumn": "ro_reg_dt",
        "fromTable": "dms_svc_ro",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_206d6f31-9f04-40a7-bbe0-440b93664244"
      },
      {
        "name": "ce9b2582-754e-421e-aa02-3ae35ef90e26",
        "fromColumn": "port_in_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_29db8caa-5b03-4937-bd1d-bbb566a4b65a"
      },
      {
        "name": "768ec85d-f11e-4f84-b69f-45e5a14d6c6c",
        "fromColumn": "retailsales_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_97123f9e-5cf6-41c7-b2ae-230ca5003e1b"
      },
      {
        "name": "d1615a2b-fe3b-4cce-9d84-e64119646296",
        "fromColumn": "wholesales_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_9e8cebc1-50a2-4b3a-87c6-6c57886cc384"
      },
      {
        "name": "9e249483-7073-489e-8d8c-df93f9f711ed",
        "fromColumn": "loss_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_71db58b9-f4da-4303-866b-8e5fd6e08d3d"
      },
      {
        "name": "c6c4ae06-b881-496c-8bab-ec96fa029eb1",
        "fromColumn": "internal_dt",
        "fromTable": "dms_co_vehic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_97ae6b8d-eaa0-455f-b998-e8b739b50e9a"
      },
      {
        "name": "7aae4e05-2abb-4c2c-baee-c0f600b5ba9c",
        "fromColumn": "dt",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "dc6b4eed-8827-4aab-8b5e-b8a48feacdce",
        "fromColumn": "yyyymmdd",
        "fromTable": "dms_svc_act8_cust_v",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "dc3684d1-63a6-4fd1-b81b-2efd25e69419",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "3d56a952-c48b-437a-a458-b72e069fb7c0",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "d5ee2ebd-f4e3-4527-a3a9-a3bbe09d1755",
        "fromColumn": "dt",
        "fromTable": "v_fact_svc_type_detail",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "93e96d51-2b9e-4eb1-b7f1-756c556df1de",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_svc_type_detail",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "8cfe19a3-7bfc-4827-9c8b-591f573e0893",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_svc_type_detail",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "5f295923-2905-4f3c-9463-09e0b39e46f5",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_svc_type_detail",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "3fb5f25e-af54-4c74-a74a-f150fdee9fdd",
        "fromColumn": "group_id",
        "fromTable": "dms_svc_ro",
        "toColumn": "group_id",
        "toTable": "v_dim_group"
      },
      {
        "name": "75275b49-f29c-470c-9ae3-cc742e9ffb25",
        "fromColumn": "date",
        "fromTable": "previous_date",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a42184ff-f71f-4dd8-ab72-d572295cb8e6"
      },
      {
        "name": "3fa231c1-61eb-4596-a47c-b9a65af9ab69",
        "fromColumn": "date",
        "fromTable": "v_dim_calendar",
        "isActive": false,
        "toColumn": "date",
        "toTable": "previous_date"
      },
      {
        "name": "df48f08f-f8f8-419d-bcd6-cbead90807ea",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "3493c81b-4db3-4d83-9f50-bedf635cd3a9",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "0e4131ee-23f9-4f54-a460-b663b1796572",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "51e2cc9c-3826-4c34-b42e-41b04de87280",
        "fromColumn": "dt",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "date",
        "toTable": "previous_date"
      },
      {
        "name": "b9653361-da37-4bd1-a750-fb02e0662893",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_svc_act8_cust_v",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "e012caba-b4f6-45bd-882d-f7c846d48979",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_retail_year_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "f9848365-ef38-4861-b365-7eda091bbd9c",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_retail_year_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "38f4e118-1a20-46e6-a049-8eeba7fbcf92",
        "fromColumn": "yyyymmdd",
        "fromTable": "dms_svc_act8_cust_retail_year_v",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "ad1b72c8-1ce0-4c07-a87e-84d35ff22330",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_svc_kpi_resource",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "72d6bba5-aa92-451d-81d9-6bfb59dd8b39",
        "fromColumn": "YYYYMMDD",
        "fromTable": "dms_svc_kpi_resource",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "21ce6e95-50cc-4d23-be11-66584d934679",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_kpi_resource",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "0940f500-08d3-40b1-b1c4-6ff8c10bd060",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_kpi_resource",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "f6bcfb38-eff0-4321-985a-3e8b52504746",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_kpi_resource",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "fc1f0d88-8efd-4d90-9951-f3582716d73d",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_fact_capa_kpi",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "1bca76bf-0a8f-406d-86d0-b51663c22aa0",
        "fromColumn": "yyyymmdd",
        "fromTable": "v_fact_capa_kpi",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "789867c5-7d4d-481b-a7a8-877c5fc97a96",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_fact_dealer_sales_target",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "9ec8fa73-8215-42ba-b8e7-4abdc142b6f1",
        "fromColumn": "dealer_id",
        "fromTable": "v_dim_group",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_l"
      },
      {
        "name": "8e74f990-faf7-422e-8d5e-358c37cfeea1",
        "fromColumn": "dealer_id",
        "fromTable": "v_dim_group",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "eeb6c65b-b353-420c-a200-a8f81b349ef5",
        "fromColumn": "dealer_id",
        "fromTable": "v_dim_group",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer_t"
      },
      {
        "name": "80de6183-cb18-4a96-8cb0-7d9812b4128b",
        "fromColumn": "group_id",
        "fromTable": "v_fact_capa_kpi",
        "toColumn": "group_id",
        "toTable": "v_dim_group"
      },
      {
        "name": "d63255a3-8295-46d7-a1bb-febea6d9e850",
        "fromColumn": "ro_close_dt",
        "fromTable": "dms_svc_ro",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_3414bbc0-0998-4b37-a847-3f8de40a0059"
      },
      {
        "name": "2bbaa5bd-c860-9707-18e2-31ca35ca1513",
        "fromColumn": "yyyymmdd",
        "fromTable": "dms_svc_ro",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "eda473ff-5482-4f7d-ad08-a68608835fe9",
        "fromColumn": "dms_bi_reg_dt",
        "fromTable": "dms_sales_customer_traffic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6212944b-4331-4157-8510-062bba0bba6d"
      },
      {
        "name": "7521be78-7a97-472c-8111-efee9c3935cd",
        "fromColumn": "dms_bi_upd_dt",
        "fromTable": "dms_sales_customer_traffic",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_a6ec5deb-3c10-4ee5-a1b0-adbf2364851a"
      },
      {
        "name": "d052977d-2b2a-4ebe-94a4-6a7a08c8b35a",
        "fromColumn": "dms_bi_reg_dt",
        "fromTable": "dms_sales_kpi_resource_day",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_44491dc9-7093-4ea3-a163-863857ea72aa"
      },
      {
        "name": "a0e2adb1-7aac-4293-bd58-e3e96e04f515",
        "fromColumn": "dms_bi_upd_dt",
        "fromTable": "dms_sales_kpi_resource_day",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_52f6b028-e7be-4fdc-9711-bd21f9578454"
      },
      {
        "name": "75cb1c36-f464-4af7-848f-1983bedc4229",
        "fromColumn": "dms_bi_reg_dt",
        "fromTable": "dms_sales_testdrive",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7bb56323-3235-4b35-a406-fe7de7dcaa63"
      },
      {
        "name": "5ec862e8-ffde-4aa6-acd6-519d62bc69ff",
        "fromColumn": "dms_bi_upd_dt",
        "fromTable": "dms_sales_testdrive",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_449fadeb-aeeb-4450-a978-884e920a2166"
      },
      {
        "name": "126aab3f-93a9-49c7-bed7-6f50c233d6dd",
        "fromColumn": "reserved_st_dt",
        "fromTable": "dms_sales_testdrive",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_866b0a4b-662d-4de2-b00d-6813cba759fa"
      },
      {
        "name": "89021e9e-3e7c-4fb8-8022-179445b47d17",
        "fromColumn": "reserved_end_dt",
        "fromTable": "dms_sales_testdrive",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7c9aaea1-343b-468c-8c49-c2cbe5b98378"
      },
      {
        "name": "2f4d4361-cf9c-4915-b9df-4d5ad1ae262f",
        "fromColumn": "regist_dt",
        "fromTable": "v_fact_local_stock_sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_547bae4a-e835-49b1-a1d9-cc14ba120b64"
      },
      {
        "name": "0ffa235f-37d9-4a32-afe9-1458e2e0e3a9",
        "fromColumn": "lineoff_dt",
        "fromTable": "v_fact_local_stock_sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_b052abb8-6c3d-4b0d-b025-57032a34093d"
      },
      {
        "name": "87136e60-c7cb-4a69-b2a7-5244dd6bd16c",
        "fromColumn": "delivery_dt",
        "fromTable": "v_fact_local_stock_sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1188d505-dd7e-423b-9e6f-bd0259f8e146"
      },
      {
        "name": "9be3018b-8d3f-4389-9b45-ef236eec924e",
        "fromColumn": "wholesales_dt",
        "fromTable": "v_fact_local_stock_sales",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_1fad5556-b440-4add-91ed-e11b1bfdc7a1"
      },
      {
        "name": "32bd0822-173f-4601-ac4b-f1bca40cba13",
        "fromColumn": "contract_reg_dt",
        "fromTable": "dms_sales_contract",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "8637837d-879f-4fa0-977a-d63cf5c07fba",
        "fromColumn": "retail_sales_dt",
        "fromTable": "dms_sales_contract",
        "isActive": false,
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "99c93fb3-08ef-499c-950d-e3c00d159508",
        "fromColumn": "cancel_dt",
        "fromTable": "dms_sales_contract",
        "isActive": false,
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "ce039eb0-4856-4059-bb35-8cfe4baabbff",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_contract",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "15d7ca83-700b-4fc2-afa5-f4e7f1c053d2",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_sales_contract",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "92eeba51-c6c2-4a25-9f8e-fe659a3fa783",
        "fromColumn": "b_report_variant_cd",
        "fromTable": "dms_co_variant_v",
        "toColumn": "b_report_variant_cd",
        "toTable": "dms_co_report_variant_v"
      },
      {
        "name": "f1a5d8b4-2d48-4581-817d-ca9d7acb0c76",
        "fromColumn": "yyyymmdd(Date)",
        "fromTable": "dms_sales_kpi_resource_day",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "ac487c92-1302-4a3c-9ee5-b1fe9987ba3d",
        "fromColumn": "b_report_variant_cd",
        "fromTable": "dms_sales_kpi_resource_day",
        "toColumn": "b_report_variant_cd",
        "toTable": "dms_co_report_variant_v"
      },
      {
        "name": "2960f843-e15a-4acd-9157-c1f853dfb91f",
        "fromColumn": "dealer_id",
        "fromTable": "dms_sales_kpi_resource_day",
        "toColumn": "group_id",
        "toTable": "v_dim_group"
      },
      {
        "name": "f666a225-72a4-4e06-9af9-8f08134ebab8",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_sales_testdrive",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "10a131d2-20ab-4c3c-95e0-76fde1b8ab23",
        "fromColumn": "reserved_dt",
        "fromTable": "dms_sales_testdrive",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "435e1ca2-c4dd-4d90-ada9-0205a713c2ed",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_sales_customer_traffic",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "d04b78b3-c71d-45ef-8414-be6d32c75910",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_customer_traffic",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "dc398a05-8b1e-4bae-beb3-488253d9c1d4",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_testdrive",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "099ccd83-5191-4120-ab72-83c290501417",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_kpi_resource_day",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "9bb247c9-bc9b-4831-b3e5-a359caa7be99",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_co_variant",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "e531e112-b664-43e4-ae30-66280f8620b1",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_co_variant",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "77fa44d4-b6d1-4fb9-b50d-52266f3e2f2e",
        "fromColumn": "YYYYMMDD",
        "fromTable": "dms_co_variant",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "aa07c0c9-36da-4304-87a8-456a7799a637",
        "fromColumn": "b_report_variant_cd",
        "fromTable": "v_fact_contract_conversion_daily_sales",
        "toColumn": "b_report_variant_cd",
        "toTable": "dms_co_report_variant_v"
      },
      {
        "name": "1433efab-e757-4bed-8bf8-d738f6305896",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_fact_contract_conversion_daily_sales",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "75fbe853-b701-402a-9359-49b732dd67d7",
        "fromColumn": "dt",
        "fromTable": "v_fact_contract_conversion_daily_sales",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "6bbbee07-6db5-451b-9f26-189f5cba345e",
        "fromColumn": "port_in_dt",
        "fromTable": "v_fact_local_stock_sales",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "25078799-7f40-40a1-a676-4a4f31b83366",
        "fromColumn": "contract_reg_dt",
        "fromTable": "v_fact_local_stock_sales",
        "isActive": false,
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "07f408ab-b411-4a45-a321-3580d949b3f1",
        "fromColumn": "retailsales_dt",
        "fromTable": "v_fact_local_stock_sales",
        "isActive": false,
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "9f01c68e-21b2-4d41-8fcb-d61b20231fef",
        "fromColumn": "b_report_variant_cd",
        "fromTable": "v_fact_local_stock_sales",
        "toColumn": "b_report_variant_cd",
        "toTable": "dms_co_report_variant_v"
      },
      {
        "name": "6d218a2d-2112-4737-aabe-92c7c96790fb",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_fact_local_stock_sales",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "61fb9455-9d4f-456d-8025-85271584e263",
        "fromColumn": "dealer_id",
        "fromTable": "v_fact_local_stock_sales",
        "toColumn": "group_id",
        "toTable": "v_dim_group"
      },
      {
        "name": "fe686a22-4ed5-422e-8b16-611c7efb9174",
        "fromColumn": "recept_dt",
        "fromTable": "dms_sales_customer_traffic",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "1d4388d4-891e-4da7-aa96-6bf7d7742580",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_sales_kpi_history",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "db7b1fef-471d-4075-9680-4a64d406864e",
        "fromColumn": "dealer_id",
        "fromTable": "dms_sales_kpi_history",
        "toColumn": "group_id",
        "toTable": "v_dim_group"
      },
      {
        "name": "2a3f88b5-f447-4410-9f3f-0f93cc5f8012",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_kpi_history",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "69ec8c7b-f3f7-4708-9333-f2fd807ea963",
        "fromColumn": "YYYYMMDD",
        "fromTable": "dms_sales_kpi_history",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "fa1dff28-9ab2-4d6f-b34c-e9ada5e15cd9",
        "fromColumn": "dt",
        "fromTable": "v_fact_svc_type_detail",
        "toColumn": "date",
        "toTable": "previous_date"
      },
      {
        "name": "659c5fb9-85f5-4a36-9990-6a869722aa4b",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "51adf202-769d-4fae-bf66-e33c699e037b",
        "fromColumn": "dealer_id",
        "fromTable": "dms_svc_act8_cust_retail_year_v",
        "toColumn": "dealer_id",
        "toTable": "v_dim_dealer"
      },
      {
        "name": "6f5de9c6-8533-43c2-896f-742aa437a36b",
        "fromColumn": "dms_bi_reg_dt",
        "fromTable": "dms_co_kpi_resource",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_e8f7a042-f709-48fb-8ca2-f8fc52da0f86"
      },
      {
        "name": "b918b134-a04a-4eff-94c8-025684df0bde",
        "fromColumn": "dms_bi_upd_dt",
        "fromTable": "dms_co_kpi_resource",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_02eff536-60f7-4e9b-9b31-d65fd367cc80"
      },
      {
        "name": "06ee9f09-4b43-4379-84c7-f8b347e6f5f7",
        "fromColumn": "dms_bi_reg_dt",
        "fromTable": "dms_sales_kpi_resource",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_6df59a7f-babe-4480-91aa-14f82232dba1"
      },
      {
        "name": "458ac7df-e4e0-4f71-8459-5266c75bcd73",
        "fromColumn": "dms_bi_upd_dt",
        "fromTable": "dms_sales_kpi_resource",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_05913f03-ec40-4ce6-acbb-3684a3e5ff43"
      },
      {
        "name": "aaaee4e5-ba26-4d13-a32e-b9ce503977d3",
        "fromColumn": "port_in_dt",
        "fromTable": "v_fact_stock_info",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_59d7de8b-c00f-4857-8439-8a6700785696"
      },
      {
        "name": "5629ebb5-84a7-4a1a-8f96-6aee29f21b2b",
        "fromColumn": "retailsales_dt",
        "fromTable": "v_fact_stock_info",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_c442de05-9937-4533-a08e-d1315ec38db0"
      },
      {
        "name": "a28c1f17-3cb9-4b73-8c4e-ec2e9ba75cec",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_fact_stock_info",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "dc909608-60e4-49a3-a9c4-9a9b4388f900",
        "fromColumn": "b_report_variant_cd",
        "fromTable": "v_fact_stock_info",
        "toColumn": "b_report_variant_cd",
        "toTable": "dms_co_report_variant_v"
      },
      {
        "name": "77d00c0f-e46f-420a-acc1-d67eecd71d49",
        "fromColumn": "group_key",
        "fromTable": "v_fact_stock_info",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "4a2b5bc4-6206-4971-b0c3-4099a56a4f17",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_contract",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "8f1fd2af-3ebc-4e1c-a4f8-10be1c84fe35",
        "fromColumn": "group_key",
        "fromTable": "v_fact_local_stock_sales",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "a3398862-9d10-439a-93b7-57c460d5fafe",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_kpi_resource_day",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "34bd8c0a-bd5c-472c-96b9-8f4b42eb3b15",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_customer_traffic",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "68f11149-1375-4440-9fe4-98f5feec3d30",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_testdrive",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "64192886-f219-4018-828e-d0c813d12311",
        "fromColumn": "YYYYMMDD",
        "fromTable": "dms_sales_kpi_resource",
        "toColumn": "date",
        "toTable": "v_dim_calendar"
      },
      {
        "name": "07aa7ff3-3c40-4b03-a47f-7095c624dc2c",
        "fromColumn": "dms_brand_cd",
        "fromTable": "dms_sales_kpi_resource",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "8938ba75-5a46-4701-89b4-9dc5b2dbb870",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_kpi_resource",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "f87081ea-c5cb-4c8c-9e0b-c777346df9b3",
        "fromColumn": "b_variant_cd",
        "fromTable": "dms_sales_kpi_resource",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "63cdc050-95a0-4c4f-a18f-73372ff119ef",
        "fromColumn": "dealer_key",
        "fromTable": "v_fact_contract_conversion_daily_sales",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "3538bd4b-d75c-4f3b-a08b-6f6f743dd28e",
        "fromColumn": "group_key",
        "fromTable": "dms_sales_kpi_history",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "b52fb450-e293-4d9e-92fd-99b87b1f4942",
        "fromColumn": "group_key",
        "fromTable": "v_sales_contract_forecast",
        "toColumn": "group_key",
        "toTable": "v_dim_group_sales"
      },
      {
        "name": "79f1cb3c-3005-4ffb-a89c-71656e21b205",
        "fromColumn": "dms_brand_cd",
        "fromTable": "v_sales_contract_forecast",
        "toColumn": "dms_brand_cd",
        "toTable": "dms_co_brand"
      },
      {
        "name": "a679d8a2-9289-4f8b-a223-4e1ed5cd64dc",
        "fromColumn": "b_variant_cd",
        "fromTable": "v_sales_contract_forecast",
        "toColumn": "b_variant_cd",
        "toTable": "dms_co_variant_v"
      },
      {
        "name": "034e3c60-ee49-46d7-933f-0718922d73a6",
        "fromColumn": "dt",
        "fromTable": "v_sales_contract_forecast",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_884b4813-db7e-4c7d-83dc-10197a7ed0f3"
      }
    ],
    "sourceQueryCulture": "ko-KR",
    "tables": [
      {
        "name": "DateTableTemplate_b27ce2c5-53b2-401c-a29b-92672c5d306c",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "8c401578-99aa-4df8-bdc5-0e790d9369be",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b183bf11-0f3e-4e07-a1a4-46a471c5f5dc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "32ea3dca-b20c-4602-aafb-5de4824eac24",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a446ea2f-f4f4-4632-bfb0-fd1ce82b7127",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "49793163-a3e1-4f6c-9b75-db84b9f9fdd7",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0e863ed2-b2c5-40ab-85c5-c45dd4504d77",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "9a14fdb8-5d52-43bc-afdd-fe70ce5ef7c0",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "0ecabb0f-d0e0-4145-b994-393ce03a0426",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "bbc5b601-f217-4740-acb8-05b79c1fa13c",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "2987fbe1-6ef3-4ab3-91ea-944d1d065882",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "2e5ca1f2-70bd-4cd0-99be-3fe273306a08",
                "ordinal": 3
              }
            ],
            "lineageTag": "f77ec19d-7a97-4e4f-913d-4b0676c692d6"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "2ee62fc6-7010-44cd-bab7-8cea9951e347",
        "partitions": [
          {
            "name": "DateTableTemplate_b27ce2c5-53b2-401c-a29b-92672c5d306c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "measure(Service)",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "changedProperties": [
          {
            "property": "Name"
          }
        ],
        "lineageTag": "b5f628f6-3372-4f1f-b710-07e445fc107e",
        "measures": [
          {
            "name": "@_CAPA_GS_STATUS",
            "expression": [
              "",
              "IF(",
              "    [@_LT_WEEKDAYS_LM] <= 10 && [@_LT_WEEKENDS_LM] <= 14 && [#_GS_SA_LM] <= 12 && [#_GS_STALL_LM] <= 6.5 && [#_GS_TECH_LM] <= 6.5, \"1\"",
              ", -- ",
              "IF(",
              "    [@_LT_WEEKDAYS_LM] >= 15 || [@_LT_WEEKENDS_LM] >= 21 || [#_GS_SA_LM] >= 15 || [#_GS_STALL_LM] >= 8  || [#_GS_TECH_LM] >= 8,  \"0\" -- ",
              ", \"2\" --  )",
              "))"
            ],
            "lineageTag": "87efb96d-29fd-4c2a-a35f-2c1f7b345d51"
          },
          {
            "name": "@_CAPA_BP_STATUS",
            "expression": [
              "IF([#_BP_SA_LM] <= 5 && [#_BP_STALL_LM] <= 0.9 && [#_BP_TECH_LM] <= 0.9, \"1\", -- ",
              "            IF([#_BP_SA_LM] >= 7.5 || [#_BP_STALL_LM] >= 1.2 || [#_BP_TECH_LM] >= 1.2,  \"0\" -- ",
              "            , \"2\" --  )",
              "))"
            ],
            "lineageTag": "68bd6f06-63d9-4601-b26e-66706a7df962"
          },
          {
            "name": "@_CAPA_STATUS",
            "expression": [
              "",
              "IF([@_LT_WEEKDAYS_LM] <= 10 && [@_LT_WEEKENDS_LM] <= 14 && [#_GS_SA_LM] <= 12 && [#_GS_STALL_LM] <= 6.5 && [#_GS_TECH_LM] <= 6.5 && [#_BP_SA_LM] <= 5 && [#_BP_STALL_LM] <= 0.9 && [#_BP_TECH_LM] <= 0.9, \"1\", -- ",
              "",
              "IF([@_LT_WEEKDAYS_LM] >= 15 || [@_LT_WEEKENDS_LM] >= 21 || [#_GS_SA_LM] >= 15 || [#_GS_STALL_LM] >= 8 || [#_GS_TECH_LM] >= 8 || [#_BP_SA_LM] >= 7.5 && [#_BP_STALL_LM] >= 1.2 && [#_BP_TECH_LM] >= 1.2,  \"0\" -- ",
              "            ",
              ", \"2\" --  )",
              "))"
            ],
            "lineageTag": "47e32031-0f6b-42a2-9d2d-15c76f7869a5"
          },
          {
            "name": "@_ACTIVE_CRT_STATUS",
            "expression": [
              "IF([@_RATIO_ACTIVE_CRT_LY] > 0 && [@_RATIO_ACTIVE_CRT_TARGET] > 0 , \"1\", -- ",
              "            IF([@_RATIO_ACTIVE_CRT_LY] < 0 || [@_RATIO_ACTIVE_CRT_TARGET] < 0,  \"0\" -- ",
              "            , \"2\" --  )",
              "))"
            ],
            "lineageTag": "3325db9e-bad1-47c9-b85f-e7f29a8a5151"
          },
          {
            "name": "@_Calednar",
            "expression": [
              "",
              "    VAR _from = FORMAT(DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1), \"yyyy.mm\")",
              "    VAR _to = FORMAT(EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1), \"mm\")",
              " ",
              "RETURN ",
              "    IF(",
              "        OR(SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "            , SELECTEDVALUE('v_dim_calendar'[month]) = 2",
              "            )",
              "        ,  \"(\" & _from & \")\"",
              "    , \"(\" & _from & \"-\" & _to & \")\"",
              "    )"
            ],
            "lineageTag": "9c1b5f60-22d9-4032-88f9-3f0e6b939bd1"
          },
          {
            "name": "@_CY",
            "expression": "SELECTEDVALUE(v_dim_calendar[year])",
            "formatString": "0",
            "lineageTag": "727cd832-7f09-43a9-95ce-0d204a98ca3f"
          },
          {
            "name": "@_PY",
            "expression": "SELECTEDVALUE(v_dim_calendar[year]) -1",
            "formatString": "0",
            "lineageTag": "a5942b8f-8dd1-4c06-a3eb-b29269abd09b"
          },
          {
            "name": "@_VS_PY",
            "expression": "\"vs \" & ALLSELECTED(v_dim_calendar[year]) -1",
            "lineageTag": "77bbdf73-1fc6-42ed-8150-8f23c67cbb7a"
          },
          {
            "name": "@_Calednar_PM",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "    VAR PreviousMonthMonth = IF(SelectedMonth = 1, 1, SelectedMonth - 1)",
              "RETURN ",
              "    \"(\" & FORMAT(DATE(SelectedYear, PreviousMonthMonth, 1), \"YYYY.MM\") & \")\""
            ],
            "lineageTag": "a7a34da3-2e0b-4bf7-ac01-213d71754972"
          },
          {
            "name": "@_Y_MAX",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": "MAX([@_DLR_VALUE_YTD], [@_DLR_VALUE_YTD_LY])",
            "formatString": "0",
            "lineageTag": "6db1198c-9df2-42c3-8873-9da12299dbc8"
          },
          {
            "name": "@_Calednar_8Y",
            "expression": [
              "",
              "    VAR _SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR _SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = FORMAT(DATE(_SelectedYear, _SelectedMonth -96, 1), \"yyyy.mm\") -- 8Y ago",
              "    VAR _To = FORMAT(_SelectedYear, \"0000\") & \".\" & FORMAT(_SelectedMonth -1, \"00\")",
              "",
              "",
              "RETURN",
              "    \"(\"",
              "    & _From",
              "    &\"-\"",
              "    &_To",
              "    & \")\""
            ],
            "lineageTag": "d44150e0-d908-4980-a448-071a90e0280d"
          },
          {
            "name": "@_Calednar_WY",
            "expression": [
              "",
              "    VAR _SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR _SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = \"2009.01\"",
              "    VAR _To = FORMAT(_SelectedYear, \"0000\") & \".\" & FORMAT(_SelectedMonth -1, \"00\")",
              "",
              "",
              "RETURN",
              "    \"(\"",
              "    & _From",
              "    &\"-\"",
              "    &_To",
              "    & \")\""
            ],
            "lineageTag": "acbd005e-3a71-488c-9d41-3780224d708e"
          }
        ],
        "partitions": [
          {
            "name": "measure(Service)",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText(\"i44FAA==\", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [1 = _t]),",
                "    #\" \" = Table.TransformColumnTypes(,{{\"1\", type text}}),",
                "    #\"  \" = Table.RemoveColumns(#\" \",{\"1\"})",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "previous_date",
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fab6598191c74c6cb46dc091f51c00db"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "79e2fcbe-1d5a-424b-ba3f-3339d1c40b48",
            "sourceColumn": "v_dim_calendar[date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_a42184ff-f71f-4dd8-ab72-d572295cb8e6"
                },
                "isDefault": true,
                "relationship": "75275b49-f29c-470c-9ae3-cc742e9ffb25"
              }
            ]
          },
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "ad559e6e-25db-449f-9676-260bd93bdd86",
            "sourceColumn": "v_dim_calendar[year]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "35fd30f4-c079-4603-bde2-f2eb1e9497d4",
            "sourceColumn": "v_dim_calendar[month]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2838a09a-f371-4b4c-8dd4-8b614281d845",
            "sourceColumn": "v_dim_calendar[day]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "05dcb750-a258-4b39-b73c-2944477df645",
            "sourceColumn": "v_dim_calendar[quarter]",
            "summarizeBy": "sum",
            "type": "calculatedTableColumn"
          },
          {
            "name": "month_eng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "b2b07de7-3cda-4274-97ed-0f91ce4cb75a",
            "sourceColumn": "v_dim_calendar[month_eng]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "yyyy_mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2412c875-f22d-4079-a6c4-527912fa7cdf",
            "sourceColumn": "v_dim_calendar[yyyy_mm]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "weekend_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "7af7a53a-43aa-4572-a904-987b60bc223c",
            "sourceColumn": "v_dim_calendar[weekend_yn]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "MON_ENG_SHORT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "090ecfa1-724e-445c-9ed8-6ddd22d557e7",
            "sourceColumn": "v_dim_calendar[MON_ENG_SHORT]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "YYMM_EN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "isDataTypeInferred": true,
            "isNameInferred": true,
            "lineageTag": "2fb7dea4-59de-420a-a31d-86642939821f",
            "sortByColumn": "yyyy_mm",
            "sourceColumn": "v_dim_calendar[YYMM_EN]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          }
        ],
        "lineageTag": "3418c776-e986-4a67-95e1-93b41152d315",
        "partitions": [
          {
            "name": "previous_date",
            "mode": "import",
            "source": {
              "expression": "v_dim_calendar",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "dms_co_brand",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0b05eb0-505e-4ea8-8521-b00c47eca4e7",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dms_brand_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dcbaaabf-b997-4f6a-9887-d12b6e6e3394",
            "sourceColumn": "dms_brand_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "05fd7d55-1dba-4313-a982-69247a850ec3",
        "partitions": [
          {
            "name": "dms_co_brand",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_brand_Table = dev_twice_Schema{[Name=\"dms_co_brand\",Kind=\"Table\"]}[Data]",
                "in",
                "    dms_co_brand_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_co_code",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04bdf5e6-6110-442e-b606-5bd3edb6bda4",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "86e0c8a7-d669-4028-9adc-f7c3da796661",
            "sourceColumn": "code_type",
            "summarizeBy": "none"
          },
          {
            "name": "code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "36e8505f-629c-474c-a7ba-52eaaaf4ca63",
            "sourceColumn": "code",
            "summarizeBy": "none"
          },
          {
            "name": "code_type_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2db5d45f-e374-4303-847f-d115f2ef0b9f",
            "sourceColumn": "code_type_nm",
            "summarizeBy": "none"
          },
          {
            "name": "code_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "18b61f52-65f9-4c4f-b9d1-6c70fe24834f",
            "sourceColumn": "code_nm",
            "summarizeBy": "none"
          },
          {
            "name": "use_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c8bf208a-90be-47f1-ad31-95550f69ad97",
            "sourceColumn": "use_yn",
            "summarizeBy": "none"
          },
          {
            "name": "attr1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "faa7ec54-091c-43e1-bdd3-44db6c0ec11f",
            "sourceColumn": "attr1",
            "summarizeBy": "none"
          },
          {
            "name": "attr2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "679d178f-e4c2-43bd-b9f1-71a2b908a146",
            "sourceColumn": "attr2",
            "summarizeBy": "none"
          },
          {
            "name": "attr3",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e12d96a4-7593-4e08-b428-6ceceeff7a54",
            "sourceColumn": "attr3",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "50610997-722f-4d1e-bbaf-ee80b7bac794",
        "partitions": [
          {
            "name": "dms_co_code",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_code_Table = dev_twice_Schema{[Name=\"dms_co_code\",Kind=\"Table\"]}[Data]",
                "in",
                "    dms_co_code_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_co_vehic",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e88a72b-d5e3-4eca-8fd9-18e8ff4ce4c2",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67e0d839-3f61-4962-b352-047acbad5f5c",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a9fb6b7-8c3e-4e7e-8927-f2ad6790db89",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_no1",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac43afb4-1343-41dd-bbcb-c302df5e0bdf",
            "sourceColumn": "vehic_no1",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_no2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "af486c4d-8d99-4a27-8d6f-5a6b1d226e54",
            "sourceColumn": "vehic_no2",
            "summarizeBy": "none"
          },
          {
            "name": "model_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c4e5c095-e4c9-463e-b8aa-0ca8de9d687d",
            "sourceColumn": "model_year",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d7b03019-c6b1-428d-b5c1-33435ba7d308",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b02e60-3c34-4242-9f61-fabf3fa3bb0a",
            "sourceColumn": "variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "sfx_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd7189aa-b4aa-414a-b9c2-eb6555cc862f",
            "sourceColumn": "sfx_cd",
            "summarizeBy": "none"
          },
          {
            "name": "col_combi_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef8297c1-a732-40f7-9081-5c7390449a77",
            "sourceColumn": "col_combi_cd",
            "summarizeBy": "none"
          },
          {
            "name": "force_reg_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b7fd5e68-55dd-48db-815c-59d5acf4958c",
            "sourceColumn": "force_reg_yn",
            "summarizeBy": "none"
          },
          {
            "name": "sales_dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1505423e-39e2-46ce-8eb6-f2d8e834f863",
            "sourceColumn": "sales_dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "sales_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e328ecc5-0cfb-4217-859c-9291f8dcb440",
            "sourceColumn": "sales_type",
            "summarizeBy": "none"
          },
          {
            "name": "regist_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c40405f8-3887-4f60-8ce7-25ebf2132b6c",
            "sourceColumn": "regist_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_ee3385bf-1cae-4dfa-bd65-d63cb8fba3b8"
                },
                "isDefault": true,
                "relationship": "e3e90591-3d75-4683-b071-d01a876768ea"
              }
            ]
          },
          {
            "name": "lineoff_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "eaff0c35-a078-4224-87fa-a652dd498faa",
            "sourceColumn": "lineoff_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_17b78f12-9094-407e-b503-34fac1d122a6"
                },
                "isDefault": true,
                "relationship": "4674d163-68f7-4446-9a38-9fa88f43fcca"
              }
            ]
          },
          {
            "name": "delivery_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7d16c7c0-f6ad-44d5-a9a1-837b0ee3b95e",
            "sourceColumn": "delivery_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_08351f4d-4d3c-4b9c-8dcb-1f9b7cf93194"
                },
                "isDefault": true,
                "relationship": "dc6a4502-bd1d-461c-9baa-ec8e20992e61"
              }
            ]
          },
          {
            "name": "vehic_magic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "700a094c-9251-4cc8-bebb-e2fbccf342f7",
            "sourceColumn": "vehic_magic",
            "summarizeBy": "sum"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c538237-bd57-49e1-9a11-faf645b5bdd2",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "port_in_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3b9f5e6c-2b4d-486f-9c50-e271d27dffb1",
            "sourceColumn": "port_in_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_29db8caa-5b03-4937-bd1d-bbb566a4b65a"
                },
                "isDefault": true,
                "relationship": "ce9b2582-754e-421e-aa02-3ae35ef90e26"
              }
            ]
          },
          {
            "name": "retailsales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "94040ac7-2b7d-4582-a981-e4cc88f4a9da",
            "sourceColumn": "retailsales_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_97123f9e-5cf6-41c7-b2ae-230ca5003e1b"
                },
                "isDefault": true,
                "relationship": "768ec85d-f11e-4f84-b69f-45e5a14d6c6c"
              }
            ]
          },
          {
            "name": "stock_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58e23b6c-b145-4931-9727-965b22c6179c",
            "sourceColumn": "stock_status",
            "summarizeBy": "none"
          },
          {
            "name": "al_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25c8cdd5-a013-4c03-9d53-0f1af3279750",
            "sourceColumn": "al_status",
            "summarizeBy": "none"
          },
          {
            "name": "wholesales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8fe980bc-c02e-434e-a5fd-37a3bd1fbc7d",
            "sourceColumn": "wholesales_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_9e8cebc1-50a2-4b3a-87c6-6c57886cc384"
                },
                "isDefault": true,
                "relationship": "d1615a2b-fe3b-4cce-9d84-e64119646296"
              }
            ]
          },
          {
            "name": "progress_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d80643f-af9c-432f-a28c-0cf09decfd76",
            "sourceColumn": "progress_cd",
            "summarizeBy": "none"
          },
          {
            "name": "loss_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "dcdc372e-dbfc-4f6f-bb5a-1a3b76d9f149",
            "sourceColumn": "loss_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_71db58b9-f4da-4303-866b-8e5fd6e08d3d"
                },
                "isDefault": true,
                "relationship": "9e249483-7073-489e-8d8c-df93f9f711ed"
              }
            ]
          },
          {
            "name": "internal_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b9e5489e-1402-4d5d-b05c-59f1ac84c2cb",
            "sourceColumn": "internal_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_97ae6b8d-eaa0-455f-b998-e8b739b50e9a"
                },
                "isDefault": true,
                "relationship": "c6c4ae06-b881-496c-8bab-ec96fa029eb1"
              }
            ]
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dbcc32a-943d-4a2a-bb75-33994f2a4983",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9db8c9c-1615-4e66-9639-e4e3b5dd9b9d",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8dfc79d-0c7b-47ce-bf03-6c3e70ff0ddb",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "915c3e2c-7a83-4c72-aba9-0af308935f5d",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_01",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b4665fba-ba68-47d7-9309-1a9972033a83",
            "sourceColumn": "eom_detail_st_01",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_01",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "418efcc2-c5de-4a54-9d09-95da7a93f6ba",
            "sourceColumn": "eom_detail_end_01",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_02",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dc52f89-9d98-42dc-947c-add6719bb16d",
            "sourceColumn": "eom_detail_st_02",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_02",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a3d6a876-8ff8-4e4c-95de-1120eef159ba",
            "sourceColumn": "eom_detail_end_02",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_03",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1824576f-c023-42e8-9463-922f2d8d9bd0",
            "sourceColumn": "eom_detail_st_03",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_03",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b737f82e-8d4a-4dc3-890c-221f5db63f10",
            "sourceColumn": "eom_detail_end_03",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_04",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89be4007-84ca-414a-a341-3bb046597a63",
            "sourceColumn": "eom_detail_st_04",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_04",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0a66e3c9-95d6-4271-9ccf-28e4720be471",
            "sourceColumn": "eom_detail_end_04",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_05",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dfcafb7e-004d-48e4-8c9f-d7f68170644f",
            "sourceColumn": "eom_detail_st_05",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_05",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "76204dd2-a319-4b72-af49-f8c848973895",
            "sourceColumn": "eom_detail_end_05",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_06",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "766997d3-a342-49b5-ae67-b706d1e474a1",
            "sourceColumn": "eom_detail_st_06",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_06",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5ff1a265-eac0-449a-a93c-25c44b8d7c8a",
            "sourceColumn": "eom_detail_end_06",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_07",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc66c22c-583b-4694-88b7-3c9b856e6555",
            "sourceColumn": "eom_detail_st_07",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_07",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89cfd7fb-113a-469f-8794-4211b949c001",
            "sourceColumn": "eom_detail_end_07",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_08",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a65c1329-317a-4665-b5c9-e475ea2f1646",
            "sourceColumn": "eom_detail_st_08",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_08",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "21faa174-5917-4fa8-8bce-b0b3fbd3090e",
            "sourceColumn": "eom_detail_end_08",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_09",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7c0c18a7-a6cf-444f-9e90-f3ece49f6c37",
            "sourceColumn": "eom_detail_st_09",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_09",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c873b604-a373-494e-b42c-ad4f229eb4e7",
            "sourceColumn": "eom_detail_end_09",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e2a5e45-9cc1-420c-9e21-37b78b264b7b",
            "sourceColumn": "eom_detail_st_10",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_10",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8dd3b91-cb18-41c4-8bc6-352953e23fe8",
            "sourceColumn": "eom_detail_end_10",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b1ecdd35-086f-499d-a103-4090387a3cdd",
            "sourceColumn": "eom_detail_st_11",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_11",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1928311-5a4d-4a9c-b9b2-3a53dd19b31c",
            "sourceColumn": "eom_detail_end_11",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d24981d-9424-4c8c-aa68-9b4301ddce6f",
            "sourceColumn": "eom_detail_st_12",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_12",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "238a18bb-7582-4180-b0ca-be926ea0cf32",
            "sourceColumn": "eom_detail_end_12",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae69d886-4cd5-4cb1-96eb-f3973b613803",
            "sourceColumn": "eom_detail_st_13",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_13",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7098522f-edf8-477f-8df8-da0c66c66fd8",
            "sourceColumn": "eom_detail_end_13",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b24ae9f3-fc0b-47eb-9f5e-1a084a9b61f6",
            "sourceColumn": "eom_detail_st_14",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_14",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "25c9cd28-1eee-44e1-af80-ad85cdc71ee2",
            "sourceColumn": "eom_detail_end_14",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "751a39de-be19-4fb3-a187-ae021d650a72",
            "sourceColumn": "eom_detail_st_15",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_15",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec4903a3-5eee-498f-881d-6993c0a92c31",
            "sourceColumn": "eom_detail_end_15",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_st_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c37fd40-e15c-49e0-8b20-b00ad49d53d0",
            "sourceColumn": "eom_detail_st_16",
            "summarizeBy": "none"
          },
          {
            "name": "eom_detail_end_16",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd6afb55-074c-4855-8886-0f406295e3dd",
            "sourceColumn": "eom_detail_end_16",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1ae44cae-016c-4858-8720-05bee73e89c0",
        "partitions": [
          {
            "name": "dms_co_vehic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_vehic_Table = dev_twice_Schema{[Name=\"dms_co_vehic\",Kind=\"Table\"]}[Data]",
                "in",
                "    dms_co_vehic_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_ee3385bf-1cae-4dfa-bd65-d63cb8fba3b8",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "1164ffb4-a0a2-4259-a14f-4f5a6f514c67",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "5f668202-970d-4aa3-9145-83cad43ba8cc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "e35fa96c-ff7f-4e2f-9b36-f94059e98258",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "37a16b0a-60c6-4263-824f-05fab1a8df99",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a807bf32-6c29-43aa-8fe7-fe653f9d2e8f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "376af6c5-f0ce-4910-afc5-92e269dc1168",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "65b78ee3-f4fc-424e-a9ef-0e494f138a16",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "27a0f79a-295f-4178-8f92-76e0138e5697",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "c1303c18-c901-4cb0-8cf6-51838b3cf406",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b4430e29-157f-4763-bafb-b0733b0f61b9",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "fb3c3196-3934-49ea-ac75-89a5c5558140",
                "ordinal": 3
              }
            ],
            "lineageTag": "1d38b40c-d5ff-4728-bfbe-20f685910e2e"
          }
        ],
        "isHidden": true,
        "lineageTag": "1593e3dc-40ff-423f-9d9a-c5cce23ddb81",
        "partitions": [
          {
            "name": "LocalDateTable_ee3385bf-1cae-4dfa-bd65-d63cb8fba3b8",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[regist_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[regist_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_17b78f12-9094-407e-b503-34fac1d122a6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "23577c79-fcc3-4889-a194-bc6396cc761c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3cc781ed-8671-4361-8be2-40294ba6661a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "32619a8e-1b5a-4e08-981e-5c95576cefd8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6723cea1-6426-4768-ab5c-ffb29464faad",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "96ac6f35-2695-4e37-adec-0ad52c8a54da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "450653b2-95a1-4e81-bcd5-7f76c5ddfe58",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "47737213-4c4e-46b4-8826-48147e3d43ea",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "32b6bf86-05db-4c79-a2d1-29f1359307bc",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "a100868f-4c69-48a7-8bd9-8b8c1c2e37d1",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9257ad31-d93b-4a32-8373-a18d6c6f527a",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "459be04c-0ef2-4b7c-9235-6f1176e0d863",
                "ordinal": 3
              }
            ],
            "lineageTag": "346e7d3b-b397-4119-b49f-01916d546632"
          }
        ],
        "isHidden": true,
        "lineageTag": "ed3bb681-7d2c-409f-99ef-4fa660ae69a6",
        "partitions": [
          {
            "name": "LocalDateTable_17b78f12-9094-407e-b503-34fac1d122a6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[lineoff_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[lineoff_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_08351f4d-4d3c-4b9c-8dcb-1f9b7cf93194",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "156034a8-0d48-406b-88b0-67895389d93e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "78c23dca-9367-40ab-99db-a07d8a5d544f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a9c50056-b383-443a-b113-91d925d53350",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c510c922-57ec-4e8d-a72a-199bb4941874",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5db09777-dc7d-477a-acf4-6301ab8a02af",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "00ef1c63-a82d-4de4-89f7-77be01c5444f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d9b564e3-f588-41d6-af86-05f5fecbcc6d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "5df52125-4300-452f-a543-a0769b5d84a3",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "ea6580ec-81a8-40fb-9e2f-31b6fc1e4f7a",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "04bb0493-6484-4473-a76e-51f1b31d09be",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "c7ade4d8-1196-4c8a-a0c6-eed900f3d518",
                "ordinal": 3
              }
            ],
            "lineageTag": "0cc1e09b-16b4-4686-b428-6b4d4f736151"
          }
        ],
        "isHidden": true,
        "lineageTag": "1cf2eac3-e6f3-43c5-8c08-649c16d2e5d5",
        "partitions": [
          {
            "name": "LocalDateTable_08351f4d-4d3c-4b9c-8dcb-1f9b7cf93194",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[delivery_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[delivery_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_sales_contract",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6c82cfd-c03e-41c3-803a-98a5a3214b50",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "524f9bf2-ce7a-4ca1-aa25-3f00aa74b79f",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "contract_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "e2219aa1-39e9-40fd-b03d-7def847b461c",
            "sourceColumn": "contract_no",
            "summarizeBy": "sum"
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "496d43b6-074a-4f52-989e-4be82d0ab688",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "contract_stat_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5f63bac1-2e33-4778-b05a-6aeee97f2866",
            "sourceColumn": "contract_stat_cd",
            "summarizeBy": "none"
          },
          {
            "name": "contract_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "85b2fae4-3f12-43ca-a68e-6b898b61c9d7",
            "sourceColumn": "contract_reg_dt",
            "summarizeBy": "none"
          },
          {
            "name": "retail_sales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f6cc607f-ea2e-4abb-9d69-211baf243c1b",
            "sourceColumn": "retail_sales_dt",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3d1510e8-6297-44ee-8e4e-43cb09813a70",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "cancel_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "2c811c9f-38ad-4ace-bbca-5396525559ff",
            "sourceColumn": "cancel_dt",
            "summarizeBy": "none"
          },
          {
            "name": "sales_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1cb5cb6a-b0e6-4fe6-a7d1-957ddd719264",
            "sourceColumn": "sales_type",
            "summarizeBy": "none"
          },
          {
            "name": "consign_sales_flag",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5b96102-1829-4d7e-a251-e372ba0ad8fe",
            "sourceColumn": "consign_sales_flag",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f1e255ee-6d58-4cc5-84d2-d6c056de8ad8",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ba910b9c-b5df-43f8-bd7f-60c4b3400f40",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fba510cf-d9f0-45f6-97df-7b249734ceb0",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "my_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30195377-8510-4592-9cba-3e15293adc38",
            "sourceColumn": "my_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sfx_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eec91846-22db-42f6-83ed-7fdba23208f0",
            "sourceColumn": "sfx_cd",
            "summarizeBy": "none"
          },
          {
            "name": "col_combi_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b504fabb-4ea6-48d4-91e6-ce47a24a189e",
            "sourceColumn": "col_combi_cd",
            "summarizeBy": "none"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f59c2897-dcad-41ae-9f93-d38ce30db286",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbcf8d22-0896-403e-8429-b6ac864b23ce",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e28f784-ecc6-4b66-86fd-1d869f667c5c",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "887b8183-64b5-4868-bec3-26c0c13af04b",
        "measures": [
          {
            "name": "#__Trend_Contract_Blank_Filter",
            "displayFolder": "_Contract",
            "expression": "IF([#_Contract_LM]=0&&[#_Contract_3M/AVG]=0&&[#_Contract_6M/AVG]=0&&[#_Contract_LY]=0&&[#_Contract_CurrentPace_MTD]=0,0,1)",
            "formatString": "0",
            "lineageTag": "10ec813a-db95-4054-a743-f14fa52a81c7"
          },
          {
            "name": "#_Contract_3M/AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "",
              "VAR _1M = ",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,MONTH))",
              "",
              "VAR _2M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-2,MONTH))",
              "",
              "VAR _3M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-3,MONTH))",
              "",
              "RETURN ",
              "DIVIDE((_1M + _2M + _3M), 3, 0)"
            ],
            "formatString": "#,0",
            "lineageTag": "75a6b9d5-1db5-4a43-b1c0-0294f2369b4a"
          },
          {
            "name": "#_Contract_3M/AVG_Ratio(%)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_CurrentPace_MTD], [#_Contract_3M/AVG], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "74350f76-85cb-46b1-891a-5ead90a60dad"
          },
          {
            "name": "#_Contract_6M/AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "",
              "VAR _1M = ",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,MONTH))",
              "",
              "VAR _2M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-2,MONTH))",
              "",
              "VAR _3M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-3,MONTH))",
              "",
              "VAR _4M = ",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-4,MONTH))",
              "",
              "VAR _5M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-5,MONTH))",
              "",
              "VAR _6M =",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-6,MONTH))",
              "",
              "RETURN ",
              "DIVIDE((_1M + _2M + _3M + _4M + _5M + _6M), 6, 0)"
            ],
            "formatString": "#,0",
            "lineageTag": "beb63854-4974-4753-8d02-c91c0b0d0135"
          },
          {
            "name": "#_Contract_6M/AVG_Ratio(%)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_CurrentPace_MTD], [#_Contract_6M/AVG], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "9cd1533f-be2d-4692-b2d7-ccf2c0542223"
          },
          {
            "name": "#_Contract_CurrentPace",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE(COUNTROWS('dms_sales_contract'))"
            ],
            "formatString": "#,0",
            "lineageTag": "2f0fec99-169e-4466-8d7f-f46814fb964b"
          },
          {
            "name": "#_Contract_CurrentPace_MTD",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "VAR Result = CALCULATE([#_Contract_CurrentPace], DATESMTD(v_dim_calendar[date]))",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "c7a30ed8-971b-4878-a7a1-53aa17917bc5"
          },
          {
            "name": "#_Contract_CurrentPace(M)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(COUNTROWS('dms_sales_contract')",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate))",
              "         ",
              "RETURN",
              "        IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "5dcb8206-2a32-4653-b9d2-c01befc27e39"
          },
          {
            "name": "#_Contract_Forecast(31th)_MTD",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "var _1th = DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1) -- first day",
              "var _eomon = EOMONTH(_1th, 0) -- last day",
              "var _today = SELECTEDVALUE(v_dim_calendar[date]) -- selected day",
              "",
              "var _month_value = CALCULATE(",
              "                                    sum(v_sales_contract_forecast[sa_kpi_code_amt])",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"CONTRACT\"",
              "                                   ,v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _eomon",
              "                                )",
              "",
              "var _ratio_value = CALCULATE(",
              "                                    sum(v_sales_contract_forecast[co_kpi_code_amt])",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"CONTRACT\"",
              "                                    , v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _today",
              "                                ) ",
              "",
              "var _Result = DIVIDE(DIVIDE(_month_value * _ratio_value,[#_group_id_num_contract],0),100,0)",
              "RETURN",
              "IF(ISBLANK(_Result),0,_Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "5183b17f-dd9f-4c33-a07c-40540e918788"
          },
          {
            "name": "#_Contract_LM",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "557770cf-31e7-4ed1-802b-772fbe2fd723"
          },
          {
            "name": "#_Contract_LM_Ratio(%)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_CurrentPace_MTD], [#_Contract_LM], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "5fda6250-b8af-454b-bc28-732a5521be09"
          },
          {
            "name": "#_Contract_LY",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE(",
              "    [#_Contract_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,YEAR))"
            ],
            "formatString": "#,0",
            "lineageTag": "14a3775b-79dc-426e-8c4c-7bd25c3b8643"
          },
          {
            "name": "#_Contract_LY_Ratio(%)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_CurrentPace_MTD], [#_Contract_LY], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "9cdd9e64-d877-44a9-8923-0e0f45fe2ae7"
          },
          {
            "name": "#_Trend_Sales_Blank_Filter",
            "displayFolder": "_Sales",
            "expression": "IF([#_Sales_LM]=0&&[#_Sales_3M/AVG]=0&&[#_Sales_6M/AVG]=0&&[#_Sales_LY]=0&&[#_Sales_CurrentPace_MTD]=0,0,1)",
            "formatString": "#,0",
            "lineageTag": "b138b321-de18-4841-b146-2729e3d456dd"
          },
          {
            "name": "#_Sales_3M/AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "",
              "VAR _1M = ",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "VAR _2M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date], -2, MONTH))",
              "",
              "VAR _3M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-3, MONTH))",
              "",
              "RETURN ",
              "DIVIDE((_1M + _2M + _3M), 3, 0)"
            ],
            "formatString": "#,0",
            "lineageTag": "e4b82b07-e948-4fb2-be55-3ffd8b1164a7"
          },
          {
            "name": "#_Sales_3M/AVG_Ratio(%)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_CurrentPace_MTD], [#_Sales_3M/AVG], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "6774d4d8-f9d3-4a47-932a-80b5f89a8f9a"
          },
          {
            "name": "#_Sales_6M/AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "",
              "VAR _1M = ",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date], -1 ,MONTH))",
              "",
              "VAR _2M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-2,MONTH))",
              "",
              "VAR _3M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-3,MONTH))",
              "",
              "VAR _4M = ",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-4,MONTH))",
              "",
              "VAR _5M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-5,MONTH))",
              "",
              "VAR _6M =",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-6,MONTH))",
              "",
              "RETURN ",
              "DIVIDE((_1M + _2M + _3M + _4M + _5M + _6M), 6, 0)"
            ],
            "formatString": "#,0",
            "lineageTag": "04b0fa6e-4fa6-4e41-8724-7dfd59f8caea"
          },
          {
            "name": "#_Sales_6M/AVG_Ratio(%)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_CurrentPace_MTD], [#_Sales_6M/AVG], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "8d1f87b8-4734-433b-8f35-62df04fe876b"
          },
          {
            "name": "#_Sales_CurrentPace",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS('dms_sales_contract')",
              "            , USERELATIONSHIP(v_dim_calendar[date], dms_sales_contract[retail_sales_dt]))",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "c801cea7-7ef8-4043-8378-05054707335e"
          },
          {
            "name": "#_Sales_CurrentPace_MTD",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "",
              "VAR _Result =",
              "CALCULATE([#_Sales_CurrentPace], DATESMTD(v_dim_calendar[date]))",
              "",
              "RETURN",
              "    IF(ISBLANK(_Result),0,_Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "8c224b3c-c06c-4292-830b-71d0bb8197a8"
          },
          {
            "name": "#_Sales_Forecast(31th)_MTD",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "var _1th = DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1) -- first day",
              "var _eomon = EOMONTH(_1th, 0) -- last day",
              "var _today = SELECTEDVALUE(v_dim_calendar[date]) -- selected day",
              "",
              "var _month_value = CALCULATE(",
              "                                    sum(v_sales_contract_forecast[sa_kpi_code_amt])",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"RETAIL_SALES\"",
              "                                   ,v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _eomon",
              "                                )",
              "",
              "var _ratio_value = CALCULATE(",
              "                                    sum(v_sales_contract_forecast[co_kpi_code_amt])",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"RETAIL_SALES\"",
              "                                    , v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _today",
              "                                ) ",
              "var _Result = DIVIDE(DIVIDE(_month_value * _ratio_value,[#_group_id_num_sales],0),100,0)",
              "",
              "RETURN",
              "IF(ISBLANK(_Result),0,_Result)",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "6ac75d9e-bc22-41ae-86d1-8de2f9783d54"
          },
          {
            "name": "#_Sales_LM",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "a5930162-8c53-4b7a-b174-bc8def3bc5a3"
          },
          {
            "name": "#_Sales_LM_Ratio(%)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_CurrentPace_MTD], [#_Sales_LM], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "78eff9a1-49e1-479f-9b1f-3a873ccf0509"
          },
          {
            "name": "#_Sales_LY",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "CALCULATE(",
              "    [#_Sales_CurrentPace_MTD]",
              "    ,DATEADD(v_dim_calendar[date],-1,YEAR))"
            ],
            "formatString": "#,0",
            "lineageTag": "bba0d106-7699-4724-afc9-896ee9b270b7"
          },
          {
            "name": "#_Sales_LY_Ratio(%)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_CurrentPace_MTD], [#_Sales_LY], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "4612c870-a2a4-4a26-a030-02c8093ce1db"
          },
          {
            "name": "#_Sales_Target_Ratio(CP/D)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_CurrentPace_MTD], [#_Sales_Target(D)_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "f3435717-9e80-4a57-b2a5-a4df8bb7a802"
          },
          {
            "name": "#_Sales_Target_Ratio(D/M)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_Target(D)_MTD], [#_Sales_Target(M)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "7ecc2378-4bee-4c83-ab06-6a5bdb5aae4b"
          },
          {
            "name": "#_Sales_Target(D)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , dms_sales_kpi_resource_day[sa_kpi_code_type] = \"DMS_BI_SA003\"",
              "    , dms_sales_kpi_resource_day[sa_kpi_code] = \"RETAIL_SALES\")"
            ],
            "formatString": "#,0",
            "lineageTag": "1822a3d2-2549-4e74-a6db-00d2656c3c2e"
          },
          {
            "name": "#_Sales_Target(D)_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "VAR Result = CALCULATE([#_Sales_Target(D)], DATESMTD(v_dim_calendar[date]))",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "4900d429-e3af-42fd-adc4-b065df7a9cfa"
          },
          {
            "name": "#_Sales_Target(F/M)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_Forecast(31th)_MTD], [#_Sales_Target(M)], 0 )"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "9f5828b8-cabd-4b3c-bac1-4c4d497f69f9"
          },
          {
            "name": "#_Sales_Target(M)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , 'dms_sales_kpi_resource_day'[sa_kpi_code_type] = \"DMS_BI_SA003\"",
              "    && 'dms_sales_kpi_resource_day'[sa_kpi_code] = \"RETAIL_SALES\"",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate))",
              "         ",
              "RETURN",
              "    IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "c2414002-fdfa-435f-960d-8a964b3d97ee"
          },
          {
            "name": "#_Sales_CurrentPace(M)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(COUNTROWS('dms_sales_contract')",
              "    , USERELATIONSHIP(v_dim_calendar[date], dms_sales_contract[retail_sales_dt])",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate))",
              "         ",
              "RETURN",
              "        IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "0c9bbe9b-2878-4a1c-b2b1-f102a53f8245"
          },
          {
            "name": "#_Sales_MTD(N-1)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -1, MONTH))",
              "     ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "539dbead-d972-4d69-8e91-e66d6b358ab2"
          },
          {
            "name": "#_Sales_MTD(N-2)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -2, MONTH))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "7ca8d8bc-8bb5-4cd7-8a8f-731878319185"
          },
          {
            "name": "#_Sales_MTD(N-3)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 12, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE), DAY(L_DATE))",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -3, MONTH))",
              "           ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "871953f7-8d37-4f41-af6e-94bbacbb3383"
          },
          {
            "name": "#_Sales_Seasonal_Ratio(AVG)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Sales_Seasonal_Result(AVG)], [#_Sales_Seasonal_Target(AVG)], 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a634dc22-1473-4e05-bf97-b758432f9bb5"
          },
          {
            "name": "#_Sales_Seasonal_Ratio(N-1)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Sales_Seasonal_Result(N-1)], [#_Sales_Seasonal_Target(N-1)], 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "d56ff000-5497-4f48-82ac-44bd8597758b"
          },
          {
            "name": "#_Sales_Seasonal_Ratio(N-2)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Sales_Seasonal_Result(N-2)], [#_Sales_Seasonal_Target(N-2)], 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "67feb9dd-b5e3-4936-8794-002f91dbed07"
          },
          {
            "name": "#_Sales_Seasonal_Result(AVG)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR _AVG = ",
              "([#_Sales_Seasonal_Result(N-1)] + [#_Sales_Seasonal_Result(N-2)] + [#_Sales_Seasonal_Result(N-3)])/3",
              "",
              "VAR _Result =",
              "ROUND(_AVG, -1)",
              "",
              "RETURN ",
              "    _Result"
            ],
            "formatString": "0",
            "lineageTag": "2e0996b8-e382-4d4d-8aed-e0e8da7554c8"
          },
          {
            "name": "#_Sales_Seasonal_Ratio(N-3)",
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Sales_Seasonal_Result(N-3)], [#_Sales_Seasonal_Target(N-3)], 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8ae15eb4-a0fe-4160-b255-d28e1868c154"
          },
          {
            "name": "#_Sales_Seasonal_Result(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_MTD(N-1)],[#_Seasonal_Index(N-1)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "1cb832ec-a743-45b6-8bab-1fec7411ab97"
          },
          {
            "name": "#_Contract_Forecast_Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "var num = [#_Contract_Forecast(31th)_MTD] - [#_Contract_Target(M)]",
              "RETURN",
              "IF(num > 0, \"+\"&FORMAT(num, \"#\"), num)"
            ],
            "formatString": "#,0",
            "lineageTag": "c50ea747-9453-41c6-afcc-f913f70b6855"
          },
          {
            "name": "#_Contract_Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "var num = [#_Contract_CurrentPace_MTD] - [#_Contract_Target(D)_MTD]",
              "RETURN",
              "IF(num > 0, \"+\"&FORMAT(num, \"#\"), num)"
            ],
            "formatString": "#,0",
            "lineageTag": "f63a9e36-15d1-4d34-b217-c8c705ca8f06"
          },
          {
            "name": "#_Contract_Target_LM_Ratio(CP/D)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_LM], [#_Contract_Target(D)_LM], 0)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1245d3e5-adce-45b8-b46b-cc65a299fb68"
          },
          {
            "name": "#_Contract_Target_LY_Ratio(CP/D)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_LY], [#_Contract_Target(D)_LY], 0)"
            ],
            "formatString": "#,0.00",
            "lineageTag": "1f3f80f6-2bd2-498a-8516-a83da00aa7e7"
          },
          {
            "name": "#_Contract_Target_Ratio(CP/D)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_CurrentPace_MTD], [#_Contract_Target(D)_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "11f1f7ef-9e5b-44c7-9df7-6cfbea1bc3fe"
          },
          {
            "name": "#_Contract_Target_Ratio(CP/D)_Gap(M)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "",
              "var num = ROUND(([#_Contract_Target_Ratio(CP/D)] - [#_Contract_Target_LM_Ratio(CP/D)])*100,0)",
              "RETURN IF(num > 0, \"+\"&num&\"%\", num&\"%\")"
            ],
            "lineageTag": "d036b881-aafb-40db-b5b3-1470ec4a5a0a"
          },
          {
            "name": "#_Contract_Target_Ratio(CP/D)_Gap(Y)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "",
              "var num = ROUND(([#_Contract_Target_Ratio(CP/D)] - [#_Contract_Target_LY_Ratio(CP/D)])*100,0)",
              "RETURN IF(num > 0, \"+\"&num&\"%\", num&\"%\")"
            ],
            "lineageTag": "039dab28-8baf-461d-adde-7e221b97d67b"
          },
          {
            "name": "#_Contract_Target_Ratio(D/M)",
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_Target(D)_MTD], [#_Contract_Target(M)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "0ba72ae3-fda7-4d3d-b2c9-d972c02553f8"
          },
          {
            "name": "#_Contract_Target(D)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , dms_sales_kpi_resource_day[sa_kpi_code_type] = \"DMS_BI_SA003\"",
              "    , dms_sales_kpi_resource_day[sa_kpi_code] = \"CONTRACT\")"
            ],
            "formatString": "#,0",
            "lineageTag": "631bf684-1243-4a0e-816b-f85361d74ee9"
          },
          {
            "name": "#_Contract_Target(D)_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE([#_Contract_Target(D)_MTD], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "ee7f1e03-c150-4f58-abcc-dc8de6ea91eb"
          },
          {
            "name": "#_Contract_Target(D)_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "CALCULATE([#_Contract_Target(D)_MTD], DATEADD(v_dim_calendar[date], -1, year))"
            ],
            "formatString": "#,0",
            "lineageTag": "e83b18e3-768e-46d4-97ad-7e836fe5fffb"
          },
          {
            "name": "#_Contract_Target(D)_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "VAR Result = CALCULATE([#_Contract_Target(D)], DATESMTD(v_dim_calendar[date]))",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "ed5c1fbe-a97b-4b1d-b3de-b02b28314736"
          },
          {
            "name": "#_Contract_Target(F/M)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "DIVIDE([#_Contract_Forecast(31th)_MTD], [#_Contract_Target(M)], 0 )"
            ],
            "formatString": "#,0",
            "lineageTag": "fc5d4df1-1a81-409b-98c6-88a3affcc4c0"
          },
          {
            "name": "#_Contract_Target(M)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , 'dms_sales_kpi_resource_day'[sa_kpi_code_type] = \"DMS_BI_SA003\"",
              "    && 'dms_sales_kpi_resource_day'[sa_kpi_code] = \"CONTRACT\"",
              "    , FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate",
              "    ))       ",
              "RETURN",
              "    IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "59e22c4c-52c8-4809-94b6-562ddfc63c8c"
          },
          {
            "name": "#_~6M BOC",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , ALLEXCEPT( 'dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[group_eng_name]",
              "    ,v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)]",
              "    ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] < EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "    , SELECTEDVALUE(v_dim_calendar[month]),1),-6)",
              "    , ISBLANK('dms_sales_contract'[retail_sales_dt])||'dms_sales_contract'[retail_sales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "    , SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              "    || 'dms_sales_contract'[contract_stat_cd] <> \"D4\"",
              "   , ISBLANK('dms_sales_contract'[cancel_dt]) || 'dms_sales_contract'[cancel_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "   , SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "c5f0b7cd-5b45-44d0-b674-8fc3d62a9a14"
          },
          {
            "name": "#_~6M Delivery",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              " ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , USERELATIONSHIP(v_dim_calendar[date], 'dms_sales_contract'[retail_sales_dt])",
              "    , 'dms_sales_contract'[contract_stat_cd] = \"D4\"",
              "    , NOT ISBLANK('dms_sales_contract'[retail_sales_dt])",
              "    , FILTER(",
              "        ALL('dms_sales_contract'[contract_reg_dt]),",
              "        'dms_sales_contract'[contract_reg_dt] < EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-6)",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "9594a1b8-a31b-4fae-9b09-86517557caa8"
          },
          {
            "name": "#_1~3M BOC",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract') ",
              "    , ALLEXCEPT( 'dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[group_eng_name]",
              "    ,v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)]",
              "     ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), -3)",
              "    , 'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), -1) -1",
              "    , ISBLANK('dms_sales_contract'[retail_sales_dt])||'dms_sales_contract'[retail_sales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), 0)",
              "    || 'dms_sales_contract'[contract_stat_cd] <> \"D4\"",
              "   , ISBLANK('dms_sales_contract'[cancel_dt]) || 'dms_sales_contract'[cancel_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "   , SELECTEDVALUE(v_dim_calendar[month]), 1), 0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "ab550966-28c4-44a9-8ae2-9e6f1f1bdc8e"
          },
          {
            "name": "#_1~3M Delivery",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , USERELATIONSHIP(v_dim_calendar[date], 'dms_sales_contract'[retail_sales_dt])",
              "    , 'dms_sales_contract'[contract_stat_cd] = \"D4\"",
              "    , NOT ISBLANK('dms_sales_contract'[retail_sales_dt])",
              "    , FILTER(",
              "        ALL('dms_sales_contract'[contract_reg_dt]),",
              "        'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-3) &&",
              "        'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1) -1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "6dabdd13-8fa8-45f2-b687-303ef9c0513b"
          },
          {
            "name": "#_1M BOC",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "VAR Result = ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , ALLEXCEPT( 'dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[group_eng_name]",
              "    ,v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)]",
              "     ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), -1)",
              "    , 'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), 0)",
              "    , ISBLANK('dms_sales_contract'[retail_sales_dt])||'dms_sales_contract'[retail_sales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), 0)",
              "    || 'dms_sales_contract'[contract_stat_cd] <> \"D4\"",
              "   , ISBLANK('dms_sales_contract'[cancel_dt]) || 'dms_sales_contract'[cancel_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "3da7ca03-d049-42c0-ba5b-dec37dde4633"
          },
          {
            "name": "#_1M Delivery",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              " ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , USERELATIONSHIP(v_dim_calendar[date], 'dms_sales_contract'[retail_sales_dt])",
              "    , 'dms_sales_contract'[contract_stat_cd] = \"D4\"",
              "    , NOT ISBLANK('dms_sales_contract'[retail_sales_dt])",
              "    , FILTER(",
              "        ALL('dms_sales_contract'[contract_reg_dt]),",
              "        'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)&&",
              "        'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "3b157c5d-8f31-4ddc-bb5a-35ce2219d1c7"
          },
          {
            "name": "#_4~6M BOC",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "VAR Result = ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , ALLEXCEPT( 'dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[group_eng_name]",
              "    ,v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)]",
              "     ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1), -6)",
              "    , 'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1), -3) -1",
              "    , ISBLANK('dms_sales_contract'[retail_sales_dt])||'dms_sales_contract'[retail_sales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              "    || 'dms_sales_contract'[contract_stat_cd] <> \"D4\"",
              "   , ISBLANK('dms_sales_contract'[cancel_dt]) || 'dms_sales_contract'[cancel_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1), 0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "28192e09-7aaa-4d9c-87cc-1bd6fb3f0bfc"
          },
          {
            "name": "#_4~6M Delivery",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , USERELATIONSHIP(v_dim_calendar[date], 'dms_sales_contract'[retail_sales_dt])",
              "    , 'dms_sales_contract'[contract_stat_cd] = \"D4\"",
              "    , NOT ISBLANK('dms_sales_contract'[retail_sales_dt])",
              "    , FILTER(",
              "        ALL('dms_sales_contract'[contract_reg_dt]),",
              "        'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-6) &&",
              "        'dms_sales_contract'[contract_reg_dt] <=EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-3)-1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "lineageTag": "0d6abd7b-5ed6-46f6-acbc-72b747942c8f"
          },
          {
            "name": "#_BOC_Delivery_Total",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "[#_1M Delivery] + [#_1~3M Delivery] + [#_4~6M Delivery] + [#_~6M Delivery]"
            ],
            "formatString": "#,0",
            "lineageTag": "a91c82ef-6b1e-4c57-b605-3dcc363547da"
          },
          {
            "name": "#_BOC_Total",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "",
              "[#_1M BOC] + [#_1~3M BOC] + [#_4~6M BOC] + [#_~6M BOC]"
            ],
            "formatString": "#,0",
            "lineageTag": "5b750133-7979-4e78-b8a1-855e11591dd6"
          },
          {
            "name": "#_Contract_MTD(N-1)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 12, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE), DAY(L_DATE))",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -1, MONTH))",
              "           ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "000aaefe-ee23-4da0-b6e1-94420f551817"
          },
          {
            "name": "#_Contract_MTD(N-2)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -2, MONTH))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "13192de5-1a3f-4257-a07a-2fd2a5bcfe6c"
          },
          {
            "name": "#_Contract_MTD(N-3)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_CurrentPace_MTD],DATEADD(v_dim_calendar[date], -3, MONTH))",
              "     ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "d8c2973d-b78e-47e3-af75-94f34bc43d6e"
          },
          {
            "name": "#_Contract_Seasonal_Ratio(AVG)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Contract_Seasonal_Result(AVG)], [#_Contract_Seasonal_Target(AVG)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "b3ddb3ae-f777-47fc-81c9-67e91c6d7399"
          },
          {
            "name": "#_Contract_Seasonal_Ratio(N-1)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Contract_Seasonal_Result(N-3)], [#_Contract_Seasonal_Target(N-3)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "36db943e-36a2-49cb-ad6c-3b014c4527dc"
          },
          {
            "name": "#_Contract_Seasonal_Ratio(N-2)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Contract_Seasonal_Result(N-2)], [#_Contract_Seasonal_Target(N-2)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "c68985f9-087f-4b02-8c1b-b55d0c4e9a63"
          },
          {
            "name": "#_Contract_Seasonal_Ratio(N-3)",
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "DIVIDE([#_Contract_Seasonal_Result(N-3)], [#_Contract_Seasonal_Target(N-3)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "11859fa8-9d2a-4c64-9a13-fdb87ff81609"
          },
          {
            "name": "#_Contract_Seasonal_Result(AVG)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR _AVG = ",
              "([#_Contract_Seasonal_Result(N-1)] + [#_Contract_Seasonal_Result(N-3)] + [#_Contract_Seasonal_Result(N-2)])/3",
              "",
              "VAR _Result =",
              "ROUND(_AVG, -1)",
              "",
              "RETURN ",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "dbf3fbde-e418-4f18-8202-73a203ca54c4"
          },
          {
            "name": "#_Contract_Seasonal_Result(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_MTD(N-1)],[#_Seasonal_Index(N-1)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "bf9b24bd-ede7-4efa-8af4-b5a8da3d35ad"
          },
          {
            "name": "#_Contract_Seasonal_Result(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_MTD(N-2)],[#_Seasonal_Index(N-2)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "0c659020-81cf-4c60-a145-eea048559f3b"
          },
          {
            "name": "#_Contract_Seasonal_Result(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_MTD(N-3)],[#_Seasonal_Index(N-3)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "1e096819-6df9-4240-9add-bc10aca01ab9"
          },
          {
            "name": "#_Contract_Seasonal_Target(AVG)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR _AVG = ([#_Contract_Seasonal_Target(N-1)] + [#_Contract_Seasonal_Target(N-2)] + [#_Contract_Seasonal_Target(N-3)])/3",
              "",
              "VAR _Result =",
              "ROUND(_AVG, -1)",
              "",
              "RETURN ",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "8718842c-6959-4240-a113-f377a2a73027"
          },
          {
            "name": "#_Contract_Seasonal_Target(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_Target(N-1)],[#_Seasonal_Index(N-1)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "ce69e0d2-c1dd-48f6-a5d5-3e170c042624"
          },
          {
            "name": "#_Contract_Seasonal_Target(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_Target(N-2)],[#_Seasonal_Index(N-2)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "90a7b71a-fbd5-4d93-8bac-980fb0105cf6"
          },
          {
            "name": "#_Contract_Target(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 13, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE), 1) -1  //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_Target(M)],DATEADD(v_dim_calendar[date], -1, MONTH))",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "ce3f355b-7a8f-4215-8fed-38cf4b2a5dcd"
          },
          {
            "name": "#_Contract_Seasonal_Target(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Contract_Target(N-3)],[#_Seasonal_Index(N-3)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "51526f7d-507c-4bca-a111-30152f251a99"
          },
          {
            "name": "#_Contract_Target(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_Target(M)],DATEADD(v_dim_calendar[date], -2, MONTH))",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "15a96e75-b11f-4c2c-99b7-7c33a1530787"
          },
          {
            "name": "#_Contract_Target(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Contract_Target(M)],DATEADD(v_dim_calendar[date], -3, MONTH))",
              "           ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "abd20bec-6b85-4f78-9286-6e33a6da6ebf"
          },
          {
            "name": "#_Seasonal_Index(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [#_Seasonal_Index(N)]",
              "    , DATEADD(v_dim_calendar[date], -1, MONTH ))"
            ],
            "formatString": "#,0",
            "lineageTag": "c5be089d-6aed-4648-8288-e5e3d3d3c257"
          },
          {
            "name": "#_Seasonal_Index(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [#_Seasonal_Index(N)]",
              "    , DATEADD(v_dim_calendar[date], -2, MONTH ))"
            ],
            "formatString": "#,0",
            "lineageTag": "b40bb572-6e03-4ea8-afd8-96061a5b86f7"
          },
          {
            "name": "#_Seasonal_Index(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    [#_Seasonal_Index(N)]",
              "    , DATEADD(v_dim_calendar[date], -3, MONTH ))"
            ],
            "formatString": "#,0",
            "lineageTag": "2afd3b15-89c7-4c5c-b27f-832db2ad2c71"
          },
          {
            "name": "#_Seasonal_Index(N)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Contract_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "    CALCULATE(",
              "        SUM(dms_sales_kpi_resource[sa_kpi_code_amt])",
              "    )",
              "",
              "VAR _B = ",
              "    CALCULATE(",
              "        COUNT(dms_sales_kpi_resource[sa_kpi_code_amt])",
              "    )",
              "",
              "VAR _Result =",
              "    DIVIDE(_A, _B, 0)",
              "",
              "RETURN",
              "_Result"
            ],
            "formatString": "#,0",
            "lineageTag": "34021326-21d0-48ad-aa12-ad6db15310b7"
          },
          {
            "name": "#_BOC(N-1)_Net Contract(N)_Ratio(Plan)",
            "displayFolder": "_Other KPIs_a",
            "expression": "DIVIDE([#_N-1 BOC]+[#_N Net Contract],[#_N Sales_Plan],0)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "54e264d9-6a04-4549-a2e1-5b1bc5de3103"
          },
          {
            "name": "#_BOC(N-1)_Ratio(Cancel)",
            "displayFolder": "_Other KPIs_a",
            "expression": "DIVIDE([#_N-1 BOC],[#_N Cancellation])",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "fb83a9ec-525c-47eb-afc1-53980114869d"
          },
          {
            "name": "#_N Cancellation",
            "displayFolder": "_Other KPIs_a",
            "expression": [
              "",
              "CALCULATE(COUNTROWS('dms_sales_contract')",
              ", USERELATIONSHIP(v_dim_calendar[date], 'dms_sales_contract'[cancel_dt]))"
            ],
            "formatString": "#,0",
            "lineageTag": "446b534b-a60c-4572-b0cb-696e77e93c81"
          },
          {
            "name": "#_N Net Contract",
            "displayFolder": "_Other KPIs_a",
            "expression": [
              "",
              "VAR Result = ",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , ALLEXCEPT('dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[dms_brand_cd]",
              "    , v_dim_group_sales[group_eng_name]",
              "    , v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)]",
              "     ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1), 0)",
              "    , 'dms_sales_contract'[contract_reg_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]),1), -1) +1)",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "c6222856-41af-43cb-86d7-2f76a5bb3667"
          },
          {
            "name": "#_N-1 BOC",
            "displayFolder": "_Other KPIs_a",
            "expression": [
              "",
              "VAR Result = CALCULATE(",
              "    COUNTROWS('dms_sales_contract')",
              "    , ALLEXCEPT('dms_sales_contract',dms_co_report_variant_v[model_nm],v_dim_group_sales[dms_brand_cd],v_dim_group_sales[dealer_id],v_dim_group_sales[group_eng_name],v_dim_group_sales[group_name(New)] ,dms_co_report_variant_v[report_variant_nm])",
              "    , 'dms_sales_contract'[contract_reg_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              "    , ISBLANK('dms_sales_contract'[retail_sales_dt])",
              "    || 'dms_sales_contract'[retail_sales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              "    || 'dms_sales_contract'[contract_stat_cd] <> \"D4\"",
              "    , ISBLANK('dms_sales_contract'[cancel_dt]) || 'dms_sales_contract'[cancel_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              ")",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "ca346178-eac4-485f-92ed-61874b0e9d47"
          },
          {
            "name": "#_Sales_Forecast_Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "var num = [#_Sales_Forecast(31th)_MTD] - [#_Sales_Target(M)]",
              "RETURN ",
              "IF(num > 0, \"+\"&FORMAT(num, \"#\"), num)"
            ],
            "formatString": "#,0",
            "lineageTag": "e6f840b5-bbc6-41eb-81b1-385aed5b57eb"
          },
          {
            "name": "#_Sales_Gap",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "var num = [#_Sales_CurrentPace_MTD] - [#_Sales_Target(D)_MTD]",
              "RETURN",
              "IF(num > 0, \"+\"&FORMAT(num, \"#\"), num)"
            ],
            "formatString": "#,0",
            "lineageTag": "6cd6f696-0dca-46fb-9845-2ae2410d90e2"
          },
          {
            "name": "#_Sales_Target_LM_Ratio(CP/D)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_LM], [#_Sales_Target(D)_LM], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "726044fa-d2df-4487-8dfe-c522dc5b71f9"
          },
          {
            "name": "#_Sales_Target_LY_Ratio(CP/D)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "DIVIDE([#_Sales_LY], [#_Sales_Target(D)_LY], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "6e127d13-fa71-4855-8f6a-cefeb5df0840"
          },
          {
            "name": "#_Sales_Target_Ratio(CP/D)_Gap(M)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "",
              "var num = ROUND(([#_Sales_Target_Ratio(CP/D)] - [#_Sales_Target_LM_Ratio(CP/D)])*100,0)",
              "RETURN IF(num > 0, \"+\"&num&\"%\", num&\"%\")"
            ],
            "lineageTag": "55f31eb6-17fb-47f6-8a30-ad4b702ed293"
          },
          {
            "name": "#_Sales_Target_Ratio(CP/D)_Gap(Y)",
            "displayFolder": "_Sales",
            "expression": [
              "",
              "",
              "var num = ROUND(([#_Sales_Target_Ratio(CP/D)] - [#_Sales_Target_LY_Ratio(CP/D)])*100,0)",
              "RETURN IF(num > 0, \"+\"&num&\"%\", num&\"%\")"
            ],
            "lineageTag": "1336d455-47fe-452e-805d-1a29f9d9930b"
          },
          {
            "name": "#_Sales_Target(D)_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "CALCULATE([#_Sales_Target(D)_MTD], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "4fb3ad5d-e7fe-409d-bf17-e8e80b0ea954"
          },
          {
            "name": "#_Sales_Target(D)_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales",
            "expression": [
              "",
              "CALCULATE([#_Sales_Target(D)_MTD], DATEADD(v_dim_calendar[date], -1, year))"
            ],
            "formatString": "#,0",
            "lineageTag": "4010ab99-c199-40b7-afe5-0bcd3326c12c"
          },
          {
            "name": "#_Sales_Seasonal_Result(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_MTD(N-2)],[#_Seasonal_Index(N-2)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "86e450f7-9925-4092-8d46-037c0dcff257"
          },
          {
            "name": "#_Sales_Seasonal_Result(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_MTD(N-3)],[#_Seasonal_Index(N-3)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "8f3fd2ff-6c80-4c4c-807e-b33cc5e66cf1"
          },
          {
            "name": "#_Sales_Seasonal_Target(AVG)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR _AVG = ([#_Sales_Seasonal_Target(N-1)] + [#_Sales_Seasonal_Target(N-2)] + [#_Sales_Seasonal_Target(N-3)])/3",
              "",
              "VAR _Result =",
              "ROUND(_AVG, -1)",
              "",
              "RETURN ",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "da04118c-67d7-43ec-bb40-1daa855d7903"
          },
          {
            "name": "#_Sales_Seasonal_Target(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_Target(N-1)],[#_Seasonal_Index(N-1)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "311ae88c-840a-4532-8eb7-efff48b6a05c"
          },
          {
            "name": "#_Sales_Seasonal_Target(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_Target(N-2)],[#_Seasonal_Index(N-2)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "bfed5eb4-cab3-4ace-ba43-293c210dc575"
          },
          {
            "name": "#_Sales_Seasonal_Target(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "DIVIDE(",
              "    [#_Sales_Target(N-3)],[#_Seasonal_Index(N-3)],-1",
              "    ) * 1200",
              "",
              "VAR _B = ",
              "ROUND(_A, -1) ",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0",
            "lineageTag": "0ebff009-e32f-4749-bc7e-8c4cbd0e5324"
          },
          {
            "name": "#_Sales_Target(N-1)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE)-1, 1) -1  //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_Target(M)],DATEADD(v_dim_calendar[date], -1, MONTH))",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "8c6afa63-4212-4a3a-8399-1af09c52f1f8"
          },
          {
            "name": "#_Sales_Target(N-2)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_Target(M)],DATEADD(v_dim_calendar[date], -2, MONTH))",
              "    ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "febc5c82-9665-401d-97a3-f4db509a617c"
          },
          {
            "name": "#_Sales_Target(N-3)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Sales_Seasonal Trend",
            "expression": [
              "",
              "VAR F_DATE = FIRSTDATE('v_dim_calendar'[date])",
              "VAR L_DATE = LASTDATE('v_dim_calendar'[date])",
              "VAR MINDATE = DATE(YEAR(F_DATE), MONTH(F_DATE) - 14, DAY(F_DATE))",
              "VAR MAXDATE = DATE(YEAR(L_DATE), MONTH(L_DATE) - 1, 1) - 1 //1   ",
              "",
              "VAR _Result = ",
              "    CALCULATE([#_Sales_Target(M)],DATEADD(v_dim_calendar[date], -3, MONTH))",
              "           ",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "9f5fc3fc-2488-4339-b470-d36b5061563f"
          },
          {
            "name": "#_OtherKPIs_Blank_Filter",
            "displayFolder": "_Other KPIs_a",
            "expression": [
              "",
              "IF([#_N Sales_Plan]=0 && [#_N-1 Local_Stock]=0 && [#_N Arrival]=0 && [#_N-1 BOC]= 0 && [#_N Net Contract]= 0,0,1)"
            ],
            "formatString": "#,0",
            "lineageTag": "8e4f77a1-c099-4045-a1f4-cee82efd8138"
          },
          {
            "name": "#_BOC_Blank_Filter",
            "displayFolder": "_BOC Information",
            "expression": [
              "",
              "IF([#_1M BOC]=0 && [#_1~3M BOC]=0 && [#_4~6M BOC]=0 && [#_~6M BOC]= 0,0,1)"
            ],
            "formatString": "#,0",
            "lineageTag": "077f7a70-680c-4e72-b8ed-7f92e8dd61ec"
          },
          {
            "name": "#_Trend_Sales_Ratio_Blank_Filter",
            "displayFolder": "_Sales",
            "expression": "IF([#_Sales_LM_Ratio(%)]=0&&[#_Sales_3M/AVG_Ratio(%)]=0&&[#_Sales_6M/AVG_Ratio(%)]=0&&[#_Sales_LY_Ratio(%)]=0,0,1)",
            "formatString": "#,0",
            "lineageTag": "fc73b7bd-e5bf-4bbe-ab44-1d5ba68504f8"
          },
          {
            "name": "#__Trend_Contract_Ratio_Blank_Filter",
            "displayFolder": "_Contract",
            "expression": "IF([#_Contract_LM_Ratio(%)]=0&&[#_Contract_3M/AVG_Ratio(%)]=0&&[#_Contract_6M/AVG_Ratio(%)]=0&&[#_Contract_LY_Ratio(%)]=0,0,1)",
            "formatString": "0",
            "lineageTag": "1b5ce7f5-705b-485b-981f-286c4a57c014"
          },
          {
            "name": "#_N Sales_Plan",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Other KPIs_a",
            "expression": [
              "",
              "VAR Result = CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , dms_sales_kpi_resource_day[sa_kpi_code_type] = \"DMS_BI_SA003\"",
              "    , dms_sales_kpi_resource_day[sa_kpi_code] = \"RETAIL_SALES\")",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "5df4fbf0-3362-46e0-b225-a20b26bf2b31"
          }
        ],
        "partitions": [
          {
            "name": "dms_sales_contract",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_sales_contract_Table = dev_twice_Schema{[Name=\"dms_sales_contract\",Kind=\"Table\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_sales_contract_Table, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_svc_kpi_resource",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d28dc1fe-1e8e-4617-b418-85da71b79f6a",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4034175f-6ec1-4e57-b184-7e536421e28e",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "830f81c9-1e5f-4a7e-af56-7cbb16f104ea",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c12e5219-5a1e-422c-9dae-008ea01263ec",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "svc_kpi_code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "658bead3-41c5-4c28-ac23-4e696bcf9286",
            "sourceColumn": "svc_kpi_code_type",
            "summarizeBy": "none"
          },
          {
            "name": "svc_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5e70d97a-122f-4124-9044-86388cd9e11d",
            "sourceColumn": "svc_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "svc_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "692c8419-e56f-4c0a-95e2-e0dcc452dcdc",
            "sourceColumn": "svc_kpi_code_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "YYYYMMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    LEFT('dms_svc_kpi_resource'[YYYYMM], 4), //  ",
              "    RIGHT('dms_svc_kpi_resource'[YYYYMM], 2), //  ",
              "    1 //  1       ",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "7ef7a0e8-96e3-41b2-9660-b1a5ecd6d392",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MON_ENG_NAME",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH(RIGHT(dms_svc_kpi_resource[yyyymm], 2), \"01\", \"JAN\", \"02\", \"FEB\", \"03\", \"MAR\", \"04\", \"APR\", \"05\", \"MAY\", \"06\", \"JUN\", \"07\", \"JUL\", \"08\", \"AUG\", \"09\", \"SEP\", \"10\", \"OCT\", \"11\", \"NOV\", \"12\", \"DEC\")",
            "isDataTypeInferred": true,
            "lineageTag": "5dc16c84-b7de-4f51-992e-3c42c684d865",
            "sortByColumn": "MON_ORD",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MON_ORD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "DataType"
              }
            ],
            "dataType": "int64",
            "expression": "RIGHT(dms_svc_kpi_resource[yyyymm], 2)",
            "formatString": "0",
            "lineageTag": "8b543bb7-c8cf-4077-be66-315885228b32",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "Category_Sub",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "04737ddc-0527-4e85-8869-712866ab2e1a",
            "sourceColumn": "Category_Sub",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "b766c7f1-cb8d-4835-9213-732241041db2",
        "measures": [
          {
            "name": "@_LT_WEEKDAYS_LM",
            "expression": [
              "",
              "",
              "VAR _A = CALCULATE(AVERAGE('dms_svc_kpi_resource'[svc_kpi_code_amt]), ",
              "                    'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_WEEKDAY_AVG\"",
              "                    )",
              "",
              "VAR _B = CALCULATE(_A, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_B),0,_B)"
            ],
            "formatString": "0.0",
            "lineageTag": "c9f48fb5-fc18-4f92-ab9a-951a84f4da9c"
          },
          {
            "name": "@_LT_WEEKENDS_LM",
            "expression": [
              "",
              "",
              "VAR _A = CALCULATE(AVERAGE('dms_svc_kpi_resource'[svc_kpi_code_amt]), ",
              "                    'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_WEEKEND_AVG\"",
              "                    )",
              "",
              "VAR _B = CALCULATE(_A, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_B),0,_B)"
            ],
            "formatString": "0.0",
            "lineageTag": "bcc364b0-bfaf-4e4c-b419-e31ed90ecdfa"
          },
          {
            "name": "@_AICC",
            "expression": [
              "",
              "",
              "VAR _A = CALCULATE(AVERAGE('dms_svc_kpi_resource'[svc_kpi_code_amt]), ",
              "                    'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_AICC_WEEKDAY_AVG\" ",
              "                    ||'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_AICC_WEEKEND_AVG\"",
              "                    )",
              "",
              "RETURN",
              "IF(ISBLANK(_A),0,_A)"
            ],
            "formatString": "0.0",
            "lineageTag": "ec0980c9-9fae-4997-9c9f-61f5f0255fe4"
          },
          {
            "name": "@_RATIO_LT_WEEKDAYS",
            "expression": [
              "",
              "    VAR _LT_WEEKDAYS_LM = CALCULATE([@_LT_WEEKDAYS_LM], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "    DIVIDE([@_LT_WEEKDAYS_LM], _LT_WEEKDAYS_LM, \"0\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3d2c5405-1c24-4721-8fc0-5d3831715b51"
          },
          {
            "name": "@_RATIO_LT_WEEKENDS",
            "expression": [
              "",
              "    VAR _LT_WEEKENDS_LM = CALCULATE([@_LT_WEEKENDS_LM], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "    DIVIDE([@_LT_WEEKENDS_LM], _LT_WEEKENDS_LM, \"0\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "100712ec-5d2c-457f-a269-39d25419b4f5"
          },
          {
            "name": "@_LT_LM_WEEKDAYS",
            "expression": [
              "",
              "",
              "VAR _VALUE = CALCULATE(AVERAGE('dms_svc_kpi_resource'[svc_kpi_code_amt]), ",
              "                    'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_WEEKDAY_AVG\" ",
              "                     , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "",
              "RETURN",
              "    IF(ISBLANK(_VALUE),0,_VALUE)"
            ],
            "formatString": "0.0",
            "lineageTag": "f4023457-4ba0-40a9-b974-8960731e09af"
          },
          {
            "name": "@_Blank",
            "expression": "\"-\" ",
            "lineageTag": "74e68218-1310-4a68-9891-31bbebcc9613"
          },
          {
            "name": "@_LT_LM_WEEKENDS",
            "expression": [
              "",
              "",
              "VAR _VALUE = CALCULATE(AVERAGE('dms_svc_kpi_resource'[svc_kpi_code_amt]), ",
              "                    'dms_svc_kpi_resource'[svc_kpi_code] = \"SVC_GR_RESV_WEEKKEND_AVG\" ",
              "                     , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "",
              "RETURN",
              "    IF(ISBLANK(_VALUE),0,_VALUE)"
            ],
            "formatString": "0.0",
            "lineageTag": "8addc3fe-c14d-4931-8709-8e10a1edefda"
          }
        ],
        "partitions": [
          {
            "name": "dms_svc_kpi_resource",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_svc_kpi_resource_Table = dev_twice_Schema{[Name=\"dms_svc_kpi_resource\",Kind=\"Table\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_svc_kpi_resource_Table, \"Category_Sub\"",
                "    , each if [svc_kpi_code] = \"SVC_BP_SA\" then \"SA\" ",
                "        else if [svc_kpi_code] = \"SVC_BP_TECH\" then \"TECH\" ",
                "        else if [svc_kpi_code] = \"SVC_BP_STALL\" then \"STALL\" ",
                "        else if [svc_kpi_code] = \"SVC_GS_SA\" then \"SA\" ",
                "        else if [svc_kpi_code] = \"SVC_GS_TECH\" then \"TECH\" ",
                "        else if [svc_kpi_code] = \"SVC_GS_STALL\" then \"STALL\" ",
                "        else \"\", type text)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_svc_resv",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e9b96d0f-9f94-44da-8ece-f63524f7bf94",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e85f6559-f8ee-4ea6-a63b-e81670454f60",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "resv_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d1006eaf-0ea4-4f00-8511-a0491996b0a3",
            "sourceColumn": "resv_dt",
            "summarizeBy": "none"
          },
          {
            "name": "resv_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "fe66d1d5-0a35-4a52-aa45-8f7824a822a4",
            "sourceColumn": "resv_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "real_resv_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "396ccaf3-d506-4195-a25d-f2636821de3b",
            "sourceColumn": "real_resv_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_6ccbc330-3633-4ff8-8015-ab2c92b5c621"
                },
                "isDefault": true,
                "relationship": "3f7c178a-877c-4470-83da-b4379e69ca53"
              }
            ]
          },
          {
            "name": "real_resv_st_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "15885cf2-27a3-4131-b28b-b8c1f4b0a221",
            "sourceColumn": "real_resv_st_time",
            "summarizeBy": "none"
          },
          {
            "name": "real_resv_end_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "debf029c-51c7-4535-a72b-5cd728ee4094",
            "sourceColumn": "real_resv_end_time",
            "summarizeBy": "none"
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e5e3c10a-1198-4039-ac38-d163b722ffe3",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "resv_way_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ee5c2f2-7d03-4864-8904-d0e00427cd3b",
            "sourceColumn": "resv_way_cd",
            "summarizeBy": "none"
          },
          {
            "name": "resv_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "94915a39-f9b0-43b9-8f39-296cf959392e",
            "sourceColumn": "resv_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_25c3233b-52b3-4306-9c62-d2fc8ef22e46"
                },
                "isDefault": true,
                "relationship": "d1d40580-aeee-4c1f-b9ad-4fb2bed013d9"
              }
            ]
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "fc83e4f5-b781-4afc-ade8-641be4ec19f2",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "LT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": "DATEDIFF('dms_svc_resv'[resv_reg_dt], 'dms_svc_resv'[real_resv_dt], day)",
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "56bc2cb7-d087-415e-a5d7-6df9b43300c6",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "71f83642-c0d8-43e8-9b45-9b6b33d9403f",
        "partitions": [
          {
            "name": "dms_svc_resv",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.Query(\"dsn=TOYOTA1\", \"SELECT *#(lf)FROM dms_svc_resv dsr #(lf)WHERE EXTRACT(YEAR FROM TO_DATE(resv_dt, 'YYYYMMDD')) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5;\")",
                "in",
                "    "
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6ccbc330-3633-4ff8-8015-ab2c92b5c621",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9c7db9a6-176d-4015-959c-522e89f4eb4e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "0cc99010-911d-4e2f-a673-c1f07dbe5dd4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "dd7cd2dd-c773-462a-b24f-b34e054e9ce3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "12ab99dc-c2bc-4e82-8e3f-48187c7c8f90",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "15433160-f9f3-4cc5-b3b8-5537900c30e3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b67c00b2-3564-44f3-979c-5c2d3fb8be11",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "32ee6e1d-5519-48d0-a951-dcff0e3012e1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "389c7cfe-4928-418a-8953-965e5c6572e7",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b8ff3daf-9fed-484d-962e-bdc1aa8c4e8f",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "64c71b45-f1c9-4f8f-b752-b8094c30948d",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "ea9e1b90-c619-43e3-803d-51aa8a71a1f5",
                "ordinal": 3
              }
            ],
            "lineageTag": "2136e84f-eb93-4ea0-ab88-178c64adab29"
          }
        ],
        "isHidden": true,
        "lineageTag": "8c48225e-507e-4301-8780-21f122d19fde",
        "partitions": [
          {
            "name": "LocalDateTable_6ccbc330-3633-4ff8-8015-ab2c92b5c621",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_svc_resv'[real_resv_dt])), 1, 1), Date(Year(MAX('dms_svc_resv'[real_resv_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_25c3233b-52b3-4306-9c62-d2fc8ef22e46",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ad252b30-4342-4006-b61e-b7017399523e",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "88768f67-fa79-4947-afd1-d15019e3a2d0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "b2a3bcdb-a71c-42f9-8288-16846436a7a4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "01064fb3-76ef-48cd-9218-1fdd47a69b5a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2fc64856-9713-44c8-b278-502e8f37e730",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "efcbd6d1-d08d-45b2-b3d3-1e78ba2bf52a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "374420fc-331d-4108-b000-9790ddbac737",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "01eadbd0-dc03-4233-81e0-d77b9e3ecb9e",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "40c3fa1c-5bea-49b3-888c-3bf104e09c9a",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "23f9dc5b-fde7-432e-b76b-4a35a78392b6",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "7bf3954e-717e-46e2-8d3a-ed6ed99e797a",
                "ordinal": 3
              }
            ],
            "lineageTag": "bf038682-8b01-4461-8242-eb071f1ffad8"
          }
        ],
        "isHidden": true,
        "lineageTag": "90093257-4e65-4c11-978f-83903ca0e212",
        "partitions": [
          {
            "name": "LocalDateTable_25c3233b-52b3-4306-9c62-d2fc8ef22e46",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_svc_resv'[resv_reg_dt])), 1, 1), Date(Year(MAX('dms_svc_resv'[resv_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_svc_ro",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8ec8211-8137-4ece-b4f9-9288845ca6dd",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2e5ff9ba-34f6-46dc-b30e-c7856a53b439",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "propo_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "048554d8-1eab-4434-a826-8e4b892200b3",
            "sourceColumn": "propo_dt",
            "summarizeBy": "none"
          },
          {
            "name": "propo_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "891b94b5-c7b2-46e6-a258-1461cddbb96d",
            "sourceColumn": "propo_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "repair_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0d36e868-0ce4-4dee-abca-08481951e462",
            "sourceColumn": "repair_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7498a17-4751-4db1-9ec1-3a7b2b7c96db",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "cust_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "63e9120b-bf16-4183-be78-779f4ca38757",
            "sourceColumn": "cust_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "stat_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0f6db3b-6783-4fd6-8956-ff822d2e0159",
            "sourceColumn": "stat_cd",
            "summarizeBy": "none"
          },
          {
            "name": "cnfm_part_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a417921b-23c5-4a00-8f11-1eccf303bf90",
            "sourceColumn": "cnfm_part_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "cnfm_labor_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b2c57881-a5e8-45b9-a55a-68366107de92",
            "sourceColumn": "cnfm_labor_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "cnfm_sublet_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "dfb2130f-77e1-4cb4-a05f-6ecc189c74e1",
            "sourceColumn": "cnfm_sublet_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "ro_close_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4c9ef14b-0c3b-4243-86ab-f6b29d2250f3",
            "sourceColumn": "ro_close_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_3414bbc0-0998-4b37-a847-3f8de40a0059"
                },
                "isDefault": true,
                "relationship": "d63255a3-8295-46d7-a1bb-febea6d9e850"
              }
            ]
          },
          {
            "name": "ro_close_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "98a3cdfc-d5cb-402e-bfc9-235feee9249a",
            "sourceColumn": "ro_close_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "ro_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cac88d10-54f6-4168-ab63-ffac2473c29e",
            "sourceColumn": "ro_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_206d6f31-9f04-40a7-bbe0-440b93664244"
                },
                "isDefault": true,
                "relationship": "969eb54c-9ff2-4628-991d-3f96199daf5a"
              }
            ]
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c5d80867-072a-4fba-8b52-07a8a2273660",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "ro_close_crt_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34220398-7594-407e-84ba-932fadf15691",
            "sourceColumn": "ro_close_crt_cd",
            "summarizeBy": "none"
          },
          {
            "name": "mh",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "9954562f-1823-4b3d-92a4-ec8266fb8273",
            "sourceColumn": "mh",
            "summarizeBy": "sum"
          },
          {
            "name": "retail_year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bff992da-f33e-45fe-93ca-c8bd6d0b6568",
            "sourceColumn": "retail_year",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "                LEFT('dms_svc_ro'[propo_dt], 4), // '2023'   ",
              "                MID('dms_svc_ro'[propo_dt], 5, 2), // '01'   ",
              "                1 // (day) 1       ",
              "            )"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "ac2b8977-5e45-4136-8cdc-cadf88a87f93",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "786e56d9-c788-463c-beb8-3716547197e5",
        "measures": [
          {
            "name": "@_TGUS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR TGUS = ",
              "CALCULATE(COUNTROWS('dms_svc_ro')",
              ", dms_svc_ro[repair_type_cd] = \"1\"",
              "&& 'dms_svc_ro'[stat_cd] <> \"99\"",
              "&& ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"FMS\" ",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"PSP\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"PO\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"GR\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"WT\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"IT\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"FMS_1K\")))",
              "",
              "RETURN",
              "    IF(ISBLANK(TGUS), 0, TGUS)",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "38a05778-6c01-46d7-a502-732b80c24ca3"
          },
          {
            "name": "@_RATIO_TGUS",
            "expression": [
              "",
              "    VAR _TGUS_LM = CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "    VAR _TGUS_PTM = CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -2, MONTH))",
              "    VAR _RESULT = DIVIDE(_TGUS_LM, _TGUS_PTM, \"0\")",
              "",
              "RETURN",
              "    IF(ISBLANK(_RESULT), \"0\", _RESULT)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6b708ffc-0b5e-4d79-9629-4b95244fd51e"
          },
          {
            "name": "@_PM(1M/FMS/PSP)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR PM = CALCULATE(COUNTROWS('dms_svc_ro')",
              ", 'dms_svc_ro'[stat_cd] <> \"99\"",
              ", ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"FMS\" ",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"PSP\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"PO\")",
              "|| ('dms_svc_ro'[ro_close_type_cd] <> \"BP\" && 'dms_svc_ro'[ro_close_type_cd] = \"FMS_1K\")))",
              "",
              "RETURN",
              "    IF(ISBLANK(PM),0,PM)"
            ],
            "formatString": "#,0",
            "lineageTag": "f5c0beda-bc38-427b-b717-1c4cd27d5a0e"
          },
          {
            "name": "@_PM_SVC_RATIO",
            "expression": "DIVIDE([@_PM(1M/FMS/PSP)], [@_TGUS], \"0\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "2924b898-d32c-41cc-a796-b99deab7078d"
          },
          {
            "name": "@_RATIO_PM_SVC_RATIO_LM",
            "expression": [
              "",
              "    VAR _PM_LM = CALCULATE([@_PM(1M/FMS/PSP)], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "    VAR _TGUS_LM = CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "    VAR _PM_SVC_RATIO_LM = DIVIDE(_PM_LM, _TGUS_LM, \"0\")",
              "RETURN",
              "    DIVIDE([@_PM_SVC_RATIO], _PM_SVC_RATIO_LM, \"0\")",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "18395fc0-586e-41f1-98b1-ac3d3ddbcaec"
          },
          {
            "name": "@_DLR_BPUS",
            "expression": [
              "",
              "VAR _A = ",
              "CALCULATE(COUNTROWS(dms_svc_ro)",
              ", dms_svc_ro[ro_close_type_cd] = \"BP\"",
              ", dms_svc_ro[stat_cd] <> \"99\")",
              "",
              "RETURN",
              "IF(ISBLANK(_A), 0, _A)"
            ],
            "formatString": "#,0",
            "lineageTag": "2ea7a0d5-94e3-4767-a994-3e0ae277e199"
          },
          {
            "name": "@_RATIO_DLR_BPUS_LM",
            "expression": [
              "",
              "",
              "VAR _DLR_BPUS_LM = CALCULATE(",
              "                            CALCULATE(",
              "                                        COUNTROWS(dms_svc_ro)",
              "                                        , dms_svc_ro[ro_close_type_cd] = \"BP\"",
              "                                        , dms_svc_ro[stat_cd] <> \"99\"",
              "                                    )",
              "                                        , PREVIOUSMONTH(v_dim_calendar[date])",
              "                            )",
              "",
              "VAR _DLR_BPUS_PTM = CALCULATE(",
              "                            CALCULATE(",
              "                                        COUNTROWS(dms_svc_ro)",
              "                                        , dms_svc_ro[ro_close_type_cd] = \"BP\"",
              "                                        , dms_svc_ro[stat_cd] <> \"99\"",
              "                                    )",
              "                                        , DATEADD(v_dim_calendar[date], -2, MONTH)",
              "                            )                            ",
              "",
              "RETURN",
              "    IF(ISBLANK(DIVIDE(_DLR_BPUS_LM, _DLR_BPUS_PTM, \"0\")), \"0\", DIVIDE(_DLR_BPUS_LM, _DLR_BPUS_PTM, \"0\"))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "96a125d6-1c83-4b83-bd08-de7898b5d215"
          },
          {
            "name": "@_TGUS_LM",
            "expression": [
              "",
              "CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "#,0",
            "lineageTag": "483b38bf-e74c-416a-9f56-2477ef460a50"
          },
          {
            "name": "@_TGUS_LM_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "     VAR _CNT = DISTINCTCOUNT(dms_svc_ro[dealer_id])",
              "",
              "RETURN     ",
              "    CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -1, MONTH)) / _CNT"
            ],
            "formatString": "#,0",
            "lineageTag": "ee2ff49c-ee84-4c2f-a483-2903eaec6c7d"
          },
          {
            "name": "@_TGUS_PTM",
            "expression": [
              "",
              "    CALCULATE([@_TGUS], DATEADD(v_dim_calendar[date], -2, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "91bd9e50-2298-45e7-9526-9f875bb0230e"
          },
          {
            "name": "@_DLR_BPUS_LM",
            "expression": [
              "",
              "    VAR _RESULT = CALCULATE(",
              "                            CALCULATE(",
              "                                        COUNTROWS(dms_svc_ro)",
              "                                        , dms_svc_ro[ro_close_type_cd] = \"BP\"",
              "                                        , dms_svc_ro[stat_cd] <> \"99\"",
              "                                    )",
              "                                        , PREVIOUSMONTH(v_dim_calendar[date])",
              "                            )",
              "",
              "RETURN",
              "    IF(ISBLANK(_RESULT), 0, _RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "104d9197-04a0-4564-aae8-696a960f8984"
          },
          {
            "name": "@_DLR_BPUS_LM_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "    VAR _CNT = DISTINCTCOUNT(dms_svc_ro[dealer_id])",
              "    VAR _RESULT = CALCULATE(",
              "                            CALCULATE(",
              "                                        COUNTROWS(dms_svc_ro)",
              "                                        , dms_svc_ro[ro_close_type_cd] = \"BP\"",
              "                                        , dms_svc_ro[stat_cd] <> \"99\"",
              "                                    )",
              "                                        , PREVIOUSMONTH(v_dim_calendar[date])",
              "                            )",
              "                    /",
              "                    _CNT",
              "",
              "RETURN",
              "    IF(ISBLANK(_RESULT), 0, _RESULT)"
            ],
            "formatString": "0",
            "lineageTag": "cc5f13f1-dce2-42a7-be3c-4e19a7e30548"
          }
        ],
        "partitions": [
          {
            "name": "dms_svc_ro",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.Query(\"dsn=TOYOTA1\", \"SELECT *#(lf)FROM dms_svc_ro dsr#(lf)WHERE EXTRACT(YEAR FROM TO_DATE(propo_dt, 'YYYYMMDD')) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5;\")",
                "in",
                "    "
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_co_variant",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e65914fe-3937-4249-abb4-e4c08c78a794",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1e8b64a6-19df-4a94-b9f3-869e25de7c8a",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8a317269-199a-479d-bfd2-23c3a9cb5c71",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29f58390-91e6-44b3-933f-e7e537010344",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ab484329-6233-49d8-8712-f480e92573ea",
            "sourceColumn": "variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "display_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43a73e7a-85b9-45c4-8025-2f0d12f85ba8",
            "sourceColumn": "display_order",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "db0d6d15-73c2-45dd-bacb-4db206d842d3",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "my_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a7260d3-9da9-4a14-9595-4f6dc27631a0",
            "sourceColumn": "my_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sfx_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a1c3b063-aed2-4000-aa27-95c6ee8c34ad",
            "sourceColumn": "sfx_cd",
            "summarizeBy": "none"
          },
          {
            "name": "col_combi_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3729a53f-a942-45f4-af69-92d9b9d0c984",
            "sourceColumn": "col_combi_cd",
            "summarizeBy": "none"
          },
          {
            "name": "col_combi_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58e1848c-9e38-4879-a798-9975375845bc",
            "sourceColumn": "col_combi_nm",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d952fba7-9c99-4a70-9ca5-c05467d4099f",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0c42455-4377-4dc7-8ff4-4a5d94f8dbd3",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cfc62055-97fb-4434-840f-b5fb10e6bf78",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "YYYYMMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    LEFT('dms_co_variant'[YYYYMM], 4), //  ",
              "    RIGHT('dms_co_variant'[YYYYMM], 2), //  ",
              "    1 //  1       ",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "ad3abb07-d530-4a7a-8c78-e6ce9240894e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "21c7b83a-88dc-4f50-ba3b-6ef55b2cb412",
        "partitions": [
          {
            "name": "dms_co_variant",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_variant_Table = dev_twice_Schema{[Name=\"dms_co_variant\",Kind=\"Table\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_co_variant_Table, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_svc_ro_sales",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83a902a0-5f98-4035-a3ba-bcf94d2c60c2",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "123362d0-9475-4c5a-89e0-43c7ae4e0d15",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "propo_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7ed571ea-39b3-4fe2-9274-693a6daaf7d6",
            "sourceColumn": "propo_dt",
            "summarizeBy": "none"
          },
          {
            "name": "propo_seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b48b61ca-56a8-4870-807f-db90b3427f69",
            "sourceColumn": "propo_seq",
            "summarizeBy": "sum"
          },
          {
            "name": "ro_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a921162f-b3ce-4992-aac9-9ec67fcfdcb5",
            "sourceColumn": "ro_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "59d22d5e-2041-4153-bfd2-05bbec888a56",
            "sourceColumn": "sales_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_2265f050-6358-412e-aba6-8fab6e0db912"
                },
                "isDefault": true,
                "relationship": "ed4a71b9-1654-4ccc-b59a-4b423d052582"
              }
            ]
          },
          {
            "name": "sales_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "710a0d4a-34ff-41bd-b1f2-424ef4b00876",
            "sourceColumn": "sales_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6ddac610-d618-4325-ba1e-1711470d8c8a",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "9018fdfc-1a22-4031-91df-53d8c6e29f52",
        "partitions": [
          {
            "name": "dms_svc_ro_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_svc_ro_sales_Table = dev_twice_Schema{[Name=\"dms_svc_ro_sales\",Kind=\"Table\"]}[Data]",
                "in",
                "    dms_svc_ro_sales_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_2265f050-6358-412e-aba6-8fab6e0db912",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "77ab5b07-86f6-44d0-a1f4-3890052646b0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "911ed7f7-e8b6-4013-8af2-fe3ef860c7f6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8d84bedf-9d58-4f40-9bac-4e2b5867b8fc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "7efd6090-1944-42a6-aa07-751b96b76801",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "514ac520-62e5-469f-963e-d02506c101ef",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "25215837-692a-4abc-9d59-135f371a8834",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a9b96e53-83d3-4e9d-ac59-2962094e6a23",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "a6909d31-20a2-49dd-9464-58be4c5ecd9f",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "17a94015-0dc5-4581-a0c0-a418d3b73a60",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "e7ebbbab-7f8b-4d2f-90ef-35ef431d1102",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1daa9546-890c-48b3-8896-ef0a703551a3",
                "ordinal": 3
              }
            ],
            "lineageTag": "591c6ccf-e819-465f-b1dc-f142dd793823"
          }
        ],
        "isHidden": true,
        "lineageTag": "50a005b7-db2a-4e67-af7d-14c8dcb6930f",
        "partitions": [
          {
            "name": "LocalDateTable_2265f050-6358-412e-aba6-8fab6e0db912",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_svc_ro_sales'[sales_dt])), 1, 1), Date(Year(MAX('dms_svc_ro_sales'[sales_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_206d6f31-9f04-40a7-bbe0-440b93664244",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a7006dc7-72bf-43ca-b8c1-0bf10af69a80",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9870e1e5-4fa6-4c7d-9055-28ef4e908db5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "332f8ae3-1a76-4bb3-a46d-77e33b1dad7f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3fff2f1f-3c07-47e0-8509-6fc33a966e35",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "00ce2d49-d384-4597-997f-5710831c7024",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1282b8cb-b0a4-43f0-bcc5-30fb7e4f2159",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "b3dab815-5fd2-48fb-9ca5-9f6ea4d5664c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "278c1a2e-1fa4-4a57-b1ce-9654164fed5b",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "13598e7e-bffb-46b5-9bb1-eb5e8a900c25",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "84789ab6-fe69-402c-ac5c-0b0647ad3914",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "46ad0e2d-707f-4e45-bb47-f36cbd933ff4",
                "ordinal": 3
              }
            ],
            "lineageTag": "85e27246-fd00-4cf0-9d73-a4f7d7a26154"
          }
        ],
        "isHidden": true,
        "lineageTag": "41648edf-419f-4b28-8353-d2572b396de9",
        "partitions": [
          {
            "name": "LocalDateTable_206d6f31-9f04-40a7-bbe0-440b93664244",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_svc_ro'[ro_reg_dt])), 1, 1), Date(Year(MAX('dms_svc_ro'[ro_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_svc_act8_cust_v",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "180aabfb-d3c5-41a4-b957-2a8ef33d6ca6",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "615da3f5-a366-416b-bf78-222354c9431b",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a29fbd2-7cc8-4a9d-8e13-89f20a9a7a6c",
            "sourceColumn": "group_eng_name",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "141799a4-1424-44b3-a6ae-df79a6287fd4",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "806da11d-d87a-4a76-b3f2-8885c4fad6ba",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "530c5509-c79d-4a0b-bd66-3f6f45a25eb0",
            "sourceColumn": "result",
            "summarizeBy": "sum"
          },
          {
            "name": "vs_target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "31ec7226-8f39-49e1-a162-a4317a8185b1",
            "sourceColumn": "vs_target",
            "summarizeBy": "sum"
          },
          {
            "name": "Category(New)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "d78a2ddd-3804-4434-bb0b-49cce9ba784c",
            "sortByColumn": "Sort",
            "sourceColumn": "Category(New)",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "aad5acb0-09ad-4969-a52e-6a4f5931a1a8",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "                LEFT('dms_svc_act8_cust_v'[yyyymm], 4), // '2023'   ",
              "                MID('dms_svc_act8_cust_v'[yyyymm], 5, 2), // '01'   ",
              "                1 // (day) 1       ",
              "            )"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "ef4e3653-d9e6-4c2d-b225-3926f3b72f6d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "yyyy_mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f3bb065-c31a-4e14-b420-190a1097f00b",
            "sourceColumn": "yyyy_mm",
            "summarizeBy": "none"
          },
          {
            "name": "vs_result_ly",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "5e59d529-418a-4084-88b3-9ea315204881",
            "sourceColumn": "vs_result_ly",
            "summarizeBy": "sum"
          },
          {
            "name": "ACTIVE_CUST_RESULT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "expression": [
              "",
              "VAR svc_uio_result = ",
              "    CALCULATE(",
              "        MAX('dms_svc_act8_cust_v'[result]),",
              "        FILTER(",
              "            'dms_svc_act8_cust_v',",
              "            'dms_svc_act8_cust_v'[category] = \"SVC_UIO\"",
              "                && 'dms_svc_act8_cust_v'[dms_brand_cd] = EARLIER('dms_svc_act8_cust_v'[dms_brand_cd])",
              "                && 'dms_svc_act8_cust_v'[dealer_id] = EARLIER('dms_svc_act8_cust_v'[dealer_id])",
              "                && 'dms_svc_act8_cust_v'[yyyymm] = EARLIER('dms_svc_act8_cust_v'[yyyymm])",
              "        )",
              "    )",
              "VAR svc_active_cust_vs_target = ",
              "    CALCULATE(",
              "        MAX('dms_svc_act8_cust_v'[vs_target]),",
              "        FILTER(",
              "            'dms_svc_act8_cust_v',",
              "            'dms_svc_act8_cust_v'[category] = \"SVC_ACTIVE_CUST\"",
              "                && 'dms_svc_act8_cust_v'[dms_brand_cd] = EARLIER('dms_svc_act8_cust_v'[dms_brand_cd])",
              "                && 'dms_svc_act8_cust_v'[dealer_id] = EARLIER('dms_svc_act8_cust_v'[dealer_id])",
              "                && 'dms_svc_act8_cust_v'[yyyymm] = EARLIER('dms_svc_act8_cust_v'[yyyymm])",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        'dms_svc_act8_cust_v'[category] = \"SVC_ACTIVE_CUST\",",
              "        ROUND(svc_uio_result * svc_active_cust_vs_target / 100, 0),",
              "        BLANK()",
              "    )",
              ""
            ],
            "isDataTypeInferred": true,
            "lineageTag": "0d7f2887-8551-4a3a-b89d-c8abafb9e533",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "4de18c98-da48-45b7-918e-6916fff5fc5d",
        "measures": [
          {
            "name": "@_RATIO_ACTIVE_CRT",
            "expression": [
              "",
              "",
              "VAR _DEALER_UIO = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\")",
              "",
              "VAR _DEALER_AC = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AC_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\")",
              "",
              "",
              "VAR _TOTAL =",
              "IF(ISBLANK(DIVIDE(_DEALER_AC,_DEALER_UIO,\"-\")), DIVIDE(_DEALER_AC_Jan,_DEALER_UIO_Jan,\"-\"), DIVIDE(_DEALER_AC,_DEALER_UIO,\"-\"))",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), \"-\", _TOTAL)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "37e09862-c640-4161-91d9-80a965ca6841"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_TARGET",
            "expression": [
              "",
              "    VAR _DEALER_AC_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_OT_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"OWN CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
              "VAR _DEALER_AT = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AT_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CRT\")",
              "",
              "",
              "VAR _DEALER_OT = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"OWN CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\")",
              "",
              "",
              "VAR _DEALER_AC = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AC_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\")",
              "",
              "VAR _DEALER_FMS = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"FMS\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_PSP = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"PSP\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_GR = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_Target]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"GR\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _TOTAL =",
              "IF(ISBLANK(",
              "    DIVIDE(_DEALER_AC, _DEALER_UIO, 0))",
              "    , DIVIDE(_DEALER_AC_Jan, _DEALER_UIO_Jan, 0)",
              "    , DIVIDE(_DEALER_AC, _DEALER_UIO, 0))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0 , _TOTAL)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "02f1be15-8f95-45a0-84c8-deb21fd869f1"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_LY",
            "expression": [
              "",
              "    VAR _DEALER_AT_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "",
              "VAR _DEALER_UIO_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_Result_JAN = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\")",
              "",
              "",
              "VAR _DEALER_AC_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AC_Result_JAN = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\")",
              "",
              "VAR _DEALER_FMS_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"FMS\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_GR_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"GR\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_PSP_Result = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[result]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"PSP\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////",
              "",
              "VAR _DEALER_AT_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_OT_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"OWN CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_LY_JAN = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"UIO\")",
              "",
              "",
              "VAR _DEALER_AC_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AC_LY_JAN = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"ACTIVE CUST\")",
              "",
              "",
              "VAR _DEALER_FMS_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"FMS\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_PSP_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"PSP\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_GR_LY = CALCULATE(",
              "    SUM('dms_svc_act8_cust_v'[vs_result_ly]),",
              "     'dms_svc_act8_cust_v'[Category(New)] = \"GR\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _TOTAL = ",
              "IF(ISBLANK(",
              "DIVIDE(_DEALER_AC_Result, _DEALER_UIO_Result, \"-\") - DIVIDE(_DEALER_AC_LY, _DEALER_UIO_LY, \"-\"))",
              ", DIVIDE(_DEALER_AC_Result_JAN, _DEALER_UIO_Result_JAN, \"-\") - DIVIDE(_DEALER_AC_LY_JAN, _DEALER_UIO_LY_JAN, \"-\")",
              ", (DIVIDE(_DEALER_AC_Result, _DEALER_UIO_Result, \"-\") - DIVIDE(_DEALER_AC_LY, _DEALER_UIO_LY, \"-\")))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), \"-\", _TOTAL)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "35019d77-4109-4790-96b9-abe006232af9"
          },
          {
            "name": "@_Active_CRt_STAUTS_8Y",
            "expression": [
              "",
              "IF([@_RATIO_ACTIVE_CRT_TGT_8Y] >= 1 ",
              "    && [@_RATIO_ACTIVE_CRT_LY_8Y] >= 1 ",
              ", \"1\", -- ",
              "",
              "IF([@_RATIO_ACTIVE_CRT_TGT_8Y] <= 0.95",
              "    || [@_RATIO_ACTIVE_CRT_LY_8Y] >= 0.95",
              ", \"0\" -- ",
              ", \"2\")) --"
            ],
            "lineageTag": "a5fd4673-6c4a-46a6-a16e-a3e97895cf02"
          },
          {
            "name": "@_CRt_RESULT_8Y",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(",
              "                CALCULATE(",
              "                        SUM('dms_svc_act8_cust_v'[result]),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            v_dim_calendar[yyyy_mm] >= _From",
              "                            && v_dim_calendar[yyyy_mm] <= _To",
              "                            )",
              "                    )",
              "        )",
              "        , 0",
              "        , CALCULATE(",
              "                        SUM('dms_svc_act8_cust_v'[result]),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            v_dim_calendar[yyyy_mm] >= _From",
              "                            && v_dim_calendar[yyyy_mm] <= _To",
              "                            )",
              "                    )",
              "    )"
            ],
            "formatString": "#,0",
            "lineageTag": "55c01b6b-dad7-4c9a-beba-9a7ea88c69d2"
          },
          {
            "name": "@_ACTIVE_CRT_8Y",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "        DIVIDE(",
              "                CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"Active Cust\")",
              "                , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "                , 0",
              "                )",
              "        )",
              "        , 0",
              "        , DIVIDE(",
              "                CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"Active Cust\")",
              "                , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "                , 0",
              "                )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7e864001-5765-43a2-9021-a5a454c969d1"
          },
          {
            "name": "@_RATIO_CRT_8Y_FMS",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"FMS\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "38288223-abb1-45db-99f8-a1f490ce0bb2"
          },
          {
            "name": "@_RATIO_CRT_8Y_GR",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"GR\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2ef95c9d-2591-423b-a742-b827233cff82"
          },
          {
            "name": "@_RATIO_CRT_8Y_PSP",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"PSP\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bd8bcad5-40a7-4921-9a4d-40a4ae05758a"
          },
          {
            "name": "@_OWN_CRT_8Y",
            "displayFolder": "8Y_RESULT",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "            DIVIDE(",
              "                    CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"Own Crt\")",
              "                    , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "                    , 0",
              "                    )",
              "            )",
              "            , 0",
              "            , DIVIDE(",
              "                    CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_v[Category(New)] = \"Own Crt\")",
              "                    , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "                    , 0",
              "                    )",
              "    )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "58b81058-663c-4686-961e-c0b98482b473"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y ACTIVE CRT",
              "    VAR _8Y_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_ACTIVE_CRT - _LY_ACTIVE_CRT), \"-\", _8Y_ACTIVE_CRT - _LY_ACTIVE_CRT)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "b3f2dc33-1db3-4d44-93b2-b8de4678fbf2"
          },
          {
            "name": "@_RATIO_OWN_CRT_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y OWN CRT",
              "    VAR _8Y_OWN_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_OWN_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_OWN_CRT - _LY_OWN_CRT), \"-\", _8Y_OWN_CRT - _LY_OWN_CRT)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "a7ea942c-cfd0-4672-8c57-f5234a81af8a"
          },
          {
            "name": "@_UIO_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y UIO",
              "    VAR _8Y_UIO = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _LY_UIO = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[result]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(ISBLANK(DIVIDE(_8Y_UIO, _LY_UIO, \"-\")), 0, DIVIDE(_8Y_UIO, _LY_UIO, \"-\"))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4874ea1e-ec9a-4554-b1f1-dc7683d78b30"
          },
          {
            "name": "@_ACTIVE_CUST_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y ACTIVE_CUST",
              "    VAR _8Y_ACTIVE_CUST = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _8Y_LY_ACTIVE_CUST = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[result]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(ISBLANK(DIVIDE(_8Y_ACTIVE_CUST, _8Y_LY_ACTIVE_CUST, \"-\")), 0, DIVIDE(_8Y_ACTIVE_CUST, _8Y_LY_ACTIVE_CUST, \"-\"))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "df44cace-8192-4121-a69a-b3344e9e73a2"
          },
          {
            "name": "@_RATIO_FMS_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y ACTIVE CRT",
              "    VAR _8Y_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_FMS - _LY_RATIO_FMS), \"-\", _8Y_RATIO_FMS - _LY_RATIO_FMS)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c03fb374-59d5-493f-aa19-83e98a0d5c90"
          },
          {
            "name": "@_RATIO_GR_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y RATIO_GR",
              "    VAR _8Y_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "    -- LY RATIO_GR",
              "    VAR _LY_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_GR - _LY_RATIO_GR), \"-\", _8Y_RATIO_GR - _LY_RATIO_GR)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "42340027-2d5d-4cd5-a387-9339fb87a400"
          },
          {
            "name": "@_RATIO_PSP_LY_8Y",
            "displayFolder": "8Y_LY",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8y_ly",
              "    VAR _LY_From = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y RATIO_PSP",
              "    VAR _8Y_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "    -- LY RATIO_PSP",
              "    VAR _LY_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _LY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_PSP - _LY_RATIO_PSP), \"-\", _8Y_RATIO_PSP - _LY_RATIO_PSP)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0b38564b-fb17-47d6-9313-468e6cec0bb8"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y RATIO_ACTIVE CRT",
              "    VAR _8Y_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "    -- 8Y RATIO_ACTIVE TARGET",
              "    VAR _8Y_TARGET =",
              "                        CALCULATE(",
              "                                AVERAGE('dms_svc_act8_cust_v'[vs_target]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    ) / 100",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_ACTIVE_CRT - _8Y_TARGET), \"-\", _8Y_ACTIVE_CRT - _8Y_TARGET)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "c6b920d4-2fb9-41c7-9413-444c1233cf29"
          },
          {
            "name": "@_RATIO_OWN_CRT_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y RATIO Own Crt",
              "    VAR _8Y_Own_Crt = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "    -- 8Y RATIO Own Crt",
              "    VAR _8Y_TARGET =",
              "                        CALCULATE(",
              "                                AVERAGE('dms_svc_act8_cust_v'[vs_target]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    ) / 100",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_Own_Crt - _8Y_TARGET), \"-\", _8Y_Own_Crt - _8Y_TARGET)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0fae26fb-470b-40bd-9dd2-fc207d82d74c"
          },
          {
            "name": "@_UIO_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y UIO",
              "    VAR _8Y_UIO = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _TGT_UIO = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(ISBLANK(DIVIDE(_8Y_UIO, _TGT_UIO, \"-\")), 0, DIVIDE(_8Y_UIO, _TGT_UIO, \"-\"))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "043f8bfa-e965-46cc-b23e-0d8926ce2262"
          },
          {
            "name": "@_ACTIVE_CUST_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y ACTIVE CUST",
              "    VAR _8Y_ACTIVE_CUST = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _TGT_ACTIVE_CUST = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[ACTIVE_CUST_RESULT]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(ISBLANK(DIVIDE(_8Y_ACTIVE_CUST, _TGT_ACTIVE_CUST, \"-\")), 0, DIVIDE(_8Y_ACTIVE_CUST, _TGT_ACTIVE_CUST, \"-\"))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "47939b5f-2d6e-44f1-8d27-e2218b9bf403"
          },
          {
            "name": "@_RATIO_FMS_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y ACTIVE CRT",
              "    VAR _8Y_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_FMS - _TGT_RATIO_FMS), \"-\", _8Y_RATIO_FMS - _TGT_RATIO_FMS)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c5d8bda8-8522-4a2e-b4e8-d08afd4d969d"
          },
          {
            "name": "@_RATIO_PSP_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y PSP",
              "    VAR _8Y_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_PSP - _TGT_RATIO_PSP), \"-\", _8Y_RATIO_PSP - _TGT_RATIO_PSP)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e7151249-f0c9-46cb-b0d9-4c5faeb04028"
          },
          {
            "name": "@_RATIO_GR_TGT_8Y",
            "displayFolder": "8Y_TARGET",
            "expression": [
              "",
              "    -- 8Y",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _8Y_From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _8Y_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- 8Y GR",
              "    VAR _8Y_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _8Y_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _8Y_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_8Y_RATIO_GR - _TGT_RATIO_GR), \"-\", _8Y_RATIO_GR - _TGT_RATIO_GR)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "24e4eec9-14d8-4c1a-82cd-bde452410124"
          },
          {
            "name": "@_CRt_RESULT_WY",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = \"2009-01\"",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(",
              "                CALCULATE(",
              "                    SUM('dms_svc_act8_cust_v'[result]),",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        v_dim_calendar[yyyy_mm] >= _From",
              "                        && v_dim_calendar[yyyy_mm] <= _To",
              "                        )",
              "                )",
              "            )",
              "            , 0",
              "            , CALCULATE(",
              "                    SUM('dms_svc_act8_cust_v'[result]),",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        v_dim_calendar[yyyy_mm] >= _From",
              "                        && v_dim_calendar[yyyy_mm] <= _To",
              "                        )",
              "                )",
              "        )"
            ],
            "formatString": "#,0",
            "lineageTag": "48ea9309-acfc-4c1b-af5e-c08f1d3913b9"
          },
          {
            "name": "@_OWN_CRT_WY",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "            DIVIDE(",
              "            CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"Own Crt\")",
              "            , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "            , 0",
              "            )",
              "            )",
              "            , \"-\"",
              "            , DIVIDE(",
              "            CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"Own Crt\")",
              "            , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "            , 0",
              "            )",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "54189e52-bb67-4205-9ec3-750d746b8989"
          },
          {
            "name": "@_ACTIVE_CRT_WY",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "IF(",
              "    ISBLANK(",
              "            DIVIDE(",
              "            CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"Active Cust\")",
              "            , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "            , 0",
              "            )",
              "            )",
              "            , \"-\"",
              "            , DIVIDE(",
              "            CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"Active Cust\")",
              "            , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "            , 0",
              "            )",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "05da57db-1c79-4f26-adc9-764263d5aaea"
          },
          {
            "name": "@_RATIO_CRT_WY_FMS",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"FMS\")",
              "         , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "1e1bd9cd-ba21-439f-9344-aad4817018a2"
          },
          {
            "name": "@_RATIO_CRT_WY_GR",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"GR\")",
              "         , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "76922368-2a41-4111-898c-c3616694bb38"
          },
          {
            "name": "@_RATIO_CRT_WY_PSP",
            "displayFolder": "WY_RESULT",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_WY],dms_svc_act8_cust_v[Category(New)] = \"PSP\")",
              "         , CALCULATE([@_CRt_RESULT_WY], dms_svc_act8_cust_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bdaec029-334a-49ff-84ef-e71734ab8b30"
          },
          {
            "name": "@_RATIO_FMS_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "    -- WY",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY_LY",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_FMS - _LY_RATIO_FMS), \"-\", _WY_RATIO_FMS - _LY_RATIO_FMS)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1b1672fb-8e78-4728-811b-62f91001f135"
          },
          {
            "name": "@_RATIO_GR_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "    -- WY",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY_LY",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_GR - _LY_RATIO_GR), \"-\", _WY_RATIO_GR - _LY_RATIO_GR)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "1ccb97a0-fc6c-4248-a8f5-6f03dc6fdae8"
          },
          {
            "name": "@_RATIO_PSP_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "    -- WY",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY_LY",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_PSP - _LY_RATIO_PSP), \"-\", _WY_RATIO_PSP - _LY_RATIO_PSP)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "2746c7b1-a701-47e6-a1d0-debbcc511610"
          },
          {
            "name": "@_ACTIVE_CUST_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY ACTIVE_CUST",
              "    VAR _WY_ACTIVE_CUST = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _WY_LY_ACTIVE_CUST = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[result]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(DIVIDE(_WY_ACTIVE_CUST, _WY_LY_ACTIVE_CUST, \"-\"))",
              "        , 0",
              "        , DIVIDE(_WY_ACTIVE_CUST, _WY_LY_ACTIVE_CUST, \"-\")",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6b7746c2-56a1-46ec-b2b1-b47760202e76"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY ACTIVE CRT",
              "    VAR _WY_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_ACTIVE_CRT - _LY_ACTIVE_CRT), \"-\", _WY_ACTIVE_CRT - _LY_ACTIVE_CRT)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "d90d8015-d24f-47df-92b5-479f1508e861"
          },
          {
            "name": "@_UIO_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "    ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY UIO",
              "    VAR _WY_UIO = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _LY_UIO = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[result]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(DIVIDE(_WY_UIO, _LY_UIO, \"-\"))",
              "        , 0",
              "        , DIVIDE(_WY_UIO, _LY_UIO, \"-\")",
              "        )",
              ""
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "454448b9-7699-4815-8354-3a92e4c8d092"
          },
          {
            "name": "@_ACTIVE_CUST_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "    --WY",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_ACTIVE_CUST = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _TGT_ACTIVE_CUST = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[ACTIVE_CUST_RESULT]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(DIVIDE(_WY_ACTIVE_CUST, _TGT_ACTIVE_CUST, \"-\"))",
              "        , 0",
              "        , DIVIDE(_WY_ACTIVE_CUST, _TGT_ACTIVE_CUST, \"-\")",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e3c93525-e71d-4076-9507-76fd59fb25c2"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "    -- WY",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_ACTIVE_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _WY_TARGET =",
              "                        CALCULATE(",
              "                                AVERAGE('dms_svc_act8_cust_v'[vs_target]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Active Cust\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    ) / 100",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_ACTIVE_CRT - _WY_TARGET), \"-\", _WY_ACTIVE_CRT - _WY_TARGET)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "0f0cd810-0c4d-458d-865f-ba6e7b9a619d"
          },
          {
            "name": "@_RATIO_FMS_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "    ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "",
              "    VAR _WY_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_FMS = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"FMS\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_FMS - _TGT_RATIO_FMS), \"-\", _WY_RATIO_FMS - _TGT_RATIO_FMS)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "68c17c49-0601-4458-8997-daf8856e313d"
          },
          {
            "name": "@_RATIO_GR_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\" -- 8Y ago",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_GR = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"GR\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_GR - _TGT_RATIO_GR), \"-\", _WY_RATIO_GR - _TGT_RATIO_GR)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8f3f706c-c68d-46b9-bb06-5e79cf10f172"
          },
          {
            "name": "@_RATIO_OWN_CRT_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "    ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _WY_Own_Crt = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "    -- WY RATIO Own Crt",
              "    VAR _WY_TARGET =",
              "                        CALCULATE(",
              "                                AVERAGE('dms_svc_act8_cust_v'[vs_target]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    ) / 100",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_Own_Crt - _WY_TARGET), \"-\", _WY_Own_Crt - _WY_TARGET)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "dcd9cda5-cf75-4aa5-bcfb-a00aa844dad7"
          },
          {
            "name": "@_RATIO_PSP_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY PSP",
              "    VAR _WY_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _TGT_RATIO_PSP = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"PSP\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_RATIO_PSP - _TGT_RATIO_PSP), \"-\", _WY_RATIO_PSP - _TGT_RATIO_PSP)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8fd3e03d-67d1-4f0f-b947-7576b802d2a2"
          },
          {
            "name": "@_UIO_TGT_WY",
            "displayFolder": "WY_TARGET",
            "expression": [
              "",
              "    ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\"",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY UIO",
              "    VAR _WY_UIO = ",
              "                        CALCULATE(",
              "                                SUM('dms_svc_act8_cust_v'[result]),",
              "                                dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                        ALL('v_dim_calendar'),",
              "                                        v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                        && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                        )",
              "                                    )",
              "                                ",
              "    VAR _TGT_UIO = ",
              "                    CALCULATE(",
              "                            SUM('dms_svc_act8_cust_v'[vs_target]),",
              "                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                            FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                    )",
              "                                )",
              "                                ",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK(DIVIDE(_WY_UIO, _TGT_UIO, \"-\"))",
              "        , 0",
              "        , DIVIDE(_WY_UIO, _TGT_UIO, \"-\")",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "fe9bee5a-6a5e-42af-ab08-43e06c7166c0"
          },
          {
            "name": "@_RATIO_OWN_CRT_LY_WY",
            "displayFolder": "WY_LY",
            "expression": [
              "",
              "    ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _WY_From = \"2009-01\" -- 8Y ago",
              "    VAR _WY_To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR _LY_To = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    -- WY OWN CRT",
              "    VAR _WY_OWN_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _WY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "    VAR _LY_OWN_CRT = DIVIDE(",
              "                                CALCULATE(",
              "                                        SUM('dms_svc_act8_cust_v'[result]),",
              "                                        dms_svc_act8_cust_v[Category(New)] = \"Own Crt\",",
              "                                        FILTER(",
              "                                                ALL('v_dim_calendar'),",
              "                                                v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                             )",
              "                                            )",
              "                                , CALCULATE(",
              "                                            SUM('dms_svc_act8_cust_v'[result]),",
              "                                            dms_svc_act8_cust_v[Category(New)] = \"UIO\",",
              "                                            FILTER(",
              "                                                    ALL('v_dim_calendar'),",
              "                                                    v_dim_calendar[yyyy_mm] >= _WY_From",
              "                                                    && v_dim_calendar[yyyy_mm] <= _LY_To",
              "                                                    )",
              "                                            )",
              "                                )",
              "",
              "RETURN",
              "    if(ISBLANK(_WY_OWN_CRT - _LY_OWN_CRT), \"-\", _WY_OWN_CRT - _LY_OWN_CRT)"
            ],
            "formatString": "0.0%;-0.0%;0.0%",
            "lineageTag": "bb61adde-60f4-4a68-ae19-e333b9aecec3"
          },
          {
            "name": "@_Active_CRt_STAUTS_WY",
            "expression": [
              "",
              "IF([@_RATIO_ACTIVE_CRT_TGT_WY] >= 1 ",
              "    && [@_RATIO_ACTIVE_CRT_LY_WY] >= 1 ",
              ", \"1\", -- ",
              "",
              "IF([@_RATIO_ACTIVE_CRT_TGT_WY] <= 0.95",
              "    || [@_RATIO_ACTIVE_CRT_LY_WY] >= 0.95",
              ", \"0\" -- ",
              ", \"2\")) --"
            ],
            "lineageTag": "c5361f51-fb21-4a4b-96c1-57b8a46e2758"
          }
        ],
        "partitions": [
          {
            "name": "dms_svc_act8_cust_v",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_svc_act8_cust_v_View = dev_twice_Schema{[Name=\"dms_svc_act8_cust_v\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_svc_act8_cust_v_View, \" \", each if [category] = \"SVC_ACTIVE_CRT\" then \"Active CRt\" else if [category] = \"SVC_ACTIVE_CUST\" then \"Active Cust\" else if [category] = \"SVC_ACTIVE_FMS\" then \"FMS\" else if [category] = \"SVC_ACTIVE_GR\" then \"GR\" else if [category] = \"SVC_ACTIVE_PSP\" then \"PSP\" else if [category] = \"SVC_OWN_CRT\" then \"Own CRt\" else if [category] = \"SVC_UIO\" then \"UIO\" else null, type text),",
                "    #\"   \" = Table.RenameColumns(#\"  \",{{\" \", \"Category(New)\"}}),",
                "    #\"  1\" = Table.AddColumn(#\"   \", \" \", each if [category] = \"SVC_ACTIVE_CRT\" then 1 else if [category] = \"SVC_ACTIVE_CUST\" then 4 else if [category] = \"SVC_ACTIVE_FMS\" then 5 else if [category] = \"SVC_ACTIVE_GR\" then 7 else if [category] = \"SVC_ACTIVE_PSP\" then 6 else if [category] = \"SVC_OWN_CRT\" then 2 else if [category] = \"SVC_UIO\" then 3 else null, type number),",
                "    #\"   1\" = Table.RenameColumns(#\"  1\",{{\" \", \"Sort\"}}),",
                "    #\"   \" = Table.AddColumn(#\"   1\", \"yyyy_mm\", each Text.Combine({Text.Start([yyyymm], 4), \"-\", Text.Middle([yyyymm], 4)}), type text)",
                "in",
                "    #\"   \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_29db8caa-5b03-4937-bd1d-bbb566a4b65a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fd5bceb9-c861-4aca-a834-faf23f06ce04",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "ee282dff-1445-4dc9-981b-9dfa6373ea96",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ca82a75c-0d45-4b51-9e65-d3d48d6b84fe",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bc6ed41e-69cf-405c-987c-7f1c9e173ea8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "94a82194-9d98-46f7-982c-bd7de4bfd568",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8ead06b0-c814-466e-b9cd-fa3d8a4fc675",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d8367951-33f5-425d-b9b4-cfc189d04d53",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "e676f26d-0ded-40d0-bbb2-623b3998ff07",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "461898c9-f61b-4213-b401-c55511ed3e56",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "ebd4ae53-e34b-4692-92fb-46ee76ebddf9",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1420b44e-0244-46d9-85da-a95a16447328",
                "ordinal": 3
              }
            ],
            "lineageTag": "fd647707-c035-4040-b3ff-1138499a709f"
          }
        ],
        "isHidden": true,
        "lineageTag": "79183bdf-d150-44f6-bd44-466fcf3e8a7c",
        "partitions": [
          {
            "name": "LocalDateTable_29db8caa-5b03-4937-bd1d-bbb566a4b65a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[port_in_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[port_in_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_97123f9e-5cf6-41c7-b2ae-230ca5003e1b",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "be6b8f89-2192-47fb-8263-23cc8479696f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "95efccc5-5f77-427e-add7-d344f742f216",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c6a374f3-1e8c-4111-a6d1-42e0c8ae4429",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "c0e67d8f-32b7-424b-89d6-235c66c98c00",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "5fedda4e-4184-445a-bf80-166e104ffb3f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "846c4346-cc83-41d3-9223-0be89ad7efae",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f1935644-399d-4eb5-b761-f835ba08dcb8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "14fd13f1-28f8-47d7-bb8e-40b5dbd02639",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "bebc4175-5fb4-4b2e-81c8-145691dcec71",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9dc495aa-3485-460c-8c1b-79068f3bd5b7",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "faec62e6-fe7b-458b-b195-6997093361cf",
                "ordinal": 3
              }
            ],
            "lineageTag": "98eb6d18-dbbf-4404-9161-2d179714d281"
          }
        ],
        "isHidden": true,
        "lineageTag": "a7ec09e4-cf17-4fe0-9926-f2733fabbc25",
        "partitions": [
          {
            "name": "LocalDateTable_97123f9e-5cf6-41c7-b2ae-230ca5003e1b",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[retailsales_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[retailsales_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_9e8cebc1-50a2-4b3a-87c6-6c57886cc384",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "cf007a37-b2bc-480a-8774-e1ae3586546a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "4a7fa765-986c-4fd6-8dce-f6fefc816847",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0f60510c-6000-47e7-85af-0fe77d3a0ebc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0538a73a-7fa2-42d4-9538-5718a4c3baf0",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e8252b58-8108-4caf-a1ec-e78e06958794",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "3a9c2098-b37d-4a77-bffe-0f221e7114fe",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "108ec431-db74-4801-ba97-fdf9db6d7cf6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "7cbfec00-33d1-44b9-9fa0-7606b7b1df04",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "dc951d97-e37c-4678-93fc-c40d0cbbc7f1",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "c0ac8635-1ab4-4545-a3aa-04b48e92b3fa",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b04164fa-e7f1-4c15-963d-e7415ab9a4ab",
                "ordinal": 3
              }
            ],
            "lineageTag": "2f6471b6-6105-4d64-a807-372f329e743e"
          }
        ],
        "isHidden": true,
        "lineageTag": "745ef31b-ce74-4c75-9611-6076f12d862e",
        "partitions": [
          {
            "name": "LocalDateTable_9e8cebc1-50a2-4b3a-87c6-6c57886cc384",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[wholesales_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[wholesales_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_71db58b9-f4da-4303-866b-8e5fd6e08d3d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "32970056-2750-4413-8a44-227378c46063",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "38c74a5f-414d-438b-b86e-5d2f9b93563d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "aa18f9c0-4339-4cf1-84ce-6de2ae6e030d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b8e5ba34-361c-4d3f-8f21-52d2fb7a9756",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0d7be498-3cd8-4ace-a009-53c1ffc0e0b0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "301bb6ff-c3dc-4ac8-b44b-07aa051607b5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c6d161b4-0187-4716-a714-3511c82415fb",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "7a78f16e-6416-40ee-a198-a57e974b5485",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "923916dd-87ed-4b14-971e-55cf5314d84b",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "59b11bcd-348b-4b8e-87e2-72cdc98de9a5",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "52fddb06-9cc2-4e8a-8c09-2b080dcd02f1",
                "ordinal": 3
              }
            ],
            "lineageTag": "a9dd2691-a7b1-4be2-be9c-bf58c1848467"
          }
        ],
        "isHidden": true,
        "lineageTag": "d2cb9c42-8752-46f7-95e6-6f63a2de07d1",
        "partitions": [
          {
            "name": "LocalDateTable_71db58b9-f4da-4303-866b-8e5fd6e08d3d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[loss_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[loss_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_97ae6b8d-eaa0-455f-b998-e8b739b50e9a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "3a9f292d-7785-402b-8eea-0608df64a0ff",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c1d49d21-d658-4ed6-bcf2-38ae74e28497",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0bfdfef5-14da-4d25-bffb-fb610ae57c14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "51759656-6fc6-470e-b6ce-ade6caacd2a6",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b9f4d5c5-f52a-4be3-9bf4-863148aa6f70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2664ae1f-ed7d-4dfc-8f95-8ccc59dc775e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "85245ee7-77a2-42b8-8efb-25eabf6cfcf5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "dd38a47f-91b7-47d5-998c-85371215c181",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "2d2de442-9eec-4c44-af7a-41e7aad76971",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "3e7f90b6-60ab-4c22-bcbc-3bc4369107cf",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "cc6f0588-3c7c-40fa-997a-a429bbe495eb",
                "ordinal": 3
              }
            ],
            "lineageTag": "536871e3-29e4-443c-a6df-589a33c32fff"
          }
        ],
        "isHidden": true,
        "lineageTag": "45b9de1e-8f52-4254-b17c-e71470d1b6f2",
        "partitions": [
          {
            "name": "LocalDateTable_97ae6b8d-eaa0-455f-b998-e8b739b50e9a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_vehic'[internal_dt])), 1, 1), Date(Year(MAX('dms_co_vehic'[internal_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "v_dim_calendar",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5a2f55c0-d9c1-4136-934a-903810c57a90",
            "sourceColumn": "date",
            "summarizeBy": "none"
          },
          {
            "name": "year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "fa2de380-5646-4173-ba6f-7d14ba3fc62b",
            "sourceColumn": "year",
            "summarizeBy": "sum"
          },
          {
            "name": "month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "4ee11d3d-b264-4365-8583-fb0488eb5d95",
            "sourceColumn": "month",
            "summarizeBy": "sum"
          },
          {
            "name": "day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "dataType": "double",
            "formatString": "0",
            "lineageTag": "896e1ee2-2118-40d7-812a-860d0295e864",
            "sourceColumn": "day",
            "summarizeBy": "sum"
          },
          {
            "name": "quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "72875973-833c-4b97-9abc-9ee0bbe4805f",
            "sourceColumn": "quarter",
            "summarizeBy": "sum"
          },
          {
            "name": "month_eng",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "7a4cbdef-a82b-4bc5-afc6-e812f7dedf10",
            "sortByColumn": "month",
            "sourceColumn": "month_eng",
            "summarizeBy": "none"
          },
          {
            "name": "yyyy_mm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bdb5ac0-6f4c-4063-aede-bd96fef7b7f3",
            "sourceColumn": "yyyy_mm",
            "summarizeBy": "none"
          },
          {
            "name": "weekend_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57b02686-8b21-4b82-b09d-cea9ea07683a",
            "sourceColumn": "weekend_yn",
            "summarizeBy": "none"
          },
          {
            "name": "MON_ENG_SHORT",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "LEFT(v_dim_calendar[month_eng], 3)",
            "isDataTypeInferred": true,
            "lineageTag": "194d6c9c-2b22-4ab0-a060-5dbe95cc63cb",
            "sortByColumn": "month",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "YYMM_EN",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RIGHT(v_dim_calendar[year], 2) & \"' \" & LEFT(v_dim_calendar[month_eng], 3)",
            "isDataTypeInferred": true,
            "lineageTag": "c5da6ee1-4ebb-4e34-8e6d-4db8f3d54ed2",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "8d71227f-aee7-43fd-a53e-731a0d91f6e4",
        "measures": [
          {
            "name": "DATE_BOX",
            "expression": [
              "",
              "SELECTEDVALUE(v_dim_calendar[yyyy_mm])"
            ],
            "lineageTag": "276bfff2-739e-4954-8124-12ef3d6cb128"
          }
        ],
        "partitions": [
          {
            "name": "v_dim_calendar",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_calendar_View = dev_twice_Schema{[Name=\"v_dim_calendar\",Kind=\"View\"]}[Data],",
                "    #\" \" = Table.TransformColumnTypes(v_dim_calendar_View,{{\"year\", Int64.Type}})",
                "in",
                "    #\" \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_dim_dealer",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8340a1dd-7d9f-4f8d-8db5-9943f3b91f3f",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ef3eec6-318c-4679-9ea1-2177ca3f1c16",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11cba6e9-0f9f-45a3-a7a1-0074426f2248",
            "sourceColumn": "dealer_name",
            "summarizeBy": "none"
          },
          {
            "name": "use_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4ebae391-961f-4be6-813b-d9c370fe36c5",
            "sourceColumn": "use_yn",
            "summarizeBy": "none"
          },
          {
            "name": "dspy_rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "f395ab08-b92d-4279-8908-bd99a9a42193",
            "sourceColumn": "dspy_rank",
            "summarizeBy": "sum"
          },
          {
            "name": "eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1d0579f9-562d-4a93-9dc7-7fb2f6d24b20",
            "sourceColumn": "eng_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "888864dd-df04-4165-8d59-ba742c14da52",
        "partitions": [
          {
            "name": "v_dim_dealer",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_dealer_View = dev_twice_Schema{[Name=\"v_dim_dealer\",Kind=\"View\"]}[Data]",
                "in",
                "    v_dim_dealer_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_fact_dealer_sales_target",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e8468e8b-468f-4952-b572-aef9e24d6d34",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4125dd0c-c065-4548-9a7a-4ee88491d1ef",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "00dc3f81-929a-4b84-a1b0-2fb173cb6a70",
            "sourceColumn": "value",
            "summarizeBy": "sum"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "9fb38c78-0d0c-42dd-b070-105f6648dabf",
            "sortByColumn": "category_ord",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "category_ord",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d3981712-2abf-4544-9984-300136fde259",
            "sourceColumn": "category_ord",
            "summarizeBy": "sum"
          },
          {
            "name": "dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5c450740-6b84-45c8-8fc4-c520d3ba9d0f",
            "sourceColumn": "dt",
            "summarizeBy": "none"
          },
          {
            "name": "target_value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "b3c5a490-1985-4800-8a87-33d7762e7509",
            "sourceColumn": "target_value",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "5742a81d-39f4-44a6-ad4a-ee2ffeb21ead",
        "measures": [
          {
            "name": "@_BP_DLR_STATUS",
            "expression": [
              "",
              "IF(",
              "    [@_RATIO_BPS_YTD_TARGET] >= 1 && [@_RATIO_BPUS_YTD_TARGET] >= 1 && [@_RATIO_BP_Unit_Price_TARGET] >= 1",
              "    , \"1\", -- ",
              "IF(",
              "    [@_RATIO_BPS_YTD_TARGET] <= 0.95 || [@_RATIO_BPUS_YTD_TARGET] <= 0.95 || [@_RATIO_BP_Unit_Price_TARGET] <= 0.95",
              "    , \"0\" -- ",
              ", \"2\" --  )",
              "))"
            ],
            "lineageTag": "02ce196b-f18d-43d5-abb6-9c1445e181e5"
          },
          {
            "name": "@_GS_ENTRY_STATUS",
            "expression": [
              "",
              "IF([@_RATIO_CPUS_TARGET] >= 1 ",
              "                        && [@_RATIO_CPS_TARGET] >= 1 , \"1\", -- ",
              "                                                            IF([@_RATIO_CPUS_TARGET] <= 0.95 ",
              "                                                                || [@_RATIO_CPS_TARGET] <= 0.95, \"0\" -- ",
              "            , \"2\" --  )",
              "))"
            ],
            "lineageTag": "ec747e12-63d0-44a9-b4f2-1c95052c99e2"
          },
          {
            "name": "@_BPS",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3_BPS",
            "expression": [
              "CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        )"
            ],
            "lineageTag": "e7350286-b048-4bf6-a7cd-945b9228e813"
          },
          {
            "name": "@_BPS_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "formatString": "#,0",
            "lineageTag": "4644e913-7134-487b-84d9-f6a8ab29c878"
          },
          {
            "name": "@_BPS_YTD_LY",
            "displayFolder": "3_BPS",
            "expression": [
              "CALCULATE(",
              "                [@_BPS_YTD]",
              "                , DATEADD('v_dim_calendar'[date], -1, YEAR)",
              "                )"
            ],
            "lineageTag": "42ff92b8-a70c-44d0-a0bd-a39af39ed52b"
          },
          {
            "name": "@_BPS_YTD_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value]) / 1000000",
              "                        , DATESYTD('v_dim_calendar'[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value]) / 1000000",
              "                        , DATESYTD('v_dim_calendar'[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "lineageTag": "371d29ca-95da-4750-b61f-7c50c171c67d"
          },
          {
            "name": "@_RATIO_BPS_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR _Jan_Total = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            )",
              "",
              "VAR _Jan_Target = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            )",
              "",
              "VAR _BPS_TOTAL = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )",
              "",
              "VAR _BPS_TARGET = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )                 ",
              "",
              "RETURN",
              "     IF(SELECTEDVALUE(v_dim_calendar[month]) = 1, DIVIDE(_Jan_Total, _Jan_Target, \"-\"), DIVIDE(_BPS_TOTAL, _BPS_TARGET, \"-\"))"
            ],
            "lineageTag": "f1b04778-d240-4734-9a27-26b698572d0e"
          },
          {
            "name": "@_RATIO_BPS_YTD_LY",
            "displayFolder": "3_BPS",
            "expression": "DIVIDE([@_BPS_YTD], [@_BPS_YTD_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "9259f625-8cf6-46ca-a03f-4d92774e9266"
          },
          {
            "name": "@_RATIO_BPS_YTD_TARGET",
            "displayFolder": "3_BPS",
            "expression": "DIVIDE([@_BPS_YTD], [@_BPS_YTD_TARGET], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "943d087a-4cf8-411d-993a-9320d0b7e2d2"
          },
          {
            "name": "@_BPUS_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "formatString": "#,0",
            "lineageTag": "04bd3068-2cc4-4019-81f9-da83c084df25"
          },
          {
            "name": "@_BPUS_YTD_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4_BPUS",
            "expression": [
              "CALCULATE(",
              "                [@_BPUS_YTD]",
              "                , DATEADD('v_dim_calendar'[date], -1, YEAR)",
              "                )"
            ],
            "lineageTag": "d68a29f7-ff80-4a44-8d6a-0dbd35de08ea"
          },
          {
            "name": "@_BPUS_YTD_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "lineageTag": "2d452aed-df7c-422d-a3c5-da85866149d6"
          },
          {
            "name": "@_RATIO_BPUS_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR _Jan_Total = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            )",
              "",
              "VAR _Jan_Target = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            )",
              "",
              "VAR _BPUS_TOTAL = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPUS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )",
              "",
              "VAR _BPUS_TARGET = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"BPUS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )                 ",
              "",
              "RETURN",
              "     IF(SELECTEDVALUE(v_dim_calendar[month]) = 1, DIVIDE(_Jan_Total, _Jan_Target, \"-\"), DIVIDE(_BPUS_TOTAL, _BPUS_TARGET, \"-\"))"
            ],
            "lineageTag": "58c5c1de-01b8-446b-adb9-d2105c26f8ef"
          },
          {
            "name": "@_RATIO_BPUS_YTD_LY",
            "displayFolder": "4_BPUS",
            "expression": "DIVIDE([@_BPUS_YTD], [@_BPUS_YTD_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "25e94eb6-ec0f-4f85-bd66-b0e27aaf36c5"
          },
          {
            "name": "@_RATIO_BPUS_YTD_TARGET",
            "displayFolder": "4_BPUS",
            "expression": "DIVIDE([@_BPUS_YTD], [@_BPUS_YTD_TARGET], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "d8965e29-d5fd-4535-8ffa-77231df81ef9"
          },
          {
            "name": "@_CPS_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "formatString": "#,0",
            "lineageTag": "214ddd1e-d09d-48e5-a4de-13b82592993e"
          },
          {
            "name": "@_CPS_YTD_LY",
            "displayFolder": "1_CPS",
            "expression": [
              "CALCULATE(",
              "                [@_CPS_YTD]",
              "                , DATEADD('v_dim_calendar'[date], -1, YEAR)",
              "                )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "9f2d7f2f-0e3c-4f35-8e0c-200dea490633"
          },
          {
            "name": "@_CPS_YTD_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "formatString": "#,0",
            "lineageTag": "b28baa8c-03bc-4bfc-9546-d7d896c3d591"
          },
          {
            "name": "@_RATIO_CPS_YTD_LY",
            "displayFolder": "1_CPS",
            "expression": "DIVIDE([@_CPS_YTD], [@_CPS_YTD_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f2cf43ed-b989-41f6-a5fa-44b0803a556f"
          },
          {
            "name": "@_RATIO_CPS_YTD_TARGET",
            "displayFolder": "1_CPS",
            "expression": "DIVIDE([@_CPS_YTD], [@_CPS_YTD_TARGET], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "80bfbdf2-9b6d-4ba9-b664-e49b83ed4aa6"
          },
          {
            "name": "@_CPUS_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "formatString": "#,0",
            "lineageTag": "9e49150d-b498-49fe-85f3-db08a30e695f"
          },
          {
            "name": "@_CPUS_YTD_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "2_CPUS",
            "expression": [
              "CALCULATE(",
              "                [@_CPUS_YTD]",
              "                , DATEADD('v_dim_calendar'[date], -1, YEAR)",
              "                )"
            ],
            "formatString": "0",
            "lineageTag": "b775debf-ef98-4a1b-8f8f-390254594f6b"
          },
          {
            "name": "@_CPUS_YTD_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[target_value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT), JAN, RESULT)"
            ],
            "lineageTag": "39e3d50a-2a61-4f16-927d-e93a4b233504"
          },
          {
            "name": "@_RATIO_CPUS_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR _Jan_Total = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            )",
              "",
              "VAR _Jan_Target = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            )",
              "",
              "VAR _CPUS_TOTAL = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPUS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )",
              "",
              "VAR _CPUS_TARGET = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPUS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )                 ",
              "",
              "RETURN",
              "     IF(SELECTEDVALUE(v_dim_calendar[month]) = 1, DIVIDE(_Jan_Total, _Jan_Target, \"-\"), DIVIDE(_CPUS_TOTAL, _CPUS_TARGET, \"-\"))"
            ],
            "lineageTag": "1168cdb3-8f7f-4b82-8302-ac1ec53f2f42"
          },
          {
            "name": "@_RATIO_CPUS_YTD_LY",
            "displayFolder": "2_CPUS",
            "expression": "DIVIDE([@_CPUS_YTD], [@_CPUS_YTD_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "316f6f08-b788-40d0-a626-b33937705317"
          },
          {
            "name": "@_RATIO_CPUS_YTD_TARGET",
            "displayFolder": "2_CPUS",
            "expression": "DIVIDE([@_CPUS_YTD], [@_CPUS_YTD_TARGET], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ecd0f78b-eec5-4ea3-9aba-5ee2b2aeb0bb"
          },
          {
            "name": "@_BP_Unit_Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "",
              "VAR _A =",
              "DIVIDE([@_BPS_YTD]",
              ",IF([@_BPS]=0, BLANK(), [@_BPUS_YTD])",
              ", BLANK())",
              "",
              "RETURN",
              "_A"
            ],
            "lineageTag": "67cb27dd-986c-45ab-b381-43d1db6da66d"
          },
          {
            "name": "@_BP_Unit_Price_LY",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "CALCULATE([@_BP_Unit_Price]",
              ",DATEADD('v_dim_calendar'[date], -1, YEAR))"
            ],
            "lineageTag": "11395cf8-a597-48bd-8147-fa48d7362984"
          },
          {
            "name": "@_BP_Unit_Price_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "    DIVIDE([@_BPS_YTD_TARGET], [@_BPUS_YTD_TARGET], \"-\")"
            ],
            "lineageTag": "0ab37bac-c53d-4cf5-8ebb-afff412a79c4"
          },
          {
            "name": "@_GS_Unit_Price",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "DIVIDE([@_CPS_YTD]",
              ",IF([@_CPS_YTD]=0, BLANK(), [@_CPUS_YTD])",
              ", BLANK())"
            ],
            "lineageTag": "78340a7a-072c-4293-aefc-eef6c15b16c5"
          },
          {
            "name": "@_GS_Unit_Price_LY",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "CALCULATE([@_GS_Unit_Price]",
              ",DATEADD('v_dim_calendar'[date], -1, YEAR))"
            ],
            "lineageTag": "068aeab7-427c-4f9e-8456-b81581b99347"
          },
          {
            "name": "@_GS_Unit_Price_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "    DIVIDE([@_CPS_YTD_TARGET], [@_CPUS_YTD_TARGET], \"-\")"
            ],
            "lineageTag": "41274340-d4b8-4cb8-9d76-647ed30ed413"
          },
          {
            "name": "@_RATIO_BP_Unit_Price_LY",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "DIVIDE([@_BP_Unit_Price]",
              ",IF([@_BP_Unit_Price]=0, BLANK(), [@_BP_Unit_Price_LY])",
              ", BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "c40df3cf-061f-4f15-ae15-d040da286347"
          },
          {
            "name": "@_RATIO_BP_Unit_Price_TARGET",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "DIVIDE([@_BP_Unit_Price]",
              ",IF([@_BP_Unit_Price]=0, BLANK(), [@_BP_Unit_Price_TARGET])",
              ", BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7bdc9f69-c498-4a28-9e39-058b091ab321"
          },
          {
            "name": "@_RATIO_GS_Unit_Price_LY",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "DIVIDE([@_GS_Unit_Price]",
              ",IF([@_GS_Unit_Price]=0, BLANK(), [@_GS_Unit_Price_LY])",
              ", BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2dfefd87-f14f-46e5-b788-d72a9607484a"
          },
          {
            "name": "@_RATIO_GS_Unit_Price_TARGET",
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "DIVIDE([@_GS_Unit_Price]",
              ",IF([@_GS_Unit_Price]=0, BLANK(), [@_GS_Unit_Price_TARGET])",
              ", BLANK())"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a781e32d-fde4-4776-b50e-54e59ffe89b0"
          },
          {
            "name": "@_RATIO_TARGET_CPUS",
            "displayFolder": "5_Value",
            "expression": [
              "DIVIDE(",
              "                            CALCULATE([@_VALUE], v_fact_dealer_sales_target[category] = \"CPUS\")",
              "                            , CALCULATE([@_TARGET], v_fact_dealer_sales_target[category] = \"CPUS\")",
              "                            , \"-\"",
              "                            )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "096c3236-a31e-4820-aeea-d3a0428fc79c"
          },
          {
            "name": "@_RATIO_YTD_LY",
            "displayFolder": "5_Value",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([@_VALUE_YTD]) || ISBLANK([@_VALUE_YTD_LY]),",
              "    0,",
              "    DIVIDE([@_VALUE_YTD], [@_VALUE_YTD_LY], \"-\")",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "69444da4-af05-4772-a1d3-f0383105ce21"
          },
          {
            "name": "@_RATIO_YTD_TARGET",
            "displayFolder": "5_Value",
            "expression": [
              "",
              "IF(",
              "    ISBLANK([@_VALUE_YTD]) || ISBLANK([@_TARGET_YTD]),",
              "    0,",
              "    DIVIDE([@_VALUE_YTD], [@_TARGET_YTD], \"-\")",
              ")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b5ae2882-a464-42ac-b2a3-b231512c1a2d"
          },
          {
            "name": "@_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[target_value])",
              "                                )",
              "                    )"
            ],
            "lineageTag": "9e703cb7-f034-49d6-806e-f4e8ee8004cb"
          },
          {
            "name": "@_TARGET_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "",
              "var _Jan = CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[target_value])",
              "                                )",
              "                    )",
              "",
              "var _Result = CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[target_value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[target_value])",
              "                                ),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "                    )",
              "",
              "RETURN",
              "    IF(SELECTEDVALUE(v_dim_calendar[month]) = 1, _Jan, _Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "df991ef6-038e-4a0d-8a5c-9b0f3df37e39"
          },
          {
            "name": "@_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[value])",
              "                                )",
              "                    )"
            ],
            "formatString": "#,0",
            "lineageTag": "9667d4e7-1d60-4614-a7c2-9fea32686b79"
          },
          {
            "name": "@_VALUE_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "CALCULATE(",
              "                        [@_VALUE]",
              "                        , DATEADD(v_dim_calendar[date], -1, YEAR)",
              "                        )"
            ],
            "lineageTag": "acb099e9-ba86-46a4-b97b-6965e3b2c3c8"
          },
          {
            "name": "@_VALUE_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "",
              "var _Jan = CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[value])",
              "                                )",
              "                    )",
              "var _Result = CALCULATE(",
              "                        SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"CPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_dealer_sales_target'[category]) = \"BPS\", SUM('v_fact_dealer_sales_target'[value]) / 1000000,",
              "                                SUM('v_fact_dealer_sales_target'[value])",
              "                                ),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "                    )",
              "",
              "RETURN",
              "    if(SELECTEDVALUE(v_dim_calendar[month]) = 1, _Jan, _Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "ba8a6000-53b8-487b-89a6-722000742873"
          },
          {
            "name": "@_VALUE_YTD_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "5_Value",
            "expression": [
              "CALCULATE(",
              "                        [@_VALUE_YTD]",
              "                        , DATEADD(v_dim_calendar[date], -1, YEAR)",
              "                        )"
            ],
            "formatString": "0",
            "lineageTag": "f8c946ec-ae31-47a2-bc5b-154532260a87"
          },
          {
            "name": "@_CPS_YTD_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "VAR CNT = DISTINCTCOUNT(v_fact_dealer_sales_target[dealer_id])",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT / CNT), JAN / CNT, RESULT / CNT)"
            ],
            "formatString": "#,0",
            "lineageTag": "b3b7d50e-5074-4921-9233-1e4db3622c14"
          },
          {
            "name": "@_CPUS_YTD_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "VAR CNT = DISTINCTCOUNT(v_fact_dealer_sales_target[dealer_id])",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT / CNT), JAN / CNT, RESULT / CNT)"
            ],
            "formatString": "#,0",
            "lineageTag": "bc294bfc-174c-4441-a910-a0308f99ecd8"
          },
          {
            "name": "@_BPS_YTD_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "VAR CNT = DISTINCTCOUNT(v_fact_dealer_sales_target[dealer_id])",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value]) / 1000000",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT / CNT), JAN / CNT, RESULT / CNT)"
            ],
            "formatString": "#,0",
            "lineageTag": "d0445be8-42da-497d-937a-b2879c5e7524"
          },
          {
            "name": "@_BPUS_YTD_AVG",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MM = MAX('v_dim_calendar'[date]) //   ",
              "VAR YY = YEAR(MM) //    ",
              "VAR PM = EOMONTH(MM, -1) + 1 //   1 1",
              "VAR CNT = DISTINCTCOUNT(v_fact_dealer_sales_target[dealer_id])",
              "",
              "VAR JAN = ",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        )",
              "",
              "VAR RESULT =",
              "            CALCULATE(SUM(v_fact_dealer_sales_target[value])",
              "                        , DATESYTD(v_dim_calendar[date])",
              "                        , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                        , v_fact_dealer_sales_target[dt] < PM",
              "                        )",
              " RETURN",
              "    IF(ISBLANK(RESULT / CNT), JAN / CNT, RESULT / CNT)"
            ],
            "formatString": "#,0",
            "lineageTag": "9541eeb5-07fe-4238-a141-a0bbc6a0ea05"
          },
          {
            "name": "@_RATIO_13M_CPS_TARGET",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2485d8d6-eefb-44c5-a1b3-a89bcece4380"
          },
          {
            "name": "@_RATIO_13M_CPS_LY",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6708e7f4-1b98-4aa6-b76b-3e993be0c2d8"
          },
          {
            "name": "@_RATIO_14M_CPS_TARGET",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6909d5c9-78a7-43a6-b299-dc9a83f1d1af"
          },
          {
            "name": "@_RATIO_15M_CPS_TARGET",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "ce0c6ae2-6229-4fb4-b420-6903476973b1"
          },
          {
            "name": "@_RATIO_14M_CPS_LY",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "05d66632-952f-4725-8ccb-ccb011cd036f"
          },
          {
            "name": "@_RATIO_15M_CPS_LY",
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPS, _CPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3307ad09-bfd3-443a-adf4-eed6b62e17b6"
          },
          {
            "name": "@_RATIO_13M_CPUS_LY",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "dd55be19-9695-4293-91d8-7bede8796afe"
          },
          {
            "name": "@_RATIO_13M_CPUS_TARGET",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b9f28f24-5310-4167-a5b9-ca18da956f1a"
          },
          {
            "name": "@_RATIO_14M_CPUS_LY",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6685b0f1-ea50-496c-a2ef-537a7b1af70e"
          },
          {
            "name": "@_RATIO_14M_CPUS_TARGET",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "51a04072-5ffc-4f37-ab0f-925ea0cec5c6"
          },
          {
            "name": "@_RATIO_15M_CPUS_LY",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "def9670a-a8c5-437e-97d5-9bbc7504fd5d"
          },
          {
            "name": "@_RATIO_15M_CPUS_TARGET",
            "displayFolder": "2_CPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _CPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _CPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_CPUS, _CPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "6c82494f-3364-4cb2-a23c-ed17d87108c0"
          },
          {
            "name": "@_RATIO_13M_BPS_LY",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "791a976b-d7c2-4f25-9dbd-c2036a67767c"
          },
          {
            "name": "@_RATIO_13M_BPS_TARGET",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "eb3319e0-646c-480f-b0bb-7989f8401ce8"
          },
          {
            "name": "@_RATIO_14M_BPS_LY",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "a1ad3273-3c8e-4f89-a115-dd5c83603a57"
          },
          {
            "name": "@_RATIO_14M_BPS_TARGET",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0577394c-ade0-4261-9c83-704f19b3eb14"
          },
          {
            "name": "@_RATIO_15M_BPS_LY",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "da4fcd6c-3aec-49b1-b64b-e9119f32c29e"
          },
          {
            "name": "@_RATIO_15M_BPS_TARGET",
            "displayFolder": "3_BPS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPS, _BPS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "bcb0f5ba-334f-41d8-a4ea-3cba030dab22"
          },
          {
            "name": "@_RATIO_13M_BPUS_LY",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0ae54963-7e40-41a5-a54e-4f674fe8ffb3"
          },
          {
            "name": "@_RATIO_13M_BPUS_TARGET",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "7266578c-2465-412f-918e-68fbc99a6190"
          },
          {
            "name": "@_RATIO_14M_BPUS_LY",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "8777862f-5b78-4084-b7ba-578300cca4e8"
          },
          {
            "name": "@_RATIO_14M_BPUS_TARGET",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "272304c7-d300-450c-85de-c9fa79c39edc"
          },
          {
            "name": "@_RATIO_15M_BPUS_LY",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_LY = ",
              "                CALCULATE(",
              "                            [@_VALUE_LY]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_LY, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "4b537f15-43d0-4051-914f-9b59b5c38d6d"
          },
          {
            "name": "@_RATIO_15M_BPUS_TARGET",
            "displayFolder": "4_BPUS",
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )          ",
              "",
              "VAR _BPUS = ",
              "                CALCULATE(",
              "                            [@_VALUE]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "                            )",
              "",
              "",
              "VAR _BPUS_TARGET = ",
              "                CALCULATE(",
              "                            [@_TARGET]",
              "                            , v_fact_dealer_sales_target[category] = \"BPUS\"",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //  ",
              "                            )",
              "",
              "RETURN",
              "    DIVIDE(_BPUS, _BPUS_TARGET, \"-\")"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "2bc3db6f-c8fa-4e94-991e-47fea24c7c4a"
          },
          {
            "name": "@_BP_Unit_Price(1K)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "[@_BP_Unit_Price] * 1000"
            ],
            "formatString": "#,0",
            "lineageTag": "ea72b7e9-4dc9-4450-90d4-32b61e48afc0"
          },
          {
            "name": "@_GS_Unit_Price(1K)",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "6_Unit Price",
            "expression": [
              "",
              "[@_GS_Unit_Price] * 1000"
            ],
            "formatString": "#,0",
            "lineageTag": "caecacc8-c845-4b00-a336-cbf0e870c5fd"
          },
          {
            "name": "@_BP_ENTRY_STATUS",
            "expression": [
              "",
              "IF([@_RATIO_BPUS_TARGET] >= 1 && [@_RATIO_BPS_TARGET] >= 1 , \"1\", -- ",
              "            IF([@_RATIO_BPUS_TARGET] <= 0.95 || [@_RATIO_BPS_TARGET] <= 0.95 , \"0\" -- ",
              "            , \"2\" --  )",
              "))"
            ],
            "lineageTag": "bc1eb718-4e43-4f7e-bab2-ebc3e1d738ba"
          },
          {
            "name": "@_GS_DLR_STATUS",
            "expression": [
              "",
              "IF(",
              "    [@_RATIO_CPS_YTD_TARGET] >= 1 && [@_RATIO_CPUS_YTD_TARGET] >= 1 && [@_RATIO_GS_Unit_Price_TARGET] >= 1 ",
              "    , \"1\", -- ",
              "IF(",
              "    [@_RATIO_CPS_YTD_TARGET] <= 0.95 || [@_RATIO_CPUS_YTD_TARGET] <= 0.95 || [@_RATIO_GS_Unit_Price_TARGET] <= 0.95",
              "    , \"0\" -- ",
              ", \"2\" --  )",
              "))"
            ],
            "lineageTag": "54931d89-8dad-4f72-a947-35a272190054"
          },
          {
            "name": "@_RATIO_CPS_TARGET",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "1_CPS",
            "expression": [
              "",
              "VAR _Jan_Total = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            )",
              "",
              "VAR _Jan_Target = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPS\"",
              "                            )",
              "",
              "VAR _CPS_TOTAL = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )",
              "",
              "VAR _CPS_TARGET = CALCULATE(",
              "                    SUM('v_fact_dealer_sales_target'[target_value]),",
              "                    v_fact_dealer_sales_target[category] = \"CPS\",",
              "                    FILTER(",
              "                        ALL('v_dim_calendar'),",
              "                        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                    )",
              "                )                 ",
              "",
              "RETURN",
              "     IF(SELECTEDVALUE(v_dim_calendar[month]) = 1, DIVIDE(_Jan_Total, _Jan_Target, \"-\"), DIVIDE(_CPS_TOTAL, _CPS_TARGET, \"-\"))"
            ],
            "lineageTag": "10100f93-5544-4169-9c00-7033f3ab234b"
          },
          {
            "name": "@_DLR_STATUS",
            "expression": [
              "IF(",
              "                [@_RATIO_CPS_TARGET] >= 1 && [@_RATIO_CPUS_TARGET] >= 1 && [@_RATIO_BPS_TARGET] >= 1 && [@_RATIO_BPUS_TARGET] >= 1 , \"1\", -- ",
              "                        IF(",
              "                            [@_RATIO_CPS_TARGET] <= 0.95 || [@_RATIO_CPUS_TARGET] <= 0.95 || [@_RATIO_BPS_TARGET] <= 0.95 || [@_RATIO_BPUS_TARGET] <= 0.95",
              "                            , \"0\" -- ",
              "                , \"2\" --  )",
              "                            )",
              "                )"
            ],
            "lineageTag": "c8ebb6d3-f908-49d4-a0cd-28995426dfd9"
          },
          {
            "name": "@_RATIO_LY",
            "displayFolder": "5_Value",
            "expression": "DIVIDE([@_VALUE], [@_VALUE_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ff1facaa-4a0a-4814-a983-80bf6cbb8800"
          },
          {
            "name": "@_RATIO_TARGET_BPUS",
            "displayFolder": "5_Value",
            "expression": [
              "DIVIDE(",
              "                            CALCULATE([@_VALUE], v_fact_dealer_sales_target[category] = \"BPUS\")",
              "                            , CALCULATE([@_TARGET], v_fact_dealer_sales_target[category] = \"BPUS\")",
              "                            , \"-\"",
              "                            )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "586efc36-9ac1-49eb-9025-7b78bfdf9e25"
          },
          {
            "name": "@_RATIO_TARGET",
            "displayFolder": "5_Value",
            "expression": "DIVIDE([@_VALUE], [@_TARGET], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "ebdcfa06-b36d-4b5e-98b3-27c05aa87865"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_dealer_sales_target",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_dealer_sales_target_View = dev_twice_Schema{[Name=\"v_fact_dealer_sales_target\",Kind=\"View\"]}[Data]",
                "in",
                "    v_fact_dealer_sales_target_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_fact_svc_type_detail",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          }
        ],
        "columns": [
          {
            "name": "dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "38f044f1-7775-4123-a376-08e28c94d950",
            "sourceColumn": "dt",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "122d01aa-9f91-4a3c-8024-fc39a43dc88d",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "kpi_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b5975a2b-9ca5-437f-b84b-5602ebf7827f",
            "sourceColumn": "kpi_category",
            "summarizeBy": "none"
          },
          {
            "name": "kpi_detail_category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4fd56435-ba5f-49dd-a25c-b83307caee44",
            "sortByColumn": "Sort",
            "sourceColumn": "kpi_detail_category",
            "summarizeBy": "none"
          },
          {
            "name": "value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "389ac52d-33c5-4c83-a7a0-deafa4f097ba",
            "sourceColumn": "value",
            "summarizeBy": "sum"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a299e34b-3779-49c0-994e-3e573ee04be9",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "FORMAT([dt], \"yyyy-mm\")",
            "isDataTypeInferred": true,
            "lineageTag": "ee06e58d-1660-400f-af2e-0ae4f8324fea",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "11285a94-3099-4925-9104-434214589b4f",
        "measures": [
          {
            "name": "@_DLR_VALUE_YTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _A =",
              "CALCULATE(",
              "    SWITCH(",
              "            TRUE(),",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SUM('v_fact_svc_type_detail'[value])",
              "            ),",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "        [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "     )",
              ")",
              "",
              "VAR _JAN = ",
              "CALCULATE(",
              "    SWITCH(",
              "            TRUE(),",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SUM('v_fact_svc_type_detail'[value])",
              "            )",
              ")",
              "",
              "RETURN",
              "IF(ISBLANK(_A), _JAN, _A)"
            ],
            "formatString": "#,0",
            "lineageTag": "882f6f6a-2163-4557-8543-bedad327156d"
          },
          {
            "name": "@_DLR_VALUE_YTD_LY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "CALCULATE([@_DLR_VALUE_YTD], DATEADD(v_dim_calendar[date], -1, YEAR))",
              "                    "
            ],
            "formatString": "#,0",
            "lineageTag": "29b22383-8b25-414f-b2e3-eb780cc0787f"
          },
          {
            "name": "@_RATIO_DLR_YTD_LY",
            "expression": "DIVIDE(v_fact_svc_type_detail[@_DLR_VALUE_YTD], v_fact_svc_type_detail[@_DLR_VALUE_YTD_LY], \"-\")",
            "formatString": "0%;-0%;0%",
            "lineageTag": "f4c5d695-92d7-457e-b4ac-489a61a1e032"
          },
          {
            "name": "@_13M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -14,",
              "                MONTH",
              "            )              ",
              "",
              "VAR _Result = ",
              "                CALCULATE(",
              "                           SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SUM('v_fact_svc_type_detail'[value])",
              "                                )",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                            )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "8bc5b7f6-5da7-4730-b9dd-594cde5f5f8e"
          },
          {
            "name": "@_14M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -15,",
              "                MONTH",
              "            )              ",
              "",
              "VAR _Result = ",
              "                CALCULATE(",
              "                           SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SUM('v_fact_svc_type_detail'[value])",
              "                                )",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                            )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "5c81f646-814d-4fdd-b922-644a24609527"
          },
          {
            "name": "@_15M",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "VAR _FROM = ",
              "            DATESINPERIOD(",
              "                previous_date[date],",
              "                MaxDate,",
              "                -16,",
              "                MONTH",
              "            )              ",
              "",
              "VAR _Result = ",
              "                CALCULATE(",
              "                           SWITCH(",
              "                                TRUE(),",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "                                SUM('v_fact_svc_type_detail'[value])",
              "                                )",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                            )",
              "RETURN",
              "   _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "3344828c-3751-49df-b1e1-80ce0399c0b0"
          },
          {
            "name": "@_Lexus_%_YTD",
            "expression": [
              "",
              "var _var1 =",
              "                    CALCULATE([@_DLR_VALUE_YTD]",
              "                        , FILTER('v_dim_calendar', [yyyy_mm] In VALUES(v_fact_svc_type_detail[yyyymm]))",
              "                        , FILTER('v_dim_dealer_l', [eng_name] In VALUES(v_dim_dealer[eng_name])",
              "                                || [dms_brand_cd] In VALUES(v_dim_dealer[dms_brand_cd]))",
              "                        , ALLEXCEPT(v_fact_svc_type_detail, 'v_fact_svc_type_detail'[kpi_category]))",
              "",
              "RETURN",
              "    DIVIDE([@_DLR_VALUE_YTD], _var1, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "77bcf639-3738-4373-bb4c-3cc2b012baac"
          },
          {
            "name": "@_Lexus_%_YTD_LY",
            "expression": [
              "",
              "",
              "var _var1 = ",
              "",
              "CALCULATE([@_DLR_VALUE_YTD_LY]",
              "    , FILTER('v_dim_calendar', [yyyy_mm] In VALUES(v_fact_svc_type_detail[yyyymm]))",
              "    , FILTER('v_dim_dealer_l', [eng_name] In VALUES(v_dim_dealer[eng_name])",
              "    || [dms_brand_cd] In VALUES(v_dim_dealer[dms_brand_cd]))",
              "    , ALLEXCEPT(v_fact_svc_type_detail, 'v_fact_svc_type_detail'[kpi_category]))",
              "",
              "RETURN",
              "    DIVIDE([@_DLR_VALUE_YTD_LY], _var1, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "5d24d8f3-8add-4085-9e0f-d423237685ee"
          },
          {
            "name": "@_Toyota_%_YTD_LY",
            "expression": [
              "",
              "var _var1 =",
              "                    CALCULATE([@_DLR_VALUE_YTD_LY]",
              "                        , FILTER('v_dim_calendar', [yyyy_mm] In VALUES(v_fact_svc_type_detail[yyyymm]))",
              "                        , FILTER('v_dim_dealer_t', [eng_name] In VALUES(v_dim_dealer[eng_name])",
              "                                || [dms_brand_cd] In VALUES(v_dim_dealer[dms_brand_cd]))",
              "                        , ALLEXCEPT(v_fact_svc_type_detail, 'v_fact_svc_type_detail'[kpi_category]))",
              "",
              "RETURN",
              "    DIVIDE([@_DLR_VALUE_YTD_LY], _var1, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "f45e290e-754e-4291-920c-5cf3633f0fc4"
          },
          {
            "name": "@_Toyota_%_YTD",
            "expression": [
              "",
              "var _var1 =",
              "                    CALCULATE([@_DLR_VALUE_YTD]",
              "                        , FILTER('v_dim_calendar', [yyyy_mm] In VALUES(v_fact_svc_type_detail[yyyymm]))",
              "                        , FILTER('v_dim_dealer_t', [eng_name] In VALUES(v_dim_dealer[eng_name])",
              "                                || [dms_brand_cd] In VALUES(v_dim_dealer[dms_brand_cd]))",
              "                        , ALLEXCEPT(v_fact_svc_type_detail, 'v_fact_svc_type_detail'[kpi_category]))",
              "",
              "RETURN",
              "    DIVIDE([@_DLR_VALUE_YTD], _var1, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "0dc685d2-67ed-4693-90f9-0e40831cbb1b"
          },
          {
            "name": "@_Toyota_%_YTD2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "var _var1 =",
              "                    CALCULATE([@_DLR_VALUE]",
              "                        // , FILTER('v_dim_calendar', [yyyy_mm] In VALUES(v_fact_svc_type_detail[yyyymm]))",
              "                        // , FILTER('v_dim_dealer_t', [eng_name] In VALUES(v_dim_dealer[eng_name])",
              "                        //         || [dms_brand_cd] In VALUES(v_dim_dealer[dms_brand_cd]))",
              "                        // , ALLEXCEPT(v_fact_svc_type_detail, 'v_fact_svc_type_detail'[kpi_category])",
              "                        )",
              "",
              "RETURN",
              "    _var1",
              "    -- DIVIDE([@_DLR_VALUE], _var1, 0)"
            ],
            "lineageTag": "874ef9cb-5115-42b4-b06e-3462b02ce132"
          },
          {
            "name": "@_DLR_VALUE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE(",
              "    SWITCH(",
              "            TRUE(),",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"CPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SELECTEDVALUE('v_fact_svc_type_detail'[kpi_category]) = \"BPS\", SUM('v_fact_svc_type_detail'[value]) / 1000000,",
              "            SUM('v_fact_svc_type_detail'[value])",
              "            )",
              ")"
            ],
            "lineageTag": "0864a446-3721-4613-9cfd-c0cf3a935ac6"
          },
          {
            "name": "temp",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "    VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "    VAR _FROM = ",
              "                DATESINPERIOD(",
              "                    previous_date[date],",
              "                    MaxDate,",
              "                    -14,",
              "                    MONTH",
              "                )              ",
              "",
              "VAR _Result = ",
              "                CALCULATE(",
              "                           [@_DLR_VALUE]",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                            )",
              "",
              "RETURN",
              "    _Result",
              "",
              "//     DIVIDE([@_DLR_VALUE], _var1, 0)       ",
              "",
              "// VAR _CPUS = ",
              "//                 CALCULATE(",
              "//                             [@_VALUE]",
              "//                             , v_fact_dealer_sales_target[category] = \"CPUS\"",
              "//                             , REMOVEFILTERS(v_dim_calendar)",
              "//                             , KEEPFILTERS(_FROM)",
              "//                             , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "//                             , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear) //   ",
              "//                             )",
              "",
              "",
              "// RETURN",
              "//     DIVIDE([@_DLR_VALUE], _var1, 0)   "
            ],
            "lineageTag": "1a26ce24-6133-4e55-b0dd-1c5a5b0f285a"
          },
          {
            "name": "temp2",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "    VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "    VAR _FROM = ",
              "                DATESINPERIOD(",
              "                    previous_date[date],",
              "                    MaxDate,",
              "                    -14,",
              "                    MONTH",
              "                )              ",
              "",
              "VAR _Result = ",
              "                CALCULATE(",
              "                           [@_DLR_VALUE]",
              "                            , REMOVEFILTERS(v_dim_calendar)",
              "                            , KEEPFILTERS(_FROM)",
              "                            , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                            , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                            , ALLSELECTED(v_fact_svc_type_detail[Sort], v_fact_svc_type_detail[kpi_detail_category])",
              "                            )",
              "",
              "RETURN",
              "    _Result"
            ],
            "lineageTag": "d3a440f0-44a7-4649-abe2-777ea30e9534"
          },
          {
            "name": "@_13M_RATIO",
            "expression": [
              "",
              "",
              "    VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "    VAR _FROM = ",
              "                DATESINPERIOD(",
              "                    previous_date[date],",
              "                    MaxDate,",
              "                    -14,",
              "                    MONTH",
              "                )              ",
              "",
              "    VAR _num = ",
              "                    CALCULATE(",
              "                            [@_DLR_VALUE]",
              "                                , REMOVEFILTERS(v_dim_calendar)",
              "                                , KEEPFILTERS(_FROM)",
              "                                , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                                , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                                )",
              "",
              "    VAR _denom = ",
              "                    CALCULATE(",
              "                            [@_DLR_VALUE]",
              "                                , REMOVEFILTERS(v_dim_calendar)",
              "                                , KEEPFILTERS(_FROM)",
              "                                , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                                , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                                , ALLSELECTED(v_fact_svc_type_detail[Sort], v_fact_svc_type_detail[kpi_detail_category])",
              "                                )",
              "",
              "RETURN",
              "    DIVIDE(_num, _denom, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b5b9173b-9b24-4989-9efb-c5ae06de2ae2"
          },
          {
            "name": "@_15M_RATIO",
            "expression": [
              "",
              "",
              "    VAR MaxDate = MAX('v_dim_calendar'[date]) //    ",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month]) //  ",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "",
              "    VAR _FROM = ",
              "                DATESINPERIOD(",
              "                    previous_date[date],",
              "                    MaxDate,",
              "                    -16,",
              "                    MONTH",
              "                )              ",
              "",
              "    VAR _num = ",
              "                    CALCULATE(",
              "                            [@_DLR_VALUE]",
              "                                , REMOVEFILTERS(v_dim_calendar)",
              "                                , KEEPFILTERS(_FROM)",
              "                                , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                                , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                                )",
              "",
              "    VAR _denom = ",
              "                    CALCULATE(",
              "                            [@_DLR_VALUE]",
              "                                , REMOVEFILTERS(v_dim_calendar)",
              "                                , KEEPFILTERS(_FROM)",
              "                                , USERELATIONSHIP(v_dim_calendar[date], previous_date[date])",
              "                                , NOT('v_dim_calendar'[month] = SelectedMonth && 'v_dim_calendar'[year] = SelectedYear)//   ",
              "                                , ALLSELECTED(v_fact_svc_type_detail[Sort], v_fact_svc_type_detail[kpi_detail_category])",
              "                                )",
              "",
              "RETURN",
              "    DIVIDE(_num, _denom, 0)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "31fdd956-cb63-4cae-81e0-a7f1f9f2292d"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_svc_type_detail",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_svc_type_detail_View = dev_twice_Schema{[Name=\"v_fact_svc_type_detail\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(v_fact_svc_type_detail_View, \"Sort\"",
                "    , each if [kpi_detail_category] = \"HEAVY\" then 3",
                "    else if [kpi_detail_category] = \"MEDIUM\" then 2",
                "    else if [kpi_detail_category] = \"LIGHT\" then 1",
                "    else if [kpi_detail_category] = \"FMS\" then 4",
                "    else if [kpi_detail_category] = \"PSP\" then 5 ",
                "    else if [kpi_detail_category] = \"GR\" then 6 else null, type number)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_dim_dealer_l",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bd063943-4441-4c20-b0f2-79f5cc82a7a7",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "183adbd4-aa2d-42df-8f2c-cf617089fc7c",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "28ddbe07-3110-49f7-b557-85f477b0ae80",
            "sourceColumn": "dealer_name",
            "summarizeBy": "none"
          },
          {
            "name": "use_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8537ddb1-418b-412d-bab1-86ce5b86aa9d",
            "sourceColumn": "use_yn",
            "summarizeBy": "none"
          },
          {
            "name": "dspy_rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "7ec2be79-47b8-4b62-b2f3-7c6a064d9222",
            "sourceColumn": "dspy_rank",
            "summarizeBy": "sum"
          },
          {
            "name": "eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "497576d6-a124-4115-a687-1f4fc44c003f",
            "sortByColumn": "dspy_rank",
            "sourceColumn": "eng_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "74cf3897-76e8-4a64-8c7c-d760b6ed3238",
        "partitions": [
          {
            "name": "v_dim_dealer_l",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_dealer_l_View = dev_twice_Schema{[Name=\"v_dim_dealer_l\",Kind=\"View\"]}[Data]",
                "in",
                "    v_dim_dealer_l_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_dim_dealer_t",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aaf2e408-1a15-4004-8f8d-7921bc63f135",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "877f2dd3-1402-4524-a315-7c24640ba7d7",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9724ad79-dc33-4c39-9614-733eae00f045",
            "sourceColumn": "dealer_name",
            "summarizeBy": "none"
          },
          {
            "name": "use_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "388d4658-114e-4f9c-8313-0d25fa5b903f",
            "sourceColumn": "use_yn",
            "summarizeBy": "none"
          },
          {
            "name": "dspy_rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "30488bd7-96a2-4742-873e-c0088c92dfd2",
            "sourceColumn": "dspy_rank",
            "summarizeBy": "sum"
          },
          {
            "name": "eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "0223d26c-666c-4888-83d8-376c0852e6fa",
            "sortByColumn": "dspy_rank",
            "sourceColumn": "eng_name",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d309206e-0fab-4bb6-8912-db893dc41927",
        "partitions": [
          {
            "name": "v_dim_dealer_t",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_dealer_t_View = dev_twice_Schema{[Name=\"v_dim_dealer_t\",Kind=\"View\"]}[Data]",
                "in",
                "    v_dim_dealer_t_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_dim_group",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3ad65a90-8a92-43af-932a-281ceb1489f0",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4e90d430-221c-401e-98f5-1f0829e13585",
            "sourceColumn": "group_name",
            "summarizeBy": "none"
          },
          {
            "name": "group_eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "4bd2715a-42f1-4c12-b88c-f28c6e1c8d92",
            "sortByColumn": "sort",
            "sourceColumn": "group_eng_name",
            "summarizeBy": "none"
          },
          {
            "name": "group_name(New)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d3a2a7c4-38db-4594-b48a-077419066d5c",
            "sourceColumn": "group_name(New)",
            "summarizeBy": "none"
          },
          {
            "name": "sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ddc5b5ed-fb92-4567-beb9-2d87d09023f0",
            "sourceColumn": "sort",
            "summarizeBy": "sum"
          },
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "46861adf-b71e-4a22-b9a7-eba6facd2865",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e0dbbe2a-4ffe-434d-93b3-7bd34c6bf2d8",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "cbdbf6dc-2ce8-4501-9b42-ef8390049615",
        "partitions": [
          {
            "name": "v_dim_group",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_group_View = dev_twice_Schema{[Name=\"v_dim_group\",Kind=\"View\"]}[Data],",
                "    #\"   \" = Table.AddColumn(v_dim_group_View, \"group_name(New)\", each ",
                "        let",
                "            replacements = {{\"\", \"\"}, {\"\", \"\"}, {\"\", \"\"}, {\"\", \"\"}},",
                "            replacedText = List.Accumulate(replacements, [group_name], (state, replacement) => Text.Replace(state, replacement{0}, replacement{1}))",
                "        in",
                "            Text.Trim(replacedText)",
                "    ),",
                " ",
                "    #\"  \" = Table.AddColumn(#\"   \", \"sort\"",
                "    , each if [group_eng_name] = \"YS\" then 3 ",
                "    else if [group_eng_name] = \"GN\" then 1 ",
                "    else if [group_eng_name] = \"BS\" then 5 ",
                "    else if [group_eng_name] = \"DG\" then 6 ",
                "    else if [group_eng_name] = \"BD\" then 4 ",
                "    else if [group_eng_name] = \"GJ\" then 7 ",
                "    else if [group_eng_name] = \"DJ\" then 8 ",
                "    else if [group_eng_name] = \"SC\" then 2 ",
                "    else if [group_eng_name] = \"IC\" then 2 ",
                "    else null, type number)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_a42184ff-f71f-4dd8-ab72-d572295cb8e6",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "766549bb-6ea1-4ec5-aab2-af111cf0cd57",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "734b536c-43e2-4751-95b9-48f4b063346e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9390e352-9496-4d93-816e-51c15125d39d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "76e5f296-9552-4a0a-be9c-382d4f6666d3",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9147f3bb-ea4f-42ce-9d37-58d00846649b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c0629930-7c58-4cc6-8015-3fddc34b4e27",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bfbae070-0f10-49c3-8962-34e38915eca7",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "716e6b11-56da-4071-aaf6-fbe714d73a31",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "22b8aabb-b7ab-4d65-8548-d371dc52618c",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "7a867b53-5f67-4e89-b323-3434b2085543",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1b00d5e2-caf5-460b-8a67-cec8de160785",
                "ordinal": 3
              }
            ],
            "lineageTag": "2112c612-e3c6-4fb7-b6f2-f8641e68dfbe"
          }
        ],
        "isHidden": true,
        "lineageTag": "01f20e8c-0608-4684-8a64-ae89a767e1cc",
        "partitions": [
          {
            "name": "LocalDateTable_a42184ff-f71f-4dd8-ab72-d572295cb8e6",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('previous_date'[date])), 1, 1), Date(Year(MAX('previous_date'[date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_svc_act8_cust_retail_year_v",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d2fe46d2-3f64-458b-9918-b7ea7ef30f7c",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b90a7bd6-56bb-4579-a9ce-a04ae5282468",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de0a8f76-5314-4e4a-b1ec-483d6bdc9785",
            "sourceColumn": "group_eng_name",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "07b8c14a-2c29-47e1-b044-840c13efafec",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "11a2019a-c7fd-4a39-89bf-efdec79ebd8b",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "retail_year_interval",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3a0df3b3-f1f7-4e7e-b913-a95de6f75b2e",
            "sourceColumn": "retail_year_interval",
            "summarizeBy": "none"
          },
          {
            "name": "result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "int64",
            "lineageTag": "57724595-a5d0-4425-b765-fe4d90e48b66",
            "sourceColumn": "result",
            "summarizeBy": "sum"
          },
          {
            "name": "Category(New)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "1ce06d52-65e7-430d-9d13-bf4c0fc36e43",
            "sortByColumn": "Sort",
            "sourceColumn": "Category(New)",
            "summarizeBy": "none"
          },
          {
            "name": "Sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2ff45b88-3f8b-4c8a-b76c-36d99975f1e2",
            "sourceColumn": "Sort",
            "summarizeBy": "sum"
          },
          {
            "name": "Time_Series",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ec0698a7-e74e-4266-a409-221a3ddd60dc",
            "sourceColumn": "Time_Series",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "                LEFT('dms_svc_act8_cust_retail_year_v'[yyyymm], 4), // '2023'   ",
              "                MID('dms_svc_act8_cust_retail_year_v'[yyyymm], 5, 2), // '01'   ",
              "                1 // (day) 1       ",
              "            )"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "0ec4be0f-84fc-4830-9c24-df4861063fa2",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "denominator",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE(",
              "            DISTINCT(dms_svc_act8_cust_retail_year_v[result]),",
              "            FILTER(",
              "                    dms_svc_act8_cust_retail_year_v,",
              "                    dms_svc_act8_cust_retail_year_v[Category(New)] = \"Active Cust\" ",
              "                    && dms_svc_act8_cust_retail_year_v[yyyymm] = EARLIER(dms_svc_act8_cust_retail_year_v[yyyymm])",
              "                    && dms_svc_act8_cust_retail_year_v[dealer_id] = EARLIER(dms_svc_act8_cust_retail_year_v[dealer_id])",
              "                    && dms_svc_act8_cust_retail_year_v[Time_Series] = EARLIER(dms_svc_act8_cust_retail_year_v[Time_Series])",
              "                )",
              "            )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "acacf83c-aaa5-4bbb-b0d8-b99a511a19ee",
            "summarizeBy": "sum",
            "type": "calculated"
          },
          {
            "name": "denominator_uio",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "expression": [
              "",
              "CALCULATE(",
              "            SUM(dms_svc_act8_cust_retail_year_v[result]),",
              "            FILTER(",
              "                    dms_svc_act8_cust_retail_year_v,",
              "                    dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\" ",
              "                    && dms_svc_act8_cust_retail_year_v[yyyymm] = EARLIER(dms_svc_act8_cust_retail_year_v[yyyymm])",
              "                    && dms_svc_act8_cust_retail_year_v[dealer_id] = EARLIER(dms_svc_act8_cust_retail_year_v[dealer_id])",
              "                    && dms_svc_act8_cust_retail_year_v[Time_Series] = EARLIER(dms_svc_act8_cust_retail_year_v[Time_Series])",
              "                )",
              "            )"
            ],
            "formatString": "0",
            "isDataTypeInferred": true,
            "lineageTag": "594fb2d1-b97c-4162-96eb-f3b73c3a6c11",
            "summarizeBy": "sum",
            "type": "calculated"
          }
        ],
        "lineageTag": "db64426c-ff6a-46dd-afd6-29e4dbd18554",
        "measures": [
          {
            "name": "@_VehicleAge_AT_YTD_LM",
            "expression": [
              "",
              "VAR _DEALER_AT = CALCULATE(",
              "    SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "     'dms_svc_act8_cust_retail_year_v'[Category(New)] = \"ACTIVE CRT\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO = CALCULATE(",
              "    SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "     'dms_svc_act8_cust_retail_year_v'[Category(New)] = \"UIO\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_UIO_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "     'dms_svc_act8_cust_retail_year_v'[Category(New)] = \"UIO\")",
              "",
              "VAR _DEALER_AC = CALCULATE(",
              "    SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "     'dms_svc_act8_cust_retail_year_v'[Category(New)] = \"ACTIVE CUST\",",
              "    FILTER(",
              "        ALL('v_dim_calendar'),",
              "         [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "        && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "    )",
              ")",
              "",
              "VAR _DEALER_AC_Jan = CALCULATE(",
              "    SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "     'dms_svc_act8_cust_retail_year_v'[Category(New)] = \"ACTIVE CUST\")",
              "",
              "",
              "VAR _TOTAL =",
              "IF(ISBLANK(DIVIDE(_DEALER_AC,_DEALER_UIO,\"-\")), DIVIDE(_DEALER_AC_Jan,_DEALER_UIO_Jan,\"-\"), DIVIDE(_DEALER_AC,_DEALER_UIO,\"-\"))",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), \"-\", _TOTAL)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "e596216f-57ca-4f17-b80b-ecb5e9b50bba"
          },
          {
            "name": "T_Dealer_Box",
            "expression": [
              "",
              "IF(ISBLANK(",
              "    SELECTEDVALUE(v_dim_dealer_t[eng_name]))",
              "    , \"NA\"",
              "    ,  SELECTEDVALUE(v_dim_dealer_t[eng_name]))"
            ],
            "lineageTag": "ab60e741-eab7-456f-aa77-dfdb2c6a8f65"
          },
          {
            "name": "L_Dealer_Box",
            "expression": [
              "",
              "IF(ISBLANK(",
              "    SELECTEDVALUE(v_dim_dealer_l[eng_name]))",
              "    , \"NA\"",
              "    ,  SELECTEDVALUE(v_dim_dealer_l[eng_name]))"
            ],
            "lineageTag": "7886a148-5308-4ef6-be48-302c4b538117"
          },
          {
            "name": "@_AT_YTD_LY",
            "expression": [
              "",
              "CALCULATE([@_VehicleAge_AT_YTD_LM],DATEADD(v_dim_calendar[date], -1, YEAR))"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "109fb856-ab34-4bfb-8448-6e5d86cd55b7"
          },
          {
            "name": "@_RESULT_YTD",
            "expression": [
              "",
              "var _Jan = SUM('dms_svc_act8_cust_retail_year_v'[result])",
              "                       ",
              "var _result = CALCULATE(",
              "                        SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "                    )",
              "",
              "RETURN",
              "    if(SELECTEDVALUE(v_dim_calendar[month]) = 1, _Jan, _result)"
            ],
            "formatString": "0",
            "lineageTag": "f06020f4-5d4a-48f5-9428-5d30a3bde4de"
          },
          {
            "name": "@_CRT_RATIO",
            "expression": [
              "DIVIDE(",
              "                [@_RESULT_YTD]",
              "                , [@_DENOMINATOR_YTD]",
              "                , 0",
              "                )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "5cbf7b8d-f9af-4c7d-b557-b0778c566721"
          },
          {
            "name": "@_DENOMINATOR_YTD",
            "expression": [
              "",
              "var _Jan = SUM('dms_svc_act8_cust_retail_year_v'[denominator])",
              "                       ",
              "var _result = CALCULATE(",
              "                        SUM('dms_svc_act8_cust_retail_year_v'[denominator]),",
              "                        FILTER(",
              "                            ALL('v_dim_calendar'),",
              "                            [Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && [Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "                    )",
              "",
              "RETURN",
              "    if(SELECTEDVALUE(v_dim_calendar[month]) = 1, _Jan, _result)"
            ],
            "formatString": "0",
            "lineageTag": "e1e2d2fc-0470-44fc-9e9b-292fe6ac8011"
          },
          {
            "name": "@_CRt_8Y_RESULT_YR",
            "displayFolder": "8Y",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                    v_dim_calendar[yyyy_mm] >= _From",
              "                    && v_dim_calendar[yyyy_mm] <= _To",
              "                    )",
              "            )"
            ],
            "formatString": "#,0",
            "lineageTag": "401d8b7e-98de-4181-933a-f41a07001c0a"
          },
          {
            "name": "@_RATIO_CRT_FMS_del",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_8Y_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"FMS\")",
              "         , CALCULATE([@_CRt_8Y_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "74a9bcab-9ce1-4f06-8aa6-9791cc49267e"
          },
          {
            "name": "@_RATIO_CRT_PSP_del",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_8Y_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"PSP\")",
              "         , CALCULATE([@_CRt_8Y_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "35dfa04f-b168-48b3-9946-e547626a5b2e"
          },
          {
            "name": "@_RATIO_CRT_GR_del",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_8Y_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"GR\")",
              "         , CALCULATE([@_CRt_8Y_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "455ac4e0-6640-40a8-aaaf-b2fd86aeabb1"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_YR",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_8Y_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"ACTIVE CUST\")",
              "         , CALCULATE([@_CRt_8Y_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "60125cdb-ba3e-4cd5-9091-60c7c71abcb9"
          },
          {
            "name": "@_ACTIVE_CUST_VALUE",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR StartDate = DATE(SelectedYear - 1, SelectedMonth, 1)",
              "    VAR EndDate = DATE(SelectedYear, SelectedMonth, 1) - 1",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                dms_svc_act8_cust_retail_year_v[Category(New)] = \"ACTIVE CUST\",",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                    [Date] >= StartDate",
              "                    && [Date] <= EndDate",
              "                    )",
              "            )"
            ],
            "formatString": "0",
            "lineageTag": "68553f61-83cc-469f-8c34-5ba5e1cbd5e3"
          },
          {
            "name": "result_temp",
            "expression": "SUM('dms_svc_act8_cust_retail_year_v'[result])",
            "formatString": "0",
            "lineageTag": "31505e60-9de8-4e4f-9cf7-97c8091caa87"
          },
          {
            "name": "denom_temp",
            "expression": "SUM('dms_svc_act8_cust_retail_year_v'[denominator_uio])",
            "formatString": "0",
            "lineageTag": "966ef6dc-f5d8-41f1-ac5f-2930514873fb"
          },
          {
            "name": "@_CATEGORY_RATIO_8Y",
            "displayFolder": "8Y",
            "expression": "DIVIDE([@_CRt_8Y_RESULT_YR], [@_DENOM_UIO_8Y], 0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "2d037bb0-09d4-430a-8fb5-24075b328c8e"
          },
          {
            "name": "@_DENOM_UIO_8Y",
            "displayFolder": "8Y",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = FORMAT(DATE(SelectedYear, SelectedMonth -96, 1), \"yyyy-mm\") -- 8Y ago",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth, \"00\")",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[denominator_uio]),",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                    v_dim_calendar[yyyy_mm] >= _From",
              "                    && v_dim_calendar[yyyy_mm] <= _To",
              "                    )",
              "            )"
            ],
            "formatString": "0",
            "lineageTag": "44e41cb7-9fdd-4830-813b-a5a7ea6ea2a8"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_TR_LY",
            "expression": "CALCULATE([@_RATIO_ACTIVE_CRT_LY], DATEADD(v_dim_calendar[date], -1, YEAR))",
            "formatString": "0%;-0%;0%",
            "lineageTag": "2500d83a-37aa-4ef7-8c3e-d6aee8822628"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_8Y_YR",
            "displayFolder": "8Y",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_8Y_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"Active Cust\")",
              "         , CALCULATE([@_CRt_8Y_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3605c96b-546e-40ab-b8d0-0948dd59821d"
          },
          {
            "name": "@_RATIO_CRT_8Y_FMS_YR",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_retail_year_v[Category(New)] = \"FMS\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "37563ec1-8858-411d-a5f9-7afe7b238400"
          },
          {
            "name": "@_RATIO_CRT_8Y_GR_YR",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_retail_year_v[Category(New)] = \"GR\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "ec3453f2-c025-4155-81d1-1340348140b6"
          },
          {
            "name": "@_RATIO_CRT_8Y_PSP_YR",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_RESULT_8Y],dms_svc_act8_cust_retail_year_v[Category(New)] = \"PSP\")",
              "         , CALCULATE([@_CRt_RESULT_8Y], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "26067015-78c5-4667-ae2a-90d1a0ce9bed"
          },
          {
            "name": "@_Ratio_Active_CRt_LY_Trend_YR",
            "displayFolder": "8Y",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR StartDate = FORMAT(DATE(SelectedYear, SelectedMonth -108, 1), \"yyyy-mm\")",
              "    VAR EndDate = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR Active_Cust = CALCULATE(",
              "                                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                                dms_svc_act8_cust_retail_year_v[Category(New)] = \"ACTIVE CUST\",",
              "                                FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= StartDate",
              "                                    && v_dim_calendar[yyyy_mm] < EndDate",
              "                                    )",
              "                            )",
              "",
              "    VAR UIO = CALCULATE(",
              "                                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                                dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= StartDate",
              "                                    && v_dim_calendar[yyyy_mm] < EndDate",
              "                                    )",
              "                            )                            ",
              "",
              "RETURN",
              "   DIVIDE(Active_Cust, UIO)"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "3637d5c5-7946-4597-ad01-371ca31e3ae7"
          },
          {
            "name": "@_CRt_WY_RESULT",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth, \"00\")",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                     v_dim_calendar[yyyy_mm] >= \"2009-01\"",
              "                    && v_dim_calendar[yyyy_mm] <= _To",
              "                    )",
              "            )"
            ],
            "formatString": "#,0",
            "lineageTag": "a3885af4-fbd1-44fd-a5dd-629071cb1f2d"
          },
          {
            "name": "@_CRt_WY_RESULT_YR",
            "displayFolder": "WY",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = \"2009-01\"",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                    v_dim_calendar[yyyy_mm] >= _From",
              "                    && v_dim_calendar[yyyy_mm] <= _To",
              "                    )",
              "            )"
            ],
            "formatString": "#,0",
            "lineageTag": "8898eefc-560d-429c-8df3-836844ccc5b1"
          },
          {
            "name": "@_RATIO_ACTIVE_CRT_WY_YR",
            "displayFolder": "WY",
            "expression": [
              "",
              "DIVIDE(",
              "        CALCULATE([@_CRt_WY_RESULT_YR],dms_svc_act8_cust_retail_year_v[Category(New)] = \"Active Cust\")",
              "         , CALCULATE([@_CRt_WY_RESULT_YR], dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\")",
              "         , 0",
              "        )"
            ],
            "formatString": "0%;-0%;0%",
            "lineageTag": "b8baecd1-47f1-453c-9bed-e58876e951ec"
          },
          {
            "name": "@_Ratio_Active_CRt_LY_Trend_YR_WY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "displayFolder": "WY",
            "expression": [
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR StartDate = \"2009-01\"",
              "    VAR EndDate = FORMAT(SelectedYear -1, \"0000\") & \"-\" & FORMAT(SelectedMonth -1, \"00\")",
              "",
              "    VAR Active_Cust = CALCULATE(",
              "                                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                                dms_svc_act8_cust_retail_year_v[Category(New)] = \"ACTIVE CUST\",",
              "                                FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= StartDate",
              "                                    && v_dim_calendar[yyyy_mm] < EndDate",
              "                                    )",
              "                            )",
              "",
              "    VAR UIO = CALCULATE(",
              "                                SUM('dms_svc_act8_cust_retail_year_v'[result]),",
              "                                dms_svc_act8_cust_retail_year_v[Category(New)] = \"UIO\",",
              "                                FILTER(",
              "                                    ALL('v_dim_calendar'),",
              "                                    v_dim_calendar[yyyy_mm] >= StartDate",
              "                                    && v_dim_calendar[yyyy_mm] < EndDate",
              "                                    )",
              "                            )                            ",
              "",
              "RETURN",
              "   DIVIDE(Active_Cust, UIO)"
            ],
            "lineageTag": "fb6d6e2a-3676-4c42-a4af-db402da4b1c7"
          },
          {
            "name": "@_DENOM_UIO_WY",
            "displayFolder": "WY",
            "expression": [
              "",
              "",
              "    VAR SelectedYear = SELECTEDVALUE('v_dim_calendar'[year])",
              "    VAR SelectedMonth = SELECTEDVALUE('v_dim_calendar'[month])",
              "",
              "    VAR _From = \"2009-01\"",
              "    VAR _To = FORMAT(SelectedYear, \"0000\") & \"-\" & FORMAT(SelectedMonth, \"00\")",
              "",
              "RETURN",
              "    CALCULATE(",
              "                SUM('dms_svc_act8_cust_retail_year_v'[denominator_uio]),",
              "                FILTER(",
              "                    ALL('v_dim_calendar'),",
              "                    v_dim_calendar[yyyy_mm] >= _From",
              "                    && v_dim_calendar[yyyy_mm] <= _To",
              "                    )",
              "            )"
            ],
            "formatString": "0",
            "lineageTag": "fc2ca4be-2506-4464-a032-ea47b19e5f10"
          },
          {
            "name": "@_CATEGORY_RATIO_WY",
            "displayFolder": "WY",
            "expression": "DIVIDE([@_CRt_WY_RESULT_YR], [@_DENOM_UIO_WY], 0)",
            "formatString": "0%;-0%;0%",
            "lineageTag": "e332fe3e-0502-44a1-a8bc-b6823b1bece4"
          }
        ],
        "partitions": [
          {
            "name": "dms_svc_act8_cust_retail_year_v",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_svc_act8_cust_retail_year_v_View = dev_twice_Schema{[Name=\"dms_svc_act8_cust_retail_year_v\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_svc_act8_cust_retail_year_v_View, \"Category(New)\"",
                "    , each if [category] = \"SVC_ACTIVE_CRT\" then \"Active CRt\" ",
                "        else if [category] = \"SVC_ACTIVE_CUST\" then \"Active Cust\" ",
                "        else if [category] = \"SVC_ACTIVE_FMS\" then \"FMS\" ",
                "        else if [category] = \"SVC_ACTIVE_GR\" then \"GR\" ",
                "        else if [category] = \"SVC_ACTIVE_PSP\" then \"PSP\" ",
                "        else if [category] = \"SVC_OWN_CRT\" then \"Own CRt\" ",
                "        else if [category] = \"SVC_UIO\" then \"UIO\" ",
                "        else if [category] = \"SVC_ACTIVE_WT\" then \"Warranty\"",
                "        else null, type text),",
                "    #\"  1\" = Table.AddColumn(#\"  \", \"Sort\"",
                "    , each if [category] = \"SVC_ACTIVE_CRT\" then 1 ",
                "        else if [category] = \"SVC_OWN_CRT\" then 2 ",
                "        else if [category] = \"SVC_UIO\" then 3",
                "        else if [category] = \"SVC_ACTIVE_CUST\" then 4 ",
                "        else if [category] = \"SVC_ACTIVE_FMS\" then 5 ",
                "        else if [category] = \"SVC_ACTIVE_PSP\" then 6 ",
                "        else if [category] = \"SVC_ACTIVE_GR\" then 7 ",
                "        else if [category] = \"SVC_ACTIVE_WT\" then 8  ",
                "        else null, type number),",
                "    #\" \" = Table.TransformColumnTypes(#\"  1\",{{\"retail_year_interval\", type text}}),",
                "",
                "    #\"  \" = Table.AddColumn(#\" \", \"Time_Series\", each Text.Combine({[retail_year_interval], \"yr\"}), type text)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_fact_capa_kpi",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2c37938-16f8-45f8-82b9-c40e993fe04b",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "981ce728-0f28-4a31-984e-42fbc0da3ec6",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "886e0022-cc07-4669-aa67-97f8ff404e39",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "svc_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b9f8a068-26dc-49d4-aad9-500cf0c62cda",
            "sourceColumn": "svc_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "value",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "7bc8329e-39ab-4815-b980-0b2754d165ea",
            "sourceColumn": "value",
            "summarizeBy": "sum"
          },
          {
            "name": "working_day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d45fc5e6-0b15-4e18-a71e-65a112ed95a1",
            "sourceColumn": "working_day",
            "summarizeBy": "sum"
          },
          {
            "name": "us",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "392ccf28-ef3c-4966-a5ec-1a87e1c97ad6",
            "sourceColumn": "us",
            "summarizeBy": "sum"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "                LEFT('v_fact_capa_kpi'[yyyymm], 4), // '2023'   ",
              "                MID('v_fact_capa_kpi'[yyyymm], 5, 2), // '01'   ",
              "                1 // (day) 1       ",
              "            )"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "8505ec64-ef64-4276-8550-0c901378ecbc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8b9467c5-e8e8-4108-a0ba-a51eeb3db7b0",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "capa",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "88652ba2-06e0-471e-8172-80caaa78f3c9",
            "sourceColumn": "capa",
            "summarizeBy": "sum"
          },
          {
            "name": "MON_ENG_NAME_2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "expression": "SWITCH(RIGHT(v_fact_capa_kpi[yyyymm], 2), \"01\", \"JAN\", \"02\", \"FEB\", \"03\", \"MAR\", \"04\", \"APR\", \"05\", \"MAY\", \"06\", \"JUN\", \"07\", \"JUL\", \"08\", \"AUG\", \"09\", \"SEP\", \"10\", \"OCT\", \"11\", \"NOV\", \"12\", \"DEC\")",
            "isDataTypeInferred": true,
            "lineageTag": "8051ac6c-0323-4ca8-9494-9b0a52bf2c93",
            "sortByColumn": "MON_ORD",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MON_ORD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RIGHT(v_fact_capa_kpi[yyyymm], 2)",
            "isDataTypeInferred": true,
            "lineageTag": "8d1637b2-4f03-4837-8f6c-4721f611469e",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "926e1f59-d0c5-4ee1-a20e-125c02407380",
        "measures": [
          {
            "name": "#_GS_SA",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0.0",
            "lineageTag": "ebc8abc5-5302-4fbe-9ab0-2be95fdf2be3"
          },
          {
            "name": "#_GS_STALL",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0.0",
            "lineageTag": "4da96aab-d407-459c-aa8e-719d3b114603"
          },
          {
            "name": "#_GS_TECH",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0.0",
            "lineageTag": "0d6c368d-a0f4-469f-aaf9-cd722d2e390b"
          },
          {
            "name": "#_BP_SA",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)",
              ""
            ],
            "formatString": "0.0",
            "lineageTag": "7f887907-bfd4-4ee5-ade9-04f136dce1eb"
          },
          {
            "name": "#_BP_STALL",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0.0",
            "lineageTag": "74801ad5-f6be-45a0-8017-2c3b75954104"
          },
          {
            "name": "#_BP_TECH",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "",
              "VAR _B =",
              "DISTINCT(v_fact_capa_kpi[working_day])",
              "",
              "VAR _C = ",
              "CALCULATE(SUM(v_fact_capa_kpi[us])",
              ",v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "",
              "VAR _TOTAL = _C / (_A * _B)",
              "",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0.0",
            "lineageTag": "9cbca038-5eeb-46cf-922f-e5721c61b71a"
          },
          {
            "name": "#_No_GS_STALL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0",
            "lineageTag": "a8a2d128-432a-4581-826b-a1e134ea9f21"
          },
          {
            "name": "#_No_GS_SA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL =",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "_TOTAL"
            ],
            "lineageTag": "779ec5c6-4be0-4d09-b9e4-b989a9b9229f"
          },
          {
            "name": "#_No_GS_TECH",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL = CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0",
            "lineageTag": "6116fd24-d829-4815-a397-f4317ac96f7b"
          },
          {
            "name": "#_No_BP_SA",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL =",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0",
            "lineageTag": "1325f603-9c3d-4333-a8df-f2c05320917b"
          },
          {
            "name": "#_No_BP_STALL",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL = ",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0",
            "lineageTag": "4a1c3deb-cad8-49db-9041-f11b825146fd"
          },
          {
            "name": "#_No_BP_TECH",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "",
              "VAR _TOTAL =",
              "CALCULATE(SUM(v_fact_capa_kpi[value])",
              ", v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "",
              "VAR _LM = CALCULATE(_TOTAL, DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(ISBLANK(_TOTAL), 0, _TOTAL)"
            ],
            "formatString": "0",
            "lineageTag": "b48b9cea-d403-442e-bca1-3d2b474b4e79"
          },
          {
            "name": "#_GS_SA_LM",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE([#_GS_SA], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "99704015-6a11-4600-803b-455b89acc619"
          },
          {
            "name": "#_No_GS_SA_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_GS_SA], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "7b2e7b7d-e1fb-40eb-b7f7-38c4829ddf5b"
          },
          {
            "name": "#_No_GS_STALL_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_GS_STALL], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "b7eea902-d359-4d18-8c08-138e7e12bc6c"
          },
          {
            "name": "#_No_GS_TECH_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_GS_TECH], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "9298893d-c762-481e-ae5c-758325550c23"
          },
          {
            "name": "#_No_BP_SA_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_BP_SA], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "1145255e-77e9-4e01-9b07-41edbfff2c9a"
          },
          {
            "name": "#_No_BP_STALL_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_BP_STALL], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "f26cbe43-0165-4e6a-bb54-aa4eeb7649c8"
          },
          {
            "name": "#_No_BP_TECH_LM",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "expression": [
              "",
              "CALCULATE([#_No_BP_TECH], DATEADD(v_dim_calendar[date], -1, MONTH))"
            ],
            "formatString": "0",
            "lineageTag": "f169b644-fedb-454f-b922-31b35bfa1ba4"
          },
          {
            "name": "#_GS_STALL_LM",
            "expression": [
              "",
              "",
              "VAR _A =",
              "CALCULATE([#_GS_STALL], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "1fca7f47-5748-4c9d-9e5c-30adfd871928"
          },
          {
            "name": "#_GS_TECH_LM",
            "expression": [
              "",
              "VAR _A = ",
              "CALCULATE([#_GS_TECH], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "5fab1f85-82eb-4a51-9f47-b7d044e86ca6"
          },
          {
            "name": "#_BP_SA_LM",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE([#_BP_SA], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "2eb1545e-1fd9-45ec-b817-60ca8baa8e79"
          },
          {
            "name": "#_BP_STALL_LM",
            "expression": [
              "",
              "",
              "VAR _A = ",
              "CALCULATE([#_BP_STALL], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "406cb0ee-a1de-4032-85e6-193a864d593d"
          },
          {
            "name": "#_BP_TECH_LM",
            "expression": [
              "",
              "VAR _A = CALCULATE([#_BP_TECH], DATEADD(v_dim_calendar[date], -1, MONTH))",
              "",
              "RETURN",
              "IF(",
              "    ISERROR(_A) || ISBLANK(_A) || _A = BLANK()",
              "    , 0, _A",
              ")"
            ],
            "formatString": "0.0",
            "lineageTag": "c8587471-1ed2-4384-a2f3-65000fdfe96e"
          },
          {
            "name": "@_BP_SA_BAR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_SA\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "lineageTag": "ebe04cd1-8eb1-4ca8-992e-bffca64ba9e0"
          },
          {
            "name": "@_BP_SA_LINE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_SA\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "lineageTag": "af0b3a39-d4b3-4714-841b-4749d97ddf5e"
          },
          {
            "name": "@_BP_STALL_BAR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_STALL\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_STALL\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_STALL\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "lineageTag": "d6e3cb00-cc3f-4e64-ac9b-cf61bd668b28"
          },
          {
            "name": "@_BP_STALL_LINE",
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_STALL\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "formatString": "0.0",
            "lineageTag": "d0ebf0de-d42e-4787-96e7-2b974d9663c9"
          },
          {
            "name": "@_BP_TECH_BAR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_TECH\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_TECH\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_TECH\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "lineageTag": "a24d16d7-48da-4d35-9e59-ec72ec6a1c94"
          },
          {
            "name": "@_BP_TECH_LINE",
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_BP_TECH\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "formatString": "0.0",
            "lineageTag": "559dfddd-3a02-4caa-b01a-6c3d54a5f271"
          },
          {
            "name": "@_GS_SA_BAR",
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "formatString": "0.0",
            "lineageTag": "47ce73d7-af68-4705-b90a-43374ad74b20"
          },
          {
            "name": "@_GS_SA_LINE",
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_SA\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "formatString": "0.0",
            "lineageTag": "309564ec-062e-41ee-bebc-dbb7cda43355"
          },
          {
            "name": "@_GS_STALL_BAR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_STALL\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_STALL\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_STALL\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_STALL\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "lineageTag": "3baf3683-2a56-462f-b3e2-8a51e9b0c113"
          },
          {
            "name": "@_GS_STALL_LINE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_STALL\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "lineageTag": "fd7c4bcf-a309-46e0-af38-7f17cc3c0317"
          },
          {
            "name": "@_GS_TECH_BAR",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_TECH\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_TECH\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_TECH\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_TECH\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )                        "
            ],
            "lineageTag": "96c8f3f9-06e4-45c5-b6aa-8be306cad12e"
          },
          {
            "name": "@_GS_TECH_LINE",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _jan = CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                         ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "                /",
              "                (",
              "                (",
              "                CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "                )",
              "                *",
              "                DISTINCT(v_fact_capa_kpi[working_day])",
              "                )",
              "",
              "    var _result = CALCULATE( (CALCULATE(SUM(v_fact_capa_kpi[us])",
              "                                        ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "                            /",
              "                            (",
              "                                (",
              "                                    CALCULATE(SUM(v_fact_capa_kpi[value])",
              "                                             ,v_fact_capa_kpi[svc_kpi_code] = \"SVC_GS_TECH\")",
              "                                )",
              "                                *",
              "                                DISTINCT(v_fact_capa_kpi[working_day])",
              "                            ))",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )\t",
              "",
              "RETURN",
              "    if(SELECTEDVALUE('v_dim_calendar'[month]) = 1, _jan, _result) "
            ],
            "lineageTag": "fca95eed-60ea-4552-bdf1-1cb8dbb0c0bb"
          },
          {
            "name": "#_No_GS_SA_LM_AVG",
            "expression": [
              "",
              "    VAR _CNT = DISTINCTCOUNT(v_fact_capa_kpi[dealer_id]) ",
              "",
              "RETURN",
              "    CALCULATE([#_No_GS_SA], DATEADD(v_dim_calendar[date], -1, MONTH)) / _CNT"
            ],
            "formatString": "0.0",
            "lineageTag": "9d839830-72b2-45db-a0ec-e4c5f5001272"
          },
          {
            "name": "#_No_GS_STALL_LM_AVG",
            "expression": [
              "",
              "    VAR _CNT = DISTINCTCOUNT(v_fact_capa_kpi[dealer_id]) ",
              "",
              "RETURN",
              "    CALCULATE([#_No_GS_STALL], DATEADD(v_dim_calendar[date], -1, MONTH)) / _CNT"
            ],
            "formatString": "0.0",
            "lineageTag": "aa5f9982-eee6-4c94-9dbd-70216fd0d002"
          },
          {
            "name": "#_No_GS_TECH_LM_AVG",
            "expression": [
              "",
              "    VAR _CNT = DISTINCTCOUNT(v_fact_capa_kpi[dealer_id]) ",
              "",
              "RETURN",
              "    CALCULATE([#_No_GS_TECH], DATEADD(v_dim_calendar[date], -1, MONTH)) / _CNT"
            ],
            "formatString": "0.0",
            "lineageTag": "9f8166c6-29f2-4176-9fba-2bb205649c22"
          },
          {
            "name": "#_No_BP_SA_LM_AVG",
            "expression": [
              "",
              "CALCULATE([#_No_BP_SA], DATEADD(v_dim_calendar[date], -1, MONTH)) / DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])"
            ],
            "formatString": "0.0",
            "lineageTag": "113c79be-0b5b-4187-943b-d4bf6ed13c91"
          },
          {
            "name": "#_No_BP_STALL_LM_AVG",
            "expression": [
              "",
              "CALCULATE([#_No_BP_STALL], DATEADD(v_dim_calendar[date], -1, MONTH)) / DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])"
            ],
            "formatString": "0.0",
            "lineageTag": "ebfc4356-7a25-4591-96af-2e38bddaf29a"
          },
          {
            "name": "#_No_BP_TECH_LM_AVG",
            "expression": [
              "",
              "CALCULATE([#_No_BP_TECH], DATEADD(v_dim_calendar[date], -1, MONTH)) / DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])"
            ],
            "formatString": "0.0",
            "lineageTag": "88277007-021e-4a30-bd2d-ae3abccb7032"
          },
          {
            "name": "temppppp",
            "expression": [
              "",
              "    var _cnt_jan = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "",
              "    var _cnt_result = CALCULATE(",
              "                            DISTINCTCOUNT(v_fact_capa_kpi[dealer_id])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                            )                       ",
              "",
              "    var _jan = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            )",
              "    ",
              "    var _result = CALCULATE(",
              "                            SUM('v_fact_capa_kpi'[value])",
              "                            , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                            , ALL(v_dim_calendar),",
              "                            v_dim_calendar[Date] >= DATE(SELECTEDVALUE('v_dim_calendar'[year]), 1, 1)",
              "                            && v_dim_calendar[Date] <= EOMONTH(DATE(SELECTEDVALUE('v_dim_calendar'[year]), SELECTEDVALUE('v_dim_calendar'[month]), 1), -1)",
              "                        )",
              "",
              "RETURN",
              "    if(",
              "        SELECTEDVALUE('v_dim_calendar'[month]) = 1",
              "        , _jan / _cnt_jan",
              "         ,_result / _cnt_result",
              "        )"
            ],
            "formatString": "0",
            "lineageTag": "a65d9f77-60ea-44a0-926e-7d30d2e8bda9"
          },
          {
            "name": "@_GS_SA_BAR_PY",
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_SA\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "formatString": "0.0",
            "lineageTag": "0fb35ebe-f9df-4f70-a4b6-92c2e32978bb"
          },
          {
            "name": "@_GS_STALL_BAR_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_STALL\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "lineageTag": "90209244-0b7e-4d60-a347-2e4f4d5c2b0e"
          },
          {
            "name": "@_GS_TECH_BAR_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_GS_TECH\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "lineageTag": "575a5454-bc97-4012-81ed-46e5ba248e55"
          },
          {
            "name": "@_BP_SA_BAR_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_SA\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "lineageTag": "338de42f-b47a-4ecb-a0a9-c5a1226778fb"
          },
          {
            "name": "@_BP_STALL_BAR_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_STALL\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "lineageTag": "c40c2ffd-061f-4f6c-9ece-2238546f8a02"
          },
          {
            "name": "@_BP_TECH_BAR_PY",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "expression": [
              "",
              "    var _py_from = DATE(SELECTEDVALUE(v_dim_calendar[year]) -1 , 1, 1)",
              "    var _py_to = DATE(SELECTEDVALUE(v_dim_calendar[year]), 1, 1)",
              "",
              "RETURN",
              "     CALCULATE(",
              "                SUM('v_fact_capa_kpi'[value])",
              "                , 'v_fact_capa_kpi'[svc_kpi_code] = \"SVC_BP_TECH\"",
              "                , ALL(v_dim_calendar),",
              "                v_dim_calendar[Date] >= _py_from",
              "                && v_dim_calendar[Date] < _py_to",
              "                )",
              "                / 12"
            ],
            "lineageTag": "cfd40f7f-93bc-408e-aeae-e73a2ea747f8"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_capa_kpi",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_capa_kpi_View = dev_twice_Schema{[Name=\"v_fact_capa_kpi\",Kind=\"View\"]}[Data],",
                "    #\" \" = Table.ReplaceValue(v_fact_capa_kpi_View,null,0,Replacer.ReplaceValue,{\"capa\"})",
                "in",
                "    #\" \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_3414bbc0-0998-4b37-a847-3f8de40a0059",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "965aec3f-5b66-4e13-96b3-bf79f07779d7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "59d396c4-5c6a-43bc-a704-0f69b5097025",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "22c78bb1-64ba-49ef-8d47-7c926aafda70",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "4a5c566f-ade0-4208-8a88-34e6856732f8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "64b285a2-778c-4c05-83dd-ec98df2e7fa1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0e111bb5-d212-475a-8236-3330ab45b884",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2ff02c37-21a3-4204-b0b8-5f3f9a5f6d6d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "c25a38ea-5f5b-417c-86a6-42761bd25234",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "0ae900c8-a95b-4ec3-94a8-c6f6d2152a62",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "22e37bd7-3ea7-4374-8764-b2add81f9d52",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "157d049b-a83e-4e52-b3f4-eae0b8793731",
                "ordinal": 3
              }
            ],
            "lineageTag": "be6e2d65-a760-412e-87f1-083cf25fb0b9"
          }
        ],
        "isHidden": true,
        "lineageTag": "faa3f269-ea6c-4d13-892c-8de66e556312",
        "partitions": [
          {
            "name": "LocalDateTable_3414bbc0-0998-4b37-a847-3f8de40a0059",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_svc_ro'[ro_close_dt])), 1, 1), Date(Year(MAX('dms_svc_ro'[ro_close_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_co_variant_v",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "44ff1640-8238-4ed7-ae02-977732058d16",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7e88ba18-5ca8-434a-b76c-f60b68730318",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84293ec2-0171-46f1-acb6-6e24f8c2a530",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f5ea653d-be5e-44c3-8089-e8d964fda3cb",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2feb478-85cd-421f-b1e2-d09a49d38de9",
            "sourceColumn": "variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "display_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b83a3e46-03ef-4dfd-9106-cb46469e5e8a",
            "sourceColumn": "display_order",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2c1cbcd-c367-4f45-853d-9afe06bc7e41",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "502b51ed-3847-42ca-ae62-76432c47bedf",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "brand_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50ef90eb-3af8-4b8a-9e17-981e3d8592bd",
            "sourceColumn": "brand_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "brand_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32ce784d-d93f-412e-b2c5-73d6c39b364b",
            "sourceColumn": "brand_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eb2fc58a-dde6-43df-828a-229fe72b8297",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "230b8674-b5bf-4f1b-921b-736b0feab208",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "1d335b04-55c5-4724-9f99-99e1ab691949",
        "partitions": [
          {
            "name": "dms_co_variant_v",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_variant_v_View = dev_twice_Schema{[Name=\"dms_co_variant_v\",Kind=\"View\"]}[Data],",
                "    #\"  1\" = Table.AddColumn(dms_co_variant_v_View, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text),",
                "    #\"  2\" = Table.AddColumn(#\"  1\", \"b_report_variant_cd\", each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text)",
                "in",
                "    #\"  2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_sales_customer_traffic",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "180bbe35-eeb0-494f-bd5d-a6721ee510d3",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2bd9831-dc4c-4ea3-8ebe-4df3ebaf9704",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c0700cce-e72a-4626-a5d2-120327797e51",
            "sourceColumn": "seq",
            "summarizeBy": "sum"
          },
          {
            "name": "recept_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "6d1fdf59-ea61-4638-8b45-52f150edd594",
            "sourceColumn": "recept_dt",
            "summarizeBy": "none"
          },
          {
            "name": "active_knd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96d879ea-5dda-4e81-9a0d-0de3695fdd13",
            "sourceColumn": "active_knd",
            "summarizeBy": "none"
          },
          {
            "name": "active_knd_dtl",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa73033d-dde6-4520-ad06-ffe0ae0f5047",
            "sourceColumn": "active_knd_dtl",
            "summarizeBy": "none"
          },
          {
            "name": "concern_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bed2a21-aa59-4b92-8bad-ece2501d371e",
            "sourceColumn": "concern_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "concern_variant_cd2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83f18273-06cc-409e-96aa-5eb157f20fed",
            "sourceColumn": "concern_variant_cd2",
            "summarizeBy": "none"
          },
          {
            "name": "other_comp_brand",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d4b9cbfc-54b4-4f71-abb1-ff61ae74b61a",
            "sourceColumn": "other_comp_brand",
            "summarizeBy": "none"
          },
          {
            "name": "other_comp_model",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f607a6e8-a9d9-4c64-8fae-5fbefefd9d17",
            "sourceColumn": "other_comp_model",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "b0290a86-5d6e-4d95-9fbb-50c1cc29ed60",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_6212944b-4331-4157-8510-062bba0bba6d"
                },
                "isDefault": true,
                "relationship": "eda473ff-5482-4f7d-ad08-a68608835fe9"
              }
            ]
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d623fa8c-fd58-40a0-bb6f-b790df138fe1",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "10af78fe-8dd6-491e-99cd-825a9c000f61",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_a6ec5deb-3c10-4ee5-a1b0-adbf2364851a"
                },
                "isDefault": true,
                "relationship": "7521be78-7a97-472c-8111-efee9c3935cd"
              }
            ]
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4dcfafa1-8fdd-434b-a64d-fd8646566361",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "sex_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d22c194a-033d-4f7f-b222-2697bcda406f",
            "sourceColumn": "sex_cd",
            "summarizeBy": "none"
          },
          {
            "name": "age",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "91867b0b-2ad5-4f3c-b19b-b088a50be5c0",
            "sourceColumn": "age",
            "summarizeBy": "none"
          },
          {
            "name": "together_cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "32db6baa-da1f-4674-afa5-e402ea754810",
            "sourceColumn": "together_cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "together_rel",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c2814c67-8761-40ba-b85e-b5bdca4153c3",
            "sourceColumn": "together_rel",
            "summarizeBy": "none"
          },
          {
            "name": "cust_response",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ad27026f-c870-4f7b-83af-da7ceac1a686",
            "sourceColumn": "cust_response",
            "summarizeBy": "none"
          },
          {
            "name": "revisit_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a6e977fb-f5ea-4291-afb2-c8d253045710",
            "sourceColumn": "revisit_yn",
            "summarizeBy": "none"
          },
          {
            "name": "ex_cnt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "665538cc-268d-4c11-b38f-71ce6d79ef03",
            "sourceColumn": "ex_cnt",
            "summarizeBy": "sum"
          },
          {
            "name": "recept_st_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "41b7006a-de76-4827-a508-438523a0145f",
            "sourceColumn": "recept_st_dt",
            "summarizeBy": "none"
          },
          {
            "name": "recept_end_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3e1b5ea2-e73f-4b15-aee0-3365a9a1e309",
            "sourceColumn": "recept_end_dt",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2add0aea-981c-4478-92bd-0a4f38852197",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e910f510-6011-468a-a2ec-c1c4316c8186",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "17dbcfb0-7272-4f36-ad28-6ff60fa9c962",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "96bf509c-83ed-4e3d-a36f-4b24b158b07d",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "f3ea29fc-702d-49d1-8476-1319d195d2fa",
        "measures": [
          {
            "name": "#_Showroom_Blank_Filter",
            "displayFolder": "_Showroom",
            "expression": "IF([#_Contract_CurrentPace_MTD]=0&&[#_Sales_CurrentPace_MTD]=0&&[#_Showroom_Traffic(M)]=0&&[#_Showroom_TestDrive_MTD]=0,0,1)",
            "formatString": "0",
            "lineageTag": "63c85151-1209-4e26-812f-833fe27a0542"
          },
          {
            "name": "#_Contract_Ratio( )",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "divide([#_Contract_CurrentPace_MTD],[#_Showroom_TestDrive_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "adda75ea-5639-4b10-966a-ec2ddd9a136e"
          },
          {
            "name": "#_Sales_Ratio( )",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "divide([#_Sales_CurrentPace_MTD], [#_Contract_CurrentPace_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "a1af0417-9b47-4ad3-a438-173fd790f2c2"
          },
          {
            "name": "#_Showroom_TestDrive",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_testdrive')",
              "    , dms_sales_testdrive[use_type] =\"01\"",
              "    , dms_sales_testdrive[test_type] IN {\"01\",\"02\"}",
              "    , dms_sales_testdrive[interest_degree] IN {\"01\",\"02\",\"03\"})"
            ],
            "formatString": "#,0",
            "lineageTag": "ece16b13-9004-4195-8e02-d186cc9c4efe"
          },
          {
            "name": "#_Showroom_TestDrive_LM",
            "displayFolder": "_Showroom",
            "expression": "CALCULATE([#_Showroom_TestDrive],DATEADD('v_dim_calendar'[date],-1,MONTH))",
            "formatString": "#,0",
            "lineageTag": "0f8ae9ca-a3b7-4663-a47c-7008b42ea501"
          },
          {
            "name": "#_Showroom_TestDrive_MTD",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "",
              "VAR _Result = CALCULATE([#_Showroom_TestDrive],DATESMTD(v_dim_calendar[date]))",
              "",
              "RETURN",
              "    IF(ISBLANK(_Result),0,_Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "628fb71e-bb6e-43ad-a281-4839ff20afe3"
          },
          {
            "name": "#_Showroom_TestDrive(M)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(",
              "    COUNTROWS('dms_sales_testdrive')",
              "    , dms_sales_testdrive[use_type] =\"01\"",
              "    , dms_sales_testdrive[test_type] IN {\"01\",\"02\"}",
              "    , dms_sales_testdrive[interest_degree] IN {\"01\",\"02\",\"03\"}",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate))",
              "         ",
              "RETURN",
              "    IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "7cc3c3da-ddc1-4de1-8a6a-c2c0ac7cc92b"
          },
          {
            "name": "#_Showroom_Traffic",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTROWS('dms_sales_customer_traffic')",
              "    , dms_sales_customer_traffic[active_knd] = \"02\"",
              "    , dms_sales_customer_traffic[active_knd_dtl] IN {\"21\",\"22\",\"23\"}",
              "    || dms_sales_customer_traffic[active_knd_dtl] IN {BLANK()})"
            ],
            "formatString": "#,0",
            "lineageTag": "891e44df-a67f-42a2-b345-6fce56530353"
          },
          {
            "name": "#_Showroom_Traffic_LM",
            "displayFolder": "_Showroom",
            "expression": "CALCULATE([#_Showroom_Traffic(M)],DATEADD('v_dim_calendar'[date],-1,MONTH))",
            "formatString": "#,0",
            "lineageTag": "06eeef42-ab3a-4275-8570-f2c353e8ea0f"
          },
          {
            "name": "#_T/D_Target",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(dms_sales_kpi_resource_day[sa_kpi_code_amt])",
              "    , dms_sales_kpi_resource_day[sa_kpi_code_type] = \"DMS_BI_SA001\"",
              "    , dms_sales_kpi_resource_day[sa_kpi_code] = \"TEST_DRIVE\")"
            ],
            "formatString": "#,0",
            "lineageTag": "257d5d54-3885-4a9e-8385-2f6f73335dbf"
          },
          {
            "name": "#_TestDrive_Ratio( )",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "divide([#_Showroom_TestDrive(M)], [#_Showroom_Traffic(M)], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "e60aa431-8459-4749-b47a-ccd95a3bb3c0"
          },
          {
            "name": "#_Showroom_Traffic(M)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "// 1 xx   1   ",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR Result = ",
              "    CALCULATE(",
              "    COUNTROWS('dms_sales_customer_traffic')",
              "    , dms_sales_customer_traffic[active_knd] = \"02\"",
              "    , dms_sales_customer_traffic[active_knd_dtl] IN {\"21\",\"22\",\"23\"}",
              "    || LEN(dms_sales_customer_traffic[active_knd_dtl]) < 1",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , 'v_dim_calendar'[date] >= StartDate ",
              "    && 'v_dim_calendar'[date] <= EndDate))",
              "         ",
              "RETURN",
              "    IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "377dce3f-18cc-483d-88de-dfb25ebab775"
          },
          {
            "name": "#_Showroom_Blank_Filter(C/S)",
            "displayFolder": "_Showroom",
            "expression": "IF([#_Contract_CurrentPace_MTD]=0 && [#_Sales_CurrentPace_MTD]=0,0,1)",
            "formatString": "0",
            "lineageTag": "c00cfd3c-4a38-4f6f-a68c-add7245f1421"
          },
          {
            "name": "#_Showroom_Blank_Filter(T/TD)",
            "displayFolder": "_Showroom",
            "expression": "IF([#_Showroom_Traffic(M)]=0 && [#_Showroom_TestDrive_MTD]=0,0,1)",
            "formatString": "0",
            "lineageTag": "90d05aa9-e03d-4db6-b63a-03130fc52f08"
          },
          {
            "name": "#_Showroom_Blank_Filter(TD/C)",
            "displayFolder": "_Showroom",
            "expression": "IF([#_Contract_CurrentPace_MTD]=0 && [#_Showroom_TestDrive_MTD]=0,0,1)",
            "formatString": "0",
            "lineageTag": "b4554a56-3cd7-4766-b69b-90873bda2300"
          },
          {
            "name": "#_Showroom_TestDrive_LM_Ratio(%)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "DIVIDE([#_Showroom_TestDrive_MTD], [#_Showroom_TestDrive_LM], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "6194be29-2f68-43a8-8396-69954030bcd1"
          },
          {
            "name": "#_Showroom_TestDrive_LY",
            "displayFolder": "_Showroom",
            "expression": "CALCULATE([#_Showroom_TestDrive],DATEADD('v_dim_calendar'[date],-1,YEAR))",
            "formatString": "#,0",
            "lineageTag": "481e09d9-c34a-41d9-92c4-c2d06f4de81d"
          },
          {
            "name": "#_Showroom_TestDrive_LY_Ratio(%)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "DIVIDE([#_Showroom_TestDrive_MTD], [#_Showroom_TestDrive_LY], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "a07f1f67-4711-45aa-b054-6da182904b76"
          },
          {
            "name": "#_Showroom_Traffic_LM_Ratio(%)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "DIVIDE([#_Showroom_Traffic(M)], [#_Showroom_Traffic_LM], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "c2792869-a851-4b11-9e54-b5904c39d9b7"
          },
          {
            "name": "#_Showroom_Traffic_LY",
            "displayFolder": "_Showroom",
            "expression": "CALCULATE([#_Showroom_Traffic(M)],DATEADD('v_dim_calendar'[date],-1,YEAR))",
            "formatString": "#,0",
            "lineageTag": "ba861664-469e-4272-a118-7cfaae9a0eb5"
          },
          {
            "name": "#_Showroom_Traffic_LY_Ratio(%)",
            "displayFolder": "_Showroom",
            "expression": [
              "",
              "DIVIDE([#_Showroom_Traffic(M)], [#_Showroom_Traffic_LY], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "3b38225f-ae47-4c0f-a96b-1221039c0b73"
          }
        ],
        "partitions": [
          {
            "name": "dms_sales_customer_traffic",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_sales_customer_traffic_Table = dev_twice_Schema{[Name=\"dms_sales_customer_traffic\",Kind=\"Table\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_sales_customer_traffic_Table, \"b_variant_cd\", each if [dms_brand_cd] <> null and [concern_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [concern_variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6212944b-4331-4157-8510-062bba0bba6d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2b74cca1-2984-4ecf-a31a-04835fe051e7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c41c09f6-4ebf-4000-a809-387bfbb0142c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5afd683b-2090-4e95-8664-2e8d21e69e11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0c94fa6f-babc-4de4-8bcf-88bf3b6e4420",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0150556b-49d3-470c-9b11-56e234e63e1b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "906d15db-0ae7-4641-b0ae-b77341adbc54",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a42afcfc-7abd-45ed-97b4-ab9f2a965cb4",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "6643bf7a-5bc8-40e3-9bdd-4e7d18875ac4",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9d6af1ca-586c-43a5-a627-efca0b033cc5",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "a60d9f72-1d15-438b-b04f-956a96717861",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "43d151bd-1a2b-4c4a-bb3e-217789ff973a",
                "ordinal": 3
              }
            ],
            "lineageTag": "e37f4999-6d31-4d92-8520-90bae70c8e06"
          }
        ],
        "isHidden": true,
        "lineageTag": "34b20b5b-f480-4218-af34-f16b4f7fa75b",
        "partitions": [
          {
            "name": "LocalDateTable_6212944b-4331-4157-8510-062bba0bba6d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_customer_traffic'[dms_bi_reg_dt])), 1, 1), Date(Year(MAX('dms_sales_customer_traffic'[dms_bi_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_a6ec5deb-3c10-4ee5-a1b0-adbf2364851a",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ae8ae8a0-bfa1-445c-a993-8cb85221c7ef",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2a804ddc-0d67-458a-b656-36e0866fa59d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a64a43c8-24c2-46c9-a40b-558d9b4c728a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "db1d2442-ec14-4ba8-b9e6-83a39c708bbe",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "79e96031-85f1-4238-8a86-5f2d659b8cbc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "01f29adb-f3e7-4724-880e-7f8101865d25",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "31e00c37-3ea8-4f34-a556-e31b403dbe54",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "d19debfa-2678-4f71-a949-f604726c8e42",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "bb3c94c7-bc8f-48d2-abc6-9c3fbc0adc11",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "54a1a1a7-4f0d-4bb7-a1a1-ac51df1e3373",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "ce16a915-30bd-4984-aaba-6f536c7989aa",
                "ordinal": 3
              }
            ],
            "lineageTag": "780dd4c8-0644-45d4-a48b-1052985ffb86"
          }
        ],
        "isHidden": true,
        "lineageTag": "cea40201-7dd3-4f58-8aad-ace1646e7e1e",
        "partitions": [
          {
            "name": "LocalDateTable_a6ec5deb-3c10-4ee5-a1b0-adbf2364851a",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_customer_traffic'[dms_bi_upd_dt])), 1, 1), Date(Year(MAX('dms_sales_customer_traffic'[dms_bi_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_sales_kpi_resource_day",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Exception"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2cb39801-af99-487c-858a-430186c27004",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0b544601-f6e4-496c-a290-5b604215a812",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "57763f2d-eca1-4b02-8012-1ee0c711040c",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "777b6a95-7e67-4b95-9e24-8fa79d681336",
            "sourceColumn": "yyyymmdd",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ef254273-b8b4-42a3-be41-87b91b91df0a",
            "sourceColumn": "sa_kpi_code_type",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "61c53b37-158a-4503-bbbe-c2f32f1e7204",
            "sourceColumn": "sa_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "0573fa0c-e7c4-4694-a18e-ca9746597b1c",
            "sourceColumn": "sa_kpi_code_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ae40284d-140b-4a4f-9c75-225a32cc980e",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1dac918a-1b35-40f6-b55d-0f081144f9c4",
            "sourceColumn": "variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f2f14250-d7a6-44e4-81d8-528c614584e3",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7729d40-78a4-46ee-b8fe-0df5d0a989ee",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "283fd958-d1d6-4334-9fac-d3cf56d1b643",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_44491dc9-7093-4ea3-a163-863857ea72aa"
                },
                "isDefault": true,
                "relationship": "d052977d-2b2a-4ebe-94a4-6a7a08c8b35a"
              }
            ]
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "84aba90f-b65f-4c0b-9286-d2c1e290aebd",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e4ee7890-aebe-4761-b20a-eca1f7f815fe",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_52f6b028-e7be-4fdc-9711-bd21f9578454"
                },
                "isDefault": true,
                "relationship": "a0e2adb1-7aac-4293-bd58-e3e96e04f515"
              }
            ]
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26bda331-ef08-4ab8-864e-9fa8373df13f",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2adbd6a8-172b-46be-ae6d-9e0081c31d07",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd(Date)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "                LEFT(dms_sales_kpi_resource_day[yyyymmdd], 4), // '2023'   ",
              "                MID(dms_sales_kpi_resource_day[yyyymmdd], 5, 2), // '01'   ",
              "                RIGHT(dms_sales_kpi_resource_day[yyyymmdd], 2)   // (day) ",
              "            )",
              ""
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "90941ddc-d5ca-41cf-bc0d-fe237bd4e1ba",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c677876e-2559-4573-aca3-fb0265896708",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5895d6b7-dd47-48e8-92b3-3e7867a1ff97",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "d490c39f-1b75-4bc4-9625-db27a19034e5",
        "partitions": [
          {
            "name": "dms_sales_kpi_resource_day",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.Query(\"dsn=TOYOTA1\", \"SELECT *#(lf)FROM dms_sales_kpi_resource_day dskrd #(lf)WHERE EXTRACT(YEAR FROM TO_DATE(yyyymmdd, 'YYYYMMDD')) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5;\"),",
                "    #\"  \" = Table.AddColumn(, \"b_report_variant_cd\", each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_44491dc9-7093-4ea3-a163-863857ea72aa",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "082598f0-7f52-4bad-97b8-aba2af357360",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2ac1ac91-8b40-4e00-9139-e212e5b26ddc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "0fbc75bb-c6fa-488c-87d8-3adeb60d2677",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "ba55d335-be71-49a1-8ff1-256f0639fd0b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a705b448-7e85-4c66-a7fc-5f318a8162db",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "f01adc11-a3c0-424a-b103-e7211d5acfba",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fa598b1e-704a-4feb-8f38-4df149597ac9",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "d001220d-aab6-4ed5-b6ec-414cbf1cd9e8",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "2d15a142-f8a7-4cff-bbc1-d2a0a0feb750",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "f7c5bef5-8d6e-47e8-887c-d6497a3e45b3",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "7f1bcb13-53d6-4b72-aa9e-9c848bf763a8",
                "ordinal": 3
              }
            ],
            "lineageTag": "74e0109e-af59-4f13-b874-fd111602729b"
          }
        ],
        "isHidden": true,
        "lineageTag": "85b25917-afc8-4623-8965-e5736e467844",
        "partitions": [
          {
            "name": "LocalDateTable_44491dc9-7093-4ea3-a163-863857ea72aa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_kpi_resource_day'[dms_bi_reg_dt])), 1, 1), Date(Year(MAX('dms_sales_kpi_resource_day'[dms_bi_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_52f6b028-e7be-4fdc-9711-bd21f9578454",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "52c242fa-08a5-4e69-893c-0f1c2dc5acb7",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f9df6434-d46a-4eaa-8dc7-f8a83d1906f4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c7ca5437-d5ad-4652-bc30-9904439096f0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "0ccbf193-3c80-4a8d-8bd1-4cd3a54515b7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4b0fb0f0-f03a-4289-9200-92cc4cc0089b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "ae1c641f-dcd7-48f4-aad4-3f5cff3090cf",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "8d9a26ea-1576-4d9c-a6aa-9423802b1552",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "99bfc63e-6fa6-45a2-bc17-a2454746a882",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "da6993c1-e203-44b0-8bf9-fd235f6323aa",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "8f1f722b-47d5-4e38-b6b3-419bc6bfad70",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "96c8c3cc-a5bf-44ec-b281-e5ab9954a6e0",
                "ordinal": 3
              }
            ],
            "lineageTag": "2f405af5-5524-4d47-a85e-43b5a4517168"
          }
        ],
        "isHidden": true,
        "lineageTag": "3fbf0dc2-db5b-4067-883c-2bc91a1e7a09",
        "partitions": [
          {
            "name": "LocalDateTable_52f6b028-e7be-4fdc-9711-bd21f9578454",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_kpi_resource_day'[dms_bi_upd_dt])), 1, 1), Date(Year(MAX('dms_sales_kpi_resource_day'[dms_bi_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_sales_testdrive",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "eef82483-3cef-4137-b542-0669aebe7319",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "reserved_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "8acf4391-5113-4ad1-aa49-003b93611770",
            "sourceColumn": "reserved_dt",
            "summarizeBy": "none"
          },
          {
            "name": "testcar_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c41573b3-ddc8-4e9d-a8ef-77bf7c272f82",
            "sourceColumn": "testcar_no",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "155dacc3-2fde-4eb4-8510-5eefe85159f9",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e6f8701a-c4fd-4373-8011-4f47f2228de6",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e3ef53ae-25d1-418e-86c9-81abc5178a6c",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "use_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a4cc08a-12f9-4e7a-8616-32d95ea88f93",
            "sourceColumn": "use_type",
            "summarizeBy": "none"
          },
          {
            "name": "test_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd1668b3-2df6-418e-9b24-67f8247a4f24",
            "sourceColumn": "test_type",
            "summarizeBy": "none"
          },
          {
            "name": "test_type_detail",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "557d8b08-2efc-4803-aaa6-58b35a9d5c59",
            "sourceColumn": "test_type_detail",
            "summarizeBy": "none"
          },
          {
            "name": "interest_degree",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e22f589a-e2e6-42a6-92d2-4ef3379920a2",
            "sourceColumn": "interest_degree",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "dbecb298-78bf-4c14-8c42-aacde49136cd",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "60bcfa79-f13e-4577-82e8-7cfb64a01a88",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_7bb56323-3235-4b35-a406-fe7de7dcaa63"
                },
                "isDefault": true,
                "relationship": "75cb1c36-f464-4af7-848f-1983bedc4229"
              }
            ]
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b598c935-93df-453a-afa6-19ea31b9e9ac",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "07d3b8e1-ced7-4ce0-b285-d9b1fae01734",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_449fadeb-aeeb-4450-a978-884e920a2166"
                },
                "isDefault": true,
                "relationship": "5ec862e8-ffde-4aa6-acd6-519d62bc69ff"
              }
            ]
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4806fff6-fc37-46de-9baf-d1d27fdc36e0",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "reserved_st_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f808e05c-679a-4749-b272-2581057cd362",
            "sourceColumn": "reserved_st_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_866b0a4b-662d-4de2-b00d-6813cba759fa"
                },
                "isDefault": true,
                "relationship": "126aab3f-93a9-49c7-bed7-6f50c233d6dd"
              }
            ]
          },
          {
            "name": "reserved_end_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "5e544f40-407a-45d5-82db-f6c070248763",
            "sourceColumn": "reserved_end_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_7c9aaea1-343b-468c-8c49-c2cbe5b98378"
                },
                "isDefault": true,
                "relationship": "89021e9e-3e7c-4fb8-8022-179445b47d17"
              }
            ]
          },
          {
            "name": "from_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06aaa62b-f3dd-4566-bf42-fb5a4d2b2468",
            "sourceColumn": "from_time",
            "summarizeBy": "none"
          },
          {
            "name": "to_time",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "10e53f2b-0acb-4b0a-a4aa-48509d6fdbde",
            "sourceColumn": "to_time",
            "summarizeBy": "none"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bfdddcdc-316b-4adc-9c57-9e6da6034771",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5addd712-9251-4e00-a19f-09ac22c54794",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d002a45-4ab4-4e45-ba17-75c8aed678d7",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "212da00c-e65f-4abd-b7e1-1b43db9d76a4",
        "partitions": [
          {
            "name": "dms_sales_testdrive",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_sales_testdrive_Table = dev_twice_Schema{[Name=\"dms_sales_testdrive\",Kind=\"Table\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_sales_testdrive_Table, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text),",
                "    #\" \" = Table.TransformColumnTypes(#\" 2\",{{\"reserved_dt\", type date}})",
                "in",
                "    #\" \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7bb56323-3235-4b35-a406-fe7de7dcaa63",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e8d2c948-0674-41c2-9abf-e838fcdc6cfb",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "dfdc672e-0bb0-4b9f-b6b4-eb3f22694a16",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "dceb5250-5606-4afb-bd95-2d36e378151b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "98a402b1-ff51-4cab-8e54-625850394062",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "cd7e3f32-f07f-46ec-b95d-a54f2a8edd9c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8f9c27eb-fd9c-486b-bb9d-47c116614254",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "bb194da1-1fd7-4e60-8385-8f5450f4b826",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "b4264b35-1873-4b40-b1ee-f6a6f89b7b8a",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "510f0b78-f810-4dd8-8dde-08d1210359ff",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "34f0f287-a009-4a80-bf0b-a1606b623781",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "f4447296-1a04-4eba-b8f7-1a9b562eb9b4",
                "ordinal": 3
              }
            ],
            "lineageTag": "ef6f2377-d095-44aa-a1bc-9b67f318f6ba"
          }
        ],
        "isHidden": true,
        "lineageTag": "e90a604f-9936-4f1d-89f3-db27b083718b",
        "partitions": [
          {
            "name": "LocalDateTable_7bb56323-3235-4b35-a406-fe7de7dcaa63",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_testdrive'[dms_bi_reg_dt])), 1, 1), Date(Year(MAX('dms_sales_testdrive'[dms_bi_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_449fadeb-aeeb-4450-a978-884e920a2166",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ed7f8a41-e17e-4ce5-bae6-91c40f23cf06",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "58c3e5f0-6d9b-403f-9991-f7f1478bc01c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "bf641ba0-3d3d-42bc-a90d-69ccaf068015",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "99eeddd6-a9c2-4225-a94f-31d578b0a10b",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "a665ba37-7356-40cd-8e0a-7c9711992d83",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "98e41dfd-9772-4618-97e5-68bafca9066e",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5e361224-e162-47ea-bed2-38ae6c72790d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "a0b04426-a04b-4a97-9824-99785e6bda32",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "fbd3a0c3-25b2-4714-9d30-fe0dbad0bac3",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "c3d06f5a-f2f5-4120-a413-410a2a8e6316",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "053263c4-dc3e-4d7c-a614-6f5fb414fbb3",
                "ordinal": 3
              }
            ],
            "lineageTag": "290748d5-4404-434e-918b-289733338fe4"
          }
        ],
        "isHidden": true,
        "lineageTag": "12c247e5-41be-4311-a6a8-5a78efa43148",
        "partitions": [
          {
            "name": "LocalDateTable_449fadeb-aeeb-4450-a978-884e920a2166",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_testdrive'[dms_bi_upd_dt])), 1, 1), Date(Year(MAX('dms_sales_testdrive'[dms_bi_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_866b0a4b-662d-4de2-b00d-6813cba759fa",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ac878649-2089-46e3-b62d-55f2b38d9dc0",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3643cb89-4529-402c-9962-f0bef21cbc85",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "6372b356-5366-4203-9a76-df8bae8461e0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "41423609-f7d3-4e92-a59e-4a1950a70d1d",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7a6bab6f-393b-488e-ae97-3533a694e710",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "67351af6-ebad-4ee3-95e5-36e792e2b41c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "956fa67c-f20a-4f94-9c22-8f7a2629eb89",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "ea24f5c7-263d-4ec8-8117-ddf105a2ffa5",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "724e1af2-fc50-45d2-9378-e01e947e49f6",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "2f802a74-e40a-4729-a152-478917a463c5",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "e10fad56-8c4d-4668-b9ed-7293ad323457",
                "ordinal": 3
              }
            ],
            "lineageTag": "c8a3219b-c4ac-4564-b84f-b63a26ab3a39"
          }
        ],
        "isHidden": true,
        "lineageTag": "6105f60a-f7fb-4469-b549-ea45ecea184b",
        "partitions": [
          {
            "name": "LocalDateTable_866b0a4b-662d-4de2-b00d-6813cba759fa",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_testdrive'[reserved_st_dt])), 1, 1), Date(Year(MAX('dms_sales_testdrive'[reserved_st_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_7c9aaea1-343b-468c-8c49-c2cbe5b98378",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "7357c2df-0cc3-49c6-abd2-95dd7afc9c8b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9b77d117-146d-4b16-8ea6-7177ab01b3ad",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7bcbf7e7-8191-498e-b8ea-471157c58701",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "96336506-d734-4a91-9c12-8e78ef695fdb",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "19c63332-23b0-4ce0-b2b2-7d29a1678c00",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2183b241-182c-42db-83d5-10e18f6ee534",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "84159903-a219-4381-886f-8e2ffde0e109",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "cdea2617-40c0-457e-ab8a-db1bfa3d0956",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "a3248ce2-d5e8-40ee-9409-6f50c6326e58",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1659646a-cd89-4e5d-baaf-7adcf848de77",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b42392f6-8f6c-47e8-bce8-98617ab2306a",
                "ordinal": 3
              }
            ],
            "lineageTag": "9d40537e-6928-468f-b052-bcfbbfd4c938"
          }
        ],
        "isHidden": true,
        "lineageTag": "86efda53-2d95-4d23-a2e5-3e6723a0b498",
        "partitions": [
          {
            "name": "LocalDateTable_7c9aaea1-343b-468c-8c49-c2cbe5b98378",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_testdrive'[reserved_end_dt])), 1, 1), Date(Year(MAX('dms_sales_testdrive'[reserved_end_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "v_fact_contract_conversion_daily_sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "22ae0170-9c8e-4151-9cb8-378b1f58109d",
            "sourceColumn": "dt",
            "summarizeBy": "none"
          },
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "23226159-6efd-403a-bada-9b2d074f8a80",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdf2b492-0cac-46f1-9e2e-2803d334d638",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "03829b15-e917-492a-a897-6b83cecc420f",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0e6466e8-e309-4b96-828b-a29cb18aa11a",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2673bef5-3b27-43af-b254-6a5d7aa8a2be",
            "sourceColumn": "category",
            "summarizeBy": "none"
          },
          {
            "name": "monthly_target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "d246b9f2-2436-4a44-b7de-7293e92cea1c",
            "sourceColumn": "monthly_target",
            "summarizeBy": "sum"
          },
          {
            "name": "daily_target",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f2a6ca29-2a53-462f-b11e-f713969b6d2f",
            "sourceColumn": "daily_target",
            "summarizeBy": "sum"
          },
          {
            "name": "result",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "cc810bff-a96e-4ae3-86d0-1e87907bc0fd",
            "sourceColumn": "result",
            "summarizeBy": "sum"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a324c3fe-d19c-41d2-94bd-22af651fce90",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c7a8faf6-81c2-41bf-a5c7-92fcf0b8006e",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7c6e8f5b-68df-45c4-be59-ce4076e9e7f9",
        "measures": [
          {
            "name": "#_Contract_Gap(%)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "VAR _A =",
              "(DIVIDE(",
              "    [#_Contract_Result(D)_view_MTD]",
              "    , [#_Contract_Target(D)_view_MTD]",
              "    , 0) - 1)",
              "",
              "",
              "RETURN ",
              "_A"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "1209883b-875b-4c9f-91d3-bc711f597caa"
          },
          {
            "name": "#_Contract_Result(D)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[result])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"Contract\")"
            ],
            "formatString": "#,0",
            "lineageTag": "044f2237-b9b1-473e-9e12-eb5dd53f7862"
          },
          {
            "name": "#_Contract_Result(D)_view_MTD",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "CALCULATE([#_Contract_Result(D)_view], DATESMTD(v_dim_calendar[date]))"
            ],
            "formatString": "#,0",
            "lineageTag": "37eba6de-4253-44fa-b1ff-1ce467a9dcae"
          },
          {
            "name": "#_Contract_Target(D)_view",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[daily_target])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"Contract\")",
              "",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "1b23a775-977e-42a8-a32d-989bdc6b5cb6"
          },
          {
            "name": "#_Contract_Target(D)_view_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "CALCULATE([#_Contract_Target(D)],DATESMTD(v_dim_calendar[date]))"
            ],
            "formatString": "#,0",
            "lineageTag": "e96de9ea-972e-462f-8769-ec5ff7dbb9d9"
          },
          {
            "name": "#_Contract_Target(M)_view",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR _Result = ",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[daily_target])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"Contract\"",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , v_dim_calendar[date] >= StartDate",
              "    && v_dim_calendar[date] <= EndDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "88d1aa26-ec20-4edd-9568-484bba0ec84b"
          },
          {
            "name": "#_Conversion_Gap(%)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "[#_Result_Conversion(%)_(D)_view] - [#_Target_Conversion(%)_(D)_view]",
              ""
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "dabd35c7-e766-4747-a33b-02d36df4af8b"
          },
          {
            "name": "#_Result_Conversion(%)_(D)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "DIVIDE([#_Contract_Result(D)_view_MTD], [#_TestDrive_Result(D)_view_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "2ffa810e-433c-4221-a1ba-1aa0b755ce70"
          },
          {
            "name": "#_Target_Conversion(%)_(D)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "DIVIDE([#_Contract_Target(D)_view_MTD], [#_TestDrive_Target(D)_view_MTD], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "30af8b58-8103-4f13-ac3e-43cac3835126"
          },
          {
            "name": "#_Target_Conversion(%)_(M)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "DIVIDE([#_Contract_Target(M)_view], [#_TestDrive_Target(M)_view], 0)"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "1dcaf14c-205f-462c-a271-b86852fcc2c4"
          },
          {
            "name": "#_TestDrive_Gap(%)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "VAR _A =",
              "DIVIDE(",
              "    [#_TestDrive_Result(D)_view_MTD], [#_TestDrive_Target(D)_view_MTD], 0",
              "    )",
              "",
              "VAR _B = (_A) - 1",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "a46f3855-f02f-4200-a14e-72facc97ccf4"
          },
          {
            "name": "#_TestDrive_Result(D)_view",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[result])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"T/D\")"
            ],
            "formatString": "#,0",
            "lineageTag": "3efc5a6a-4c83-4e87-904a-71204e97295d"
          },
          {
            "name": "#_TestDrive_Result(D)_view_MTD",
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "CALCULATE([#_TestDrive_Result(D)_view], DATESMTD(v_dim_calendar[date]))"
            ],
            "formatString": "#,0",
            "lineageTag": "365c800d-ca32-4e23-8d74-709b74106959"
          },
          {
            "name": "#_TestDrive_Target(D)_view",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[daily_target])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"T/D\")"
            ],
            "formatString": "#,0",
            "lineageTag": "f8536f0c-1be3-43e8-a64b-e2ad2c08e62f"
          },
          {
            "name": "#_TestDrive_Target(D)_view_MTD",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "CALCULATE([#_TestDrive_Target(D)_view], DATESMTD(v_dim_calendar[date]))"
            ],
            "formatString": "#,0",
            "lineageTag": "6515bba8-44a7-459d-a2f1-74893c72fadd"
          },
          {
            "name": "#_TestDrive_Target(M)_view",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDecimal\":true}"
              }
            ],
            "displayFolder": "_Conversion",
            "expression": [
              "",
              "",
              "VAR SelectedDate = ",
              "IF(HASONEVALUE(v_dim_calendar[date])",
              ", SELECTEDVALUE(v_dim_calendar[date])",
              ", LASTDATE(v_dim_calendar[date]))",
              "",
              "VAR StartDate = EOMONTH(SelectedDate, -1) + 1 // 1",
              "VAR EndDate = EOMONTH(SelectedDate, 0) // ",
              "",
              "VAR _Result = ",
              "CALCULATE(",
              "    SUM(v_fact_contract_conversion_daily_sales[daily_target])",
              "    , v_fact_contract_conversion_daily_sales[category] = \"T/D\"",
              "    ,FILTER(ALL(v_dim_calendar)",
              "    , v_dim_calendar[date] >= StartDate",
              "    && v_dim_calendar[date] <= EndDate))",
              "",
              "RETURN",
              "    _Result"
            ],
            "formatString": "#,0",
            "lineageTag": "3c71660f-dbf0-4ba2-9768-ea6471dfee80"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_contract_conversion_daily_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_contract_conversion_daily_sales_View = dev_twice_Schema{[Name=\"v_fact_contract_conversion_daily_sales\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(v_fact_contract_conversion_daily_sales_View, \"b_report_variant_cd\"",
                "    , each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \" , \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text)",
                "in",
                "    #\" 1\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_fact_local_stock_sales",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "90fcd87a-89ea-4bbd-ab08-bfc86e764cc2",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "regist_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d3a4e3cc-5e7b-429f-8cc2-5fae05c8418b",
            "sourceColumn": "regist_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_547bae4a-e835-49b1-a1d9-cc14ba120b64"
                },
                "isDefault": true,
                "relationship": "2f4d4361-cf9c-4915-b9df-4d5ad1ae262f"
              }
            ]
          },
          {
            "name": "lineoff_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "90878e6f-d93c-446e-b8e2-844fcee23c49",
            "sourceColumn": "lineoff_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_b052abb8-6c3d-4b0d-b025-57032a34093d"
                },
                "isDefault": true,
                "relationship": "0ffa235f-37d9-4a32-afe9-1458e2e0e3a9"
              }
            ]
          },
          {
            "name": "delivery_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "20ff3d68-aac4-44a4-9205-2fb17ac7e207",
            "sourceColumn": "delivery_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_1188d505-dd7e-423b-9e6f-bd0259f8e146"
                },
                "isDefault": true,
                "relationship": "87136e60-c7cb-4a69-b2a7-5244dd6bd16c"
              }
            ]
          },
          {
            "name": "port_in_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cc65b72f-196c-4558-8c9e-02ada3b30808",
            "sourceColumn": "port_in_dt",
            "summarizeBy": "none"
          },
          {
            "name": "retailsales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "0357b391-4faa-4b72-b05b-b73cb5c36251",
            "sourceColumn": "retailsales_dt",
            "summarizeBy": "none"
          },
          {
            "name": "wholesales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "d7645dbf-d08a-4f93-ab00-3977fdcbd165",
            "sourceColumn": "wholesales_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_1fad5556-b440-4add-91ed-e11b1bfdc7a1"
                },
                "isDefault": true,
                "relationship": "9be3018b-8d3f-4389-9b45-ef236eec924e"
              }
            ]
          },
          {
            "name": "vin",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2d348b82-09d5-41cd-bb06-69470ec668bf",
            "sourceColumn": "vin",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_magic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "0b4310ed-b4f9-4079-9ce1-573462338b59",
            "sourceColumn": "vehic_magic",
            "summarizeBy": "sum"
          },
          {
            "name": "stock_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d38448fb-5600-49cd-b48e-046b10f0729f",
            "sourceColumn": "stock_status",
            "summarizeBy": "none"
          },
          {
            "name": "al_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72b8491c-45c1-4fbd-bf62-a2242563f0b9",
            "sourceColumn": "al_status",
            "summarizeBy": "none"
          },
          {
            "name": "progress_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2fe6d6f-a490-49d3-992b-ee01a26ece73",
            "sourceColumn": "progress_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8f12b022-56b2-42d2-81f5-d8f9a48083d5",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0871256-d3e1-4eb8-ac41-0a4afe9c1bfb",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "contract_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "bdf44e16-9d60-4e33-a175-fa8888caf52f",
            "sourceColumn": "contract_reg_dt",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e93af7a1-3390-4aa6-a59d-359c5045f488",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "35ccb771-8652-4ae7-a7ca-d3f6dd67c95a",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "160bcda5-83cc-4733-8070-275196066ee5",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "34af89ef-6e0f-4bf6-94a5-150500e19010",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "994f4362-a83b-4639-be31-bfacda3afe73",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "3887cf45-1a70-46c4-90c6-efcaa0d0fe81",
        "measures": [
          {
            "name": "#_BOC Month",
            "displayFolder": "_Other KPIs_b",
            "expression": [
              "",
              "",
              "VAR _A = DIVIDE([#_N-1 BOC], [#_N Sales_Plan])",
              "",
              "VAR _B = ROUND(_A, 1)",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0.0",
            "lineageTag": "64769bff-5c2c-4c57-9c53-7a6c2e4774e4"
          },
          {
            "name": "#_Diff Month",
            "displayFolder": "_Other KPIs_b",
            "expression": "[#_Stock Month] - [#_BOC Month]",
            "formatString": "#,0.0",
            "lineageTag": "8ad1c56f-e3c5-4052-b3e7-a6e059825725"
          },
          {
            "name": "#_Local Stock(N-1)_Arrival(N)_Ratio(Plan)",
            "displayFolder": "_Other KPIs_b",
            "expression": "DIVIDE([#_N-1 Local_Stock]+[#_N Arrival],[#_N Sales_Plan],0)",
            "formatString": "#,0%;-#,0%;#,0%",
            "lineageTag": "7e8b75f4-e4a9-4557-bf2a-7b7211e2a3dd"
          },
          {
            "name": "#_N Arrival",
            "displayFolder": "_Other KPIs_b",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS(v_fact_local_stock_sales)",
              ", NOT v_fact_local_stock_sales[progress_cd] IN {BLANK()})",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "e287245b-7225-43d6-ac2e-e42647116ce3"
          },
          {
            "name": "#_N-1 Local_Stock",
            "displayFolder": "_Other KPIs_b",
            "expression": [
              "",
              "VAR Result = ",
              "CALCULATE(COUNTROWS('v_fact_local_stock_sales')",
              ", ALLEXCEPT(",
              "    'dms_sales_contract'",
              "    , dms_co_brand[dms_brand_cd]",
              "    , dms_co_report_variant_v[model_nm]",
              "    , v_dim_group_sales[group_eng_name]",
              "    ,v_dim_group_sales[dealer_id]",
              "    , v_dim_group_sales[group_name(New)])",
              "    , 'v_fact_local_stock_sales'[port_in_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "    , SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              "    , ISBLANK('v_fact_local_stock_sales'[retailsales_dt])",
              "    ||'v_fact_local_stock_sales'[retailsales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year])",
              "    ,SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              ")",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "2708df66-8600-49d9-8148-c16e47766391"
          },
          {
            "name": "#_Stock Month",
            "displayFolder": "_Other KPIs_b",
            "expression": [
              "",
              "",
              "VAR _A = DIVIDE(v_fact_local_stock_sales[#_N-1 Local_Stock], [#_N Sales_Plan])",
              "",
              "VAR _B = ROUND(_A, 1)",
              "",
              "RETURN",
              "_B"
            ],
            "formatString": "#,0.0",
            "lineageTag": "b2709dae-69f8-4e2d-bbbe-6d3e0bdf1ed1"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_local_stock_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_local_stock_sales_View = dev_twice_Schema{[Name=\"v_fact_local_stock_sales\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(v_fact_local_stock_sales_View, \"b_report_variant_cd\"",
                "    , each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \" , \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_547bae4a-e835-49b1-a1d9-cc14ba120b64",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0df6b3ed-b855-4d36-895f-4eb523dc1d5f",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "fd29298d-818a-493b-bfc1-f924dbb025d5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "c94d1890-ea67-4808-be51-702facf08095",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3541cf6a-a277-471a-89f9-a16a751dc105",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "acda7c3c-384e-4556-91da-bafaee68d0b8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "c4108ee8-ca3d-47fa-9876-62484d0cb986",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c56384a8-d823-4d3e-8ff4-640cb5bee9f8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "f508ea76-4099-4672-948e-98335188ad60",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1872bff5-9685-4571-98fd-74e8a3d7483e",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "cef2f618-aa8a-4a5d-a3e7-cfebfc186c83",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "458e9c7d-e2f2-47d7-9255-b315fc4d848b",
                "ordinal": 3
              }
            ],
            "lineageTag": "21b039ea-973f-408a-b038-5b84ad415da3"
          }
        ],
        "isHidden": true,
        "lineageTag": "b4a0ca25-29ec-4d0a-b650-22dffa312812",
        "partitions": [
          {
            "name": "LocalDateTable_547bae4a-e835-49b1-a1d9-cc14ba120b64",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_local_stock_sales'[regist_dt])), 1, 1), Date(Year(MAX('v_fact_local_stock_sales'[regist_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_b052abb8-6c3d-4b0d-b025-57032a34093d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "12881a6a-7dce-4d7e-b49b-55bda8a55390",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "b0b94bdd-163b-4b3a-a442-b234239bedcc",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "7b47893c-3d9f-4c6c-ad68-60ba59396f55",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "e0c65616-7302-4578-b384-609f97191f36",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7f74ec52-05b3-48ac-b91a-9274712cba71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8deb93d0-cc89-4257-9274-24067a28c617",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "a12f5f9e-bacf-460d-8b78-2ce9e680bed5",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "573b9365-7d90-4934-820e-1a4edbd6e33b",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "68098eb6-5b66-41c8-a4e9-8837bfb758ca",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "4e074b8e-12b4-4123-a27d-cd463b5a0a7e",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "d5eead49-a942-4e78-8aae-1ad690a14507",
                "ordinal": 3
              }
            ],
            "lineageTag": "0650ea17-1cf1-4765-9899-07309ec2a2d9"
          }
        ],
        "isHidden": true,
        "lineageTag": "ba067199-aa73-4f3b-90ce-bda6f609f5b1",
        "partitions": [
          {
            "name": "LocalDateTable_b052abb8-6c3d-4b0d-b025-57032a34093d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_local_stock_sales'[lineoff_dt])), 1, 1), Date(Year(MAX('v_fact_local_stock_sales'[lineoff_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1188d505-dd7e-423b-9e6f-bd0259f8e146",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "dfa06782-ece6-47b5-bf62-3362ae537987",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "326200bf-e26e-4c8e-839d-f467167981c3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "41ca9cb9-0e2c-412f-9564-e8e1cbf81604",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "613ba0b2-2fc4-4043-b9d5-c9d3cec418de",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "0ef526b8-b0e3-4978-8502-fc7b78126a11",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0251bb18-7a95-49ad-965a-f9d8e7909e61",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "d101dca2-628b-4f81-aea6-97087a26f7b8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "bc74bf87-2a17-4808-b640-aef8570e9c25",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9be1cfd9-776a-4e7e-8c76-6d0e0fcbc0e1",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1cb297d0-3846-4ba2-a806-fc43090d7e89",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b10e3a9f-682e-42a1-9248-1fca09f86e66",
                "ordinal": 3
              }
            ],
            "lineageTag": "baed29b6-9aa6-45a7-8bb9-a5254394f011"
          }
        ],
        "isHidden": true,
        "lineageTag": "1c5eff1c-665a-4a09-bc80-9a0ae62dafe7",
        "partitions": [
          {
            "name": "LocalDateTable_1188d505-dd7e-423b-9e6f-bd0259f8e146",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_local_stock_sales'[delivery_dt])), 1, 1), Date(Year(MAX('v_fact_local_stock_sales'[delivery_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_1fad5556-b440-4add-91ed-e11b1bfdc7a1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fa06ea76-1ddc-4068-9fe3-3c447076f580",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c1e35f4d-23ee-47b7-8df1-15a50c022b25",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8f5cff24-1e0e-4663-8228-6c7c54a82810",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "544c9511-1f9e-4c06-8b86-d9a97c6044c9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2c130cc7-91ef-45c8-9fc6-111a88c72b29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "6d7a9008-311f-41ae-aa3e-1f45aead278d",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "aa5bfc9e-3b91-48ac-9d4f-42d4596f61a8",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "cb82359e-6571-49d0-9199-c377d6f3a713",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9e8ed386-c710-452a-9f10-84ef09435f72",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "8c51f95d-b04f-4934-a7f5-234f61912e7b",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "65f8bf44-2ff6-46ce-b54a-04c67aeadae8",
                "ordinal": 3
              }
            ],
            "lineageTag": "485d05d0-c018-42a9-8f15-a75a5ceef111"
          }
        ],
        "isHidden": true,
        "lineageTag": "0752fd53-85bc-4d5b-a5c8-c74aae20567a",
        "partitions": [
          {
            "name": "LocalDateTable_1fad5556-b440-4add-91ed-e11b1bfdc7a1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_local_stock_sales'[wholesales_dt])), 1, 1), Date(Year(MAX('v_fact_local_stock_sales'[wholesales_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_co_report_variant_v",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2985d73f-d2b4-4a1e-afc1-ecc12505b3f7",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4df3bd72-5c36-45d5-99bf-aadc10d43b4d",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "86b86476-42b1-4f10-8445-bb5bccb02e7d",
            "sortByColumn": "model_display_order",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5b8f8ccc-9572-48c3-821f-2ba01b57072b",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "560943f3-e736-432d-bde8-0aef7640ddb3",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "brand_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f8231fd-d3a7-4482-beeb-0b06c97d108b",
            "sourceColumn": "brand_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "65f0112b-6acf-4beb-ad2c-90aaccb4a97b",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "516c6d0c-1e67-42c1-9d6c-22c04527149d",
            "sortByColumn": "model_display_order",
            "sourceColumn": "model_nm",
            "summarizeBy": "none"
          },
          {
            "name": "model_display_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "d14d70a5-6289-42db-ad99-67483d96eaaf",
            "sourceColumn": "model_display_order",
            "summarizeBy": "sum"
          },
          {
            "name": "report_display_order",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "8ef341fd-25fe-4e78-ba5a-20f46646df2f",
            "sourceColumn": "report_display_order",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "8955bea9-bb91-4edf-b490-3a1bc3f6f29a",
        "partitions": [
          {
            "name": "dms_co_report_variant_v",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_report_variant_v_View = dev_twice_Schema{[Name=\"dms_co_report_variant_v\",Kind=\"View\"]}[Data],",
                "    #\"  \" = Table.AddColumn(dms_co_report_variant_v_View, \"b_report_variant_cd\", each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text)",
                "in",
                "    #\"  \""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_sales_kpi_history",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b980e91-1b88-4049-ae09-2049398dd34a",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3c5f2eff-5a8a-4e70-9e11-287cc030437b",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "his_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "f0602563-4ca7-4e09-a622-c13067eb6f0f",
            "sourceColumn": "his_type",
            "summarizeBy": "none"
          },
          {
            "name": "seq",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "16a0ba00-2842-42f6-b277-b0467ed5e46a",
            "sourceColumn": "seq",
            "summarizeBy": "sum"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c41c57b7-57c0-4216-8607-217f8740f467",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "411a0c6b-fb40-4cd9-ab3b-0f4077e3b377",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_magic",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "c9a37f5f-d841-4832-ba54-c839bc1ec61c",
            "sourceColumn": "vehic_magic",
            "summarizeBy": "sum"
          },
          {
            "name": "contract_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "a95de854-9171-4a95-999c-c06161ad31a6",
            "sourceColumn": "contract_no",
            "summarizeBy": "sum"
          },
          {
            "name": "dlr_contract_no",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "95158f35-6319-4c1d-a50c-62f662c44e4a",
            "sourceColumn": "dlr_contract_no",
            "summarizeBy": "none"
          },
          {
            "name": "vehic_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "58d6ee16-3ce3-407a-b5c3-16f9bc744eab",
            "sourceColumn": "vehic_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "73b7290c-fcca-4fa9-b22b-c1c6d74dc0fd",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "29d425a0-c1e1-4373-9d28-529d6c9e3e0f",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "my_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "b3698fce-ddea-4b06-942a-85a21ef434da",
            "sourceColumn": "my_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sfx_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cd7e0dd-865a-483e-94d5-4222d7334ac4",
            "sourceColumn": "sfx_cd",
            "summarizeBy": "none"
          },
          {
            "name": "col_combi_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "38939a3d-f6b6-44d1-a2ca-d6a942bfa2e7",
            "sourceColumn": "col_combi_cd",
            "summarizeBy": "none"
          },
          {
            "name": "YYYYMMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    LEFT('dms_sales_kpi_history'[YYYYMM], 4), //  ",
              "    RIGHT('dms_sales_kpi_history'[YYYYMM], 2), //  ",
              "    1 //  1       ",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "91b6c7a0-4d23-4629-a053-bdb653421e29",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e707727c-02e3-4219-9d0b-d864ce21fbf9",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5a081fac-c530-42e2-b764-6f46abd3ac5a",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "39435d4a-8e43-42bd-8f5c-4e553c245ef5",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "e73c9ee3-b72d-480f-b881-2368e7fc687c",
        "partitions": [
          {
            "name": "dms_sales_kpi_history",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.Query(\"dsn=TOYOTA1\", \"SELECT *#(lf)FROM dms_sales_kpi_history dskh  #(lf)WHERE EXTRACT(YEAR FROM TO_DATE(yyyymm, 'YYYYMMDD')) >= EXTRACT(YEAR FROM CURRENT_DATE) - 5;\"),",
                "    #\"  \" = Table.AddColumn(, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text),",
                "    #\" 1\" = Table.AddColumn(#\"  \", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "dms_co_kpi_resource",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "48bca2f1-65f9-479a-8346-3896d7d67bef",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd_type_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "493e8c4e-1b99-493f-8de8-345d44923516",
            "sourceColumn": "yyyymmdd_type_cd",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "346e94a9-900d-4f2b-a55a-f75788d05791",
            "sourceColumn": "yyyymmdd",
            "summarizeBy": "none"
          },
          {
            "name": "co_kpi_code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ac607ad9-e9db-4527-a3e0-b16d75f77146",
            "sourceColumn": "co_kpi_code_type",
            "summarizeBy": "none"
          },
          {
            "name": "co_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67715268-9216-4e48-8937-78350ea990e6",
            "sourceColumn": "co_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "co_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "764760e3-998f-4fda-8b78-7ba04b4e60ef",
            "sourceColumn": "co_kpi_code_amt",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e235a7af-bc58-436c-8d56-afdbd9404026",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_e8f7a042-f709-48fb-8ca2-f8fc52da0f86"
                },
                "isDefault": true,
                "relationship": "6f5de9c6-8533-43c2-896f-742aa437a36b"
              }
            ]
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a0ae2e92-ed48-4dd6-a5b4-eea011185774",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "3e3c7fc0-1061-418c-8d05-0460619518be",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_02eff536-60f7-4e9b-9b31-d65fd367cc80"
                },
                "isDefault": true,
                "relationship": "b918b134-a04a-4eff-94c8-025684df0bde"
              }
            ]
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "50c0d69d-4c65-4733-bafc-846f4852e827",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "4b45798d-ea45-429e-9b06-dae10a3b12bf",
        "partitions": [
          {
            "name": "dms_co_kpi_resource",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_co_kpi_resource_Table = dev_twice_Schema{[Name=\"dms_co_kpi_resource\",Kind=\"Table\"]}[Data]",
                "in",
                "    dms_co_kpi_resource_Table"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_e8f7a042-f709-48fb-8ca2-f8fc52da0f86",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5012def1-1e8d-452d-b13f-512461e4ba85",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8e2be9e8-0bce-447c-b9f0-815f6981734f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "674fddd2-528e-4036-ada6-0565c9a6deb1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "2e8cdf87-f11b-4310-9bb1-2f124a3aa34c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "586723e5-0cd8-4c83-a4c1-1b9bb0ea61ed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "d36e7c2e-d4fe-47e2-8c50-c87279e3730c",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "2ee9f7c4-2f0c-4f38-a20c-2dade82bc2a6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "049d5d06-0056-47e3-8d1c-f6398a51fe36",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "636d8583-6dba-49c8-b19e-26b104f93674",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "85381975-02a4-4cfd-9215-34b9dfe21a44",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "de9841d8-9a3b-4125-9c80-0af6489805d5",
                "ordinal": 3
              }
            ],
            "lineageTag": "3552043c-2e4c-4a33-a86e-c5d79285045c"
          }
        ],
        "isHidden": true,
        "lineageTag": "713c5f5e-2c71-4708-b273-6cb0bc195753",
        "partitions": [
          {
            "name": "LocalDateTable_e8f7a042-f709-48fb-8ca2-f8fc52da0f86",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_kpi_resource'[dms_bi_reg_dt])), 1, 1), Date(Year(MAX('dms_co_kpi_resource'[dms_bi_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_02eff536-60f7-4e9b-9b31-d65fd367cc80",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "ab8dea3b-1c3c-4a3f-b615-4b28d2eb92aa",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "158dcbe8-3802-42b5-bc48-a947149da73a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "8d592322-7b8e-47e6-8a6e-8303ac38e82c",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "dad6bdfb-58ec-4c09-b39e-255141a1f311",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6ddd8b78-3b49-4325-a38b-44cd3891fb77",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0daca858-190f-46ac-894b-8198ae2be61f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "f36f323e-1475-45a7-86d2-5637b1a5ef01",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "3aab4a3f-4a4b-4d5c-901e-694df6ffe3c3",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "85c5b0ed-0f88-491a-87aa-c7c3ae9780c6",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "add6a143-754b-4504-8158-eab49a2a4b22",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "77781e78-f2e8-4ffa-b0f6-3998ce04c55c",
                "ordinal": 3
              }
            ],
            "lineageTag": "4840ce7d-c26d-4912-b300-2ce07132c481"
          }
        ],
        "isHidden": true,
        "lineageTag": "eef90334-613d-4f04-bbcc-ecb7a54a1201",
        "partitions": [
          {
            "name": "LocalDateTable_02eff536-60f7-4e9b-9b31-d65fd367cc80",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_co_kpi_resource'[dms_bi_upd_dt])), 1, 1), Date(Year(MAX('dms_co_kpi_resource'[dms_bi_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "dms_sales_kpi_resource",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d8b81204-5368-4df0-be8c-e4b621e9c451",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "473510c2-5d87-4021-a748-c7704feb2eee",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "45ec9600-70a4-4029-8dc3-56af45dc5f40",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "151a61bf-e053-4a0f-b03a-760508e0bbc7",
            "sourceColumn": "yyyymm",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2455d852-75f4-4b9f-99d9-65a95578168c",
            "sourceColumn": "sa_kpi_code_type",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "67748705-10aa-41d9-b165-8d627f277b2e",
            "sourceColumn": "sa_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "f6c509ef-b10a-494d-98fd-0b87944cd83f",
            "sourceColumn": "sa_kpi_code_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1a5f2848-24f8-4917-9cf7-80d1afb84e8a",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "aa38c7cf-f88b-416f-95a7-1d9a35f3021f",
            "sourceColumn": "variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "188a298d-a7e5-4fce-9938-f561ee34af5d",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "5de07a71-8ed8-41ba-889a-7287bc4c5b7a",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_reg_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "46d7ec01-39e6-4614-af62-acf7b43a0021",
            "sourceColumn": "dms_bi_reg_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_6df59a7f-babe-4480-91aa-14f82232dba1"
                },
                "isDefault": true,
                "relationship": "06ee9f09-4b43-4379-84c7-f8b347e6f5f7"
              }
            ]
          },
          {
            "name": "dms_bi_reg_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "72c3222a-9c37-4bc9-93ce-db0de372d8d9",
            "sourceColumn": "dms_bi_reg_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "dms_bi_upd_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "4386b6ed-a637-4bbe-a5c9-08b5aa82ad9f",
            "sourceColumn": "dms_bi_upd_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_05913f03-ec40-4ce6-acbb-3684a3e5ff43"
                },
                "isDefault": true,
                "relationship": "458ac7df-e4e0-4f71-8459-5266c75bcd73"
              }
            ]
          },
          {
            "name": "dms_bi_upd_user_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bbfefb12-34ff-4036-bcb1-25a63131f956",
            "sourceColumn": "dms_bi_upd_user_id",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4eaeec13-b1c0-4764-b893-2ec016012381",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "83301eab-80ea-48d7-8cb4-48d35548c156",
            "sourceColumn": "model_nm",
            "summarizeBy": "none"
          },
          {
            "name": "YYYYMMDD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "expression": [
              "DATE(",
              "    LEFT('dms_sales_kpi_resource'[YYYYMM], 4), //  ",
              "    RIGHT('dms_sales_kpi_resource'[YYYYMM], 2), //  ",
              "    1 //  1       ",
              ")"
            ],
            "formatString": "General Date",
            "isDataTypeInferred": true,
            "lineageTag": "1bdf61a5-6682-4e03-a385-11a5e356ec6a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "cd9158ee-335b-4fc6-80fd-4f197e0661dc",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "310c5254-36df-4851-b682-5476f96ec721",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "90f02668-ad80-46d5-bc35-7f46d0839138",
        "partitions": [
          {
            "name": "dms_sales_kpi_resource",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    dms_sales_kpi_resource_Table = dev_twice_Schema{[Name=\"dms_sales_kpi_resource\",Kind=\"Table\"]}[Data],",
                "    #\" 1\" = Table.AddColumn(dms_sales_kpi_resource_Table, \"b_variant_cd\", each if [dms_brand_cd] <> null and [variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [variant_cd]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_6df59a7f-babe-4480-91aa-14f82232dba1",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "9967efe2-b541-4574-a9d4-c442358e67ed",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "c6d9503a-7128-4ff6-b432-1d2d3449eb60",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "436cd743-6ae8-4d94-ad71-03dc65f2e8e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a8eb781f-0cd2-4954-918c-dbb82baf2794",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "4c9f95f6-014e-4042-bd51-dd234a7f017d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7c11d742-aca6-423b-a82d-d6c106d9bf6a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5d22d533-d07e-417c-b3a4-4b64559b76d3",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "52625a7c-ec92-4528-bfcf-4dd48f90667b",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "bf1c1e6e-f308-4f64-84fe-b1e8916128fd",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "c8327b2a-0bc8-4c95-b095-cf4c422278e2",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "441217a8-25c9-4c35-ba1c-1cbe96b72e65",
                "ordinal": 3
              }
            ],
            "lineageTag": "0835b534-987f-41b7-bb33-a3f9f4bf909f"
          }
        ],
        "isHidden": true,
        "lineageTag": "15fabcc6-7d8b-4bc9-83c7-7fbe1fffacda",
        "partitions": [
          {
            "name": "LocalDateTable_6df59a7f-babe-4480-91aa-14f82232dba1",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_kpi_resource'[dms_bi_reg_dt])), 1, 1), Date(Year(MAX('dms_sales_kpi_resource'[dms_bi_reg_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_05913f03-ec40-4ce6-acbb-3684a3e5ff43",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6282a0d3-dfe9-4aa5-84b3-9a62823d8213",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "51ae8939-0b95-4491-80df-1c0159bb420b",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "57554a86-43dc-44d5-94a1-d1cc983faba6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "6e596f52-3719-4264-9480-535cf5bd77f9",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "e8ceba8d-b5c2-4bee-999d-4953c6ff136d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "1d6da1bc-cfc4-47e7-b868-49e02a013741",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1a373e50-0f53-4350-b036-31c0d8f33cc6",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "641fc237-e805-42e6-93a8-f50bd4b89b04",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "a92174a6-8129-48bb-a11b-04b0d55bcdaa",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "7bf954bc-e79a-4794-92f0-4f67bd44832e",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "1cbbb20e-c003-4472-8793-8e72850ca4e7",
                "ordinal": 3
              }
            ],
            "lineageTag": "83a77f00-a4d6-4d29-a930-e7df39f91e09"
          }
        ],
        "isHidden": true,
        "lineageTag": "4c6618b0-f9b3-43f1-b479-bbafd9671c0a",
        "partitions": [
          {
            "name": "LocalDateTable_05913f03-ec40-4ce6-acbb-3684a3e5ff43",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('dms_sales_kpi_resource'[dms_bi_upd_dt])), 1, 1), Date(Year(MAX('dms_sales_kpi_resource'[dms_bi_upd_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "v_dim_dealer_sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a287fa92-f368-4376-afea-f4c8c9abee54",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0fb0d8d9-f45a-406d-b5e3-0914aff60a5a",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "bdeae7aa-5b0d-4e01-bd81-f14c7abdd365",
            "sourceColumn": "dealer_name",
            "summarizeBy": "none"
          },
          {
            "name": "use_yn",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "de7472a8-bdbb-412d-92b1-74f696184b52",
            "sourceColumn": "use_yn",
            "summarizeBy": "none"
          },
          {
            "name": "dspy_rank",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "b7259c2c-0a8f-4024-9091-4d3f1fd9f943",
            "sourceColumn": "dspy_rank",
            "summarizeBy": "sum"
          },
          {
            "name": "eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4d1c84e7-77f4-4824-896d-2569138692c5",
            "sourceColumn": "eng_name",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e2f318e9-2c1f-45d0-b59e-20c3dbf56259",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          },
          {
            "name": "index",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "9cb3d906-66c5-47d2-bad6-0a7c90edd818",
            "sourceColumn": "index",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "01028913-c084-499b-9d4d-bf5ef879f964",
        "partitions": [
          {
            "name": "v_dim_dealer_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_dealer_sales_View = dev_twice_Schema{[Name=\"v_dim_dealer_sales\",Kind=\"View\"]}[Data],",
                "    #\" 1\" = Table.AddColumn(v_dim_dealer_sales_View, \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text),",
                "    #\" 2\" = Table.AddIndexColumn(#\" 1\", \"index\", 1, 1, Int64.Type)",
                "in",
                "    #\" 2\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_dim_group_sales",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e257c46a-e684-46ba-8782-950d6010b04f",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c6b567ea-bc96-474a-9d5d-c1244bf05318",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2b00562a-759a-446a-8df6-4dc18f47b7a4",
            "sourceColumn": "group_name",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6cc82d74-43d3-4ba9-b1bd-612646c323dd",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_eng_name",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "changedProperties": [
              {
                "property": "SortByColumn"
              }
            ],
            "dataType": "string",
            "lineageTag": "b2142a21-a60e-4606-a60b-0518fe54ad1a",
            "sortByColumn": "sort",
            "sourceColumn": "group_eng_name",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "0bada30e-ac6c-4885-af71-37cda8d17b5c",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "c773dada-fa97-4798-92ea-4cd20e10ca58",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "group_name(New)",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "06a5cf9f-08a4-41fc-80d4-514331f90d7e",
            "sourceColumn": "group_name(New)",
            "summarizeBy": "none"
          },
          {
            "name": "sort",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "a3f1e935-07fe-4369-8471-b3c1440e6129",
            "sourceColumn": "sort",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "132c8ef8-b6d0-4bdb-a94c-853698255354",
        "partitions": [
          {
            "name": "v_dim_group_sales",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_dim_group_sales_View = dev_twice_Schema{[Name=\"v_dim_group_sales\",Kind=\"View\"]}[Data],",
                "    #\" 1\" = Table.AddColumn(v_dim_group_sales_View, \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text),",
                "    #\" 3\" = Table.AddColumn(#\" 2\", \"group_name(New)\", each ",
                "        let",
                "            replacements = {{\"\", \"\"}, {\"\", \"\"}, {\"\", \"\"}, {\"\", \"\"}},",
                "            replacedText = List.Accumulate(replacements, [group_name], (state, replacement) => Text.Replace(state, replacement{0}, replacement{1}))",
                "        in",
                "            Text.Trim(replacedText)",
                "    ),",
                "    #\" 4\" = Table.AddColumn(#\" 3\" , \"sort\"",
                "    , each if [group_eng_name] = \"GN\" then 1 ",
                "    else if [group_eng_name] = \"SC\" then 2",
                "    else if [group_eng_name] = \"IC\" then 2",
                "    else if [group_eng_name] = \"YS\" then 3",
                "    else if [group_eng_name] = \"BD\" then 4 ",
                "    else if [group_eng_name] = \"BS\" then 5 ",
                "    else if [group_eng_name] = \"DG\" then 6 ",
                "    else if [group_eng_name] = \"GJ\" then 7 ",
                "    else if [group_eng_name] = \"DJ\" then 8 ",
                "    else if [group_eng_name] = \"TMKR\" then 9",
                "    else null, type number)",
                "in",
                "    #\" 4\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "v_fact_stock_info",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": ""
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82c1436f-6213-443e-89ad-cfe870710f6e",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "port_in_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "087a972a-659f-49b9-9e3a-a630ec38e29f",
            "sourceColumn": "port_in_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_59d7de8b-c00f-4857-8439-8a6700785696"
                },
                "isDefault": true,
                "relationship": "aaaee4e5-ba26-4d13-a32e-b9ce503977d3"
              }
            ]
          },
          {
            "name": "retailsales_dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "eb424ce8-6ef4-467a-972d-df5a12c1d666",
            "sourceColumn": "retailsales_dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_c442de05-9937-4533-a08e-d1315ec38db0"
                },
                "isDefault": true,
                "relationship": "5629ebb5-84a7-4a1a-8f96-6aee29f21b2b"
              }
            ]
          },
          {
            "name": "stock_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "99f8cc6c-21f3-42a2-8e2f-22f36687566a",
            "sourceColumn": "stock_status",
            "summarizeBy": "none"
          },
          {
            "name": "al_status",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "30c4f57e-7e18-49ad-bc4a-db95b23b0654",
            "sourceColumn": "al_status",
            "summarizeBy": "none"
          },
          {
            "name": "progress_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "32808a1f-3246-4a6f-87a7-3b28ae9d6651",
            "sourceColumn": "progress_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ecd95cd4-2208-4df7-a956-f401556de936",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7f156b84-8b7b-4d29-be40-3600d8084aea",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "309b22f0-f512-4370-9beb-47ac20bda93d",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_nm",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1925120c-5f5f-4590-81aa-750fa1c82be0",
            "sourceColumn": "report_variant_nm",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89f4608b-bc7d-4d81-a0fa-19c19a144e7a",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "adb9dabc-4a56-4871-bf38-3a0bb0dcc50a",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "contract_stat_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "3b6e9338-868a-47cf-8f0b-a0fd06c7eb11",
            "sourceColumn": "contract_stat_cd",
            "summarizeBy": "none"
          },
          {
            "name": "b_report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e7920166-827f-4631-99ed-748383d1de83",
            "sourceColumn": "b_report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "9d3fd2b1-9747-4c31-8402-5f2e11ee4696",
            "sourceColumn": "dealer_key",
            "summarizeBy": "none"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "6015b27c-6d95-4070-8959-04daa61e6e5b",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "081bb312-aa58-4d78-a3a0-ac66468362ec",
        "measures": [
          {
            "name": "#_1~3M Available_Stock",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS('v_fact_stock_info')",
              ", NOT 'v_fact_stock_info'[stock_status] IN {\"96\", \"99\"}",
              ", NOT 'v_fact_stock_info'[al_status] IN {\"LO\", \"IT\"}",
              ", NOT ISBLANK('v_fact_stock_info'[progress_cd])",
              ", 'v_fact_stock_info'[port_in_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)-1",
              ", 'v_fact_stock_info'[port_in_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-3)",
              "    , ISBLANK('v_fact_stock_info'[retailsales_dt])||'v_fact_stock_info'[retailsales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)",
              ""
            ],
            "formatString": "#,0",
            "lineageTag": "e01b7715-62c3-40ae-8e11-62f96024ccae"
          },
          {
            "name": "#_1M Available_Stock",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS('v_fact_stock_info')",
              ", NOT 'v_fact_stock_info'[stock_status] IN {\"96\", \"99\"}",
              ", NOT 'v_fact_stock_info'[al_status] IN {\"LO\", \"IT\"}",
              ", NOT ISBLANK('v_fact_stock_info'[progress_cd])",
              ", 'v_fact_stock_info'[port_in_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ", 'v_fact_stock_info'[port_in_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-1)",
              "    , ISBLANK('v_fact_stock_info'[retailsales_dt])||'v_fact_stock_info'[retailsales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "bbe1f26c-b4b1-4130-942a-35023fbfa5a0"
          },
          {
            "name": "#_4~6M Available Stock",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS('v_fact_stock_info')",
              ", NOT 'v_fact_stock_info'[stock_status] IN {\"96\", \"99\"}",
              ", NOT 'v_fact_stock_info'[al_status] IN {\"LO\", \"IT\"}",
              ", NOT ISBLANK('v_fact_stock_info'[progress_cd])",
              ", 'v_fact_stock_info'[port_in_dt] <= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-3)-1",
              ", 'v_fact_stock_info'[port_in_dt] >= EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-6)",
              "    , ISBLANK('v_fact_stock_info'[retailsales_dt])||'v_fact_stock_info'[retailsales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "bc56110c-1ca7-4dd9-a937-5a266fa85ea7"
          },
          {
            "name": "#_Available_Stock_Total",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "",
              "[#_1M Available_Stock] + [#_1~3M Available_Stock] + [#_4~6M Available Stock] + [#_Over 6M Available Stock]"
            ],
            "formatString": "#,0",
            "lineageTag": "7213baa2-957a-4a81-a3c8-2f81dae7f67d"
          },
          {
            "name": "#_Over 6M Available Stock",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "VAR Result = CALCULATE(COUNTROWS('v_fact_stock_info')",
              ", NOT 'v_fact_stock_info'[stock_status] IN {\"96\", \"99\"}",
              ", NOT 'v_fact_stock_info'[al_status] IN {\"LO\", \"IT\"}",
              ", NOT ISBLANK('v_fact_stock_info'[progress_cd])",
              ", 'v_fact_stock_info'[port_in_dt] < EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),-6)",
              "    , ISBLANK('v_fact_stock_info'[retailsales_dt])||'v_fact_stock_info'[retailsales_dt] > EOMONTH(DATE(SELECTEDVALUE(v_dim_calendar[year]),SELECTEDVALUE(v_dim_calendar[month]),1),0)",
              ")",
              "RETURN",
              "IF(ISBLANK(Result),0,Result)"
            ],
            "formatString": "#,0",
            "lineageTag": "e473f770-23af-4b4c-bf44-f047e7dc8ebb"
          },
          {
            "name": "#_Diff_Blank_Filter",
            "displayFolder": "_Stock Information",
            "expression": [
              "",
              "IF([#_Stock Month]=0 && [#_BOC Month]=0,0,1)"
            ],
            "formatString": "0",
            "lineageTag": "ab1f627b-9284-4754-a98d-d42a918f03d9"
          },
          {
            "name": "#_Stock_Blank_Filter",
            "displayFolder": "_Stock Information",
            "expression": "if([#_1M Available_Stock]=0 && [#_1~3M Available_Stock]=0 && [#_4~6M Available Stock]=0 && [#_Over 6M Available Stock]=0 &&[#_Available_Stock_Total]=0,0,1) ",
            "formatString": "0",
            "lineageTag": "d57b8715-ba37-4725-ba47-4c87c7be6656"
          }
        ],
        "partitions": [
          {
            "name": "v_fact_stock_info",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_fact_stock_info_View = dev_twice_Schema{[Name=\"v_fact_stock_info\",Kind=\"View\"]}[Data],",
                "    #\" 1\" = Table.AddColumn(v_fact_stock_info_View, \"b_report_variant_cd\"",
                "    , each if [dms_brand_cd] <> null and [report_variant_cd] <> null then Text.Combine({[dms_brand_cd], \"_\", [report_variant_cd]}) else null, type text),",
                "    #\" 2\" = Table.AddColumn(#\" 1\" , \"dealer_key\"",
                "    , each if [dms_brand_cd] <> null and [dealer_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [dealer_id]}) else null, type text),",
                "    #\" 3\" = Table.AddColumn(#\" 2\", \"group_key\"",
                "    , each if [dms_brand_cd] <> null and [group_id] <> null then Text.Combine({[dms_brand_cd], \"_\", [group_id]}) else null, type text)",
                "in",
                "    #\" 3\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_59d7de8b-c00f-4857-8439-8a6700785696",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2bb5f5a4-7032-4084-a7fc-8f4fe23c660a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e42f7b31-7716-433c-9ffe-297b39713022",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "9e5bda5c-a247-4e68-94b9-2e319a24e988",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3ee0fea5-ecc1-43c3-823b-8b7464c5a37c",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "8fa96aed-84b1-4552-a6a5-a99e5eeaffed",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "b5880f2c-cac4-463e-939a-a479034e39c0",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "41acc52f-dda1-4af1-996d-3a9a53c9b75a",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "b57019fc-d954-4a07-920c-1f99642a7dc7",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "9ee881aa-01c5-4927-b3f9-f3f23957bc04",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "068e9c84-eb51-49aa-9c1c-c26d62c77c9e",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "ea08dec3-5a80-4eb5-b4a9-7ef31660b1ef",
                "ordinal": 3
              }
            ],
            "lineageTag": "cdcbdc01-2b48-4586-8ab2-201eeec0ac13"
          }
        ],
        "isHidden": true,
        "lineageTag": "39aebabd-ec45-46f0-b0ab-0465d150aa1e",
        "partitions": [
          {
            "name": "LocalDateTable_59d7de8b-c00f-4857-8439-8a6700785696",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_stock_info'[port_in_dt])), 1, 1), Date(Year(MAX('v_fact_stock_info'[port_in_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_c442de05-9937-4533-a08e-d1315ec38db0",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f8254905-6a80-433f-ae18-7ab2b0c6c16b",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "15ea1eca-ac8a-47cb-a193-5d79d035a2b9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4e2c44ba-3989-4683-a465-68f4a88bdea0",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "87608eeb-8d4c-4ddb-9e38-bbed6bafff6f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "9d120cf1-c35e-4f46-8430-f430c25261ce",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "2688017d-7f99-4472-82bf-d7268ddaf77a",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "c1156dd8-2c09-43b6-96ce-68505578156d",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "0dd5c09f-024b-4d5f-bd31-7d504dfd0088",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "efc50a83-fae0-42da-852d-a7657c0d08f2",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "e347d13d-0b99-4b53-b3f3-db7c92b64ad5",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "3938133a-bd64-445a-8869-ef5ec4a13013",
                "ordinal": 3
              }
            ],
            "lineageTag": "853b463d-f11a-4581-9cc2-2eb61a6b0cdf"
          }
        ],
        "isHidden": true,
        "lineageTag": "55145ae2-dec0-43d4-996e-988b8443ca66",
        "partitions": [
          {
            "name": "LocalDateTable_c442de05-9937-4533-a08e-d1315ec38db0",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_fact_stock_info'[retailsales_dt])), 1, 1), Date(Year(MAX('v_fact_stock_info'[retailsales_dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "v_sales_contract_forecast",
        "columns": [
          {
            "name": "dms_brand_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d9afd22-5e0b-46b9-8c2c-b61aa1c659a1",
            "sourceColumn": "dms_brand_cd",
            "summarizeBy": "none"
          },
          {
            "name": "dealer_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "89f98f8c-404a-4d2c-8da7-107564246548",
            "sourceColumn": "dealer_id",
            "summarizeBy": "none"
          },
          {
            "name": "group_id",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "349af3cc-0200-4723-b80d-0d570980dc32",
            "sourceColumn": "group_id",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_type",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "e013b724-5eb7-4a62-9e7b-e00a4d0bd557",
            "sourceColumn": "sa_kpi_code_type",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2dda59ce-250b-40e1-a824-66e9ed622b09",
            "sourceColumn": "sa_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "yyyymmdd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "43da9ce1-a1dd-42a7-8faf-d0a88457e414",
            "sourceColumn": "yyyymmdd",
            "summarizeBy": "none"
          },
          {
            "name": "variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "37a35892-5718-4e1a-b268-a7998ba91170",
            "sourceColumn": "variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "report_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "847e7bfe-70e1-4342-abd7-83bdc8af1073",
            "sourceColumn": "report_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "model_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "82fd4398-08ba-42d9-ac9d-308dc450d6c3",
            "sourceColumn": "model_cd",
            "summarizeBy": "none"
          },
          {
            "name": "sa_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "c264be3f-e554-444f-bf32-b4b960fecb53",
            "sourceColumn": "sa_kpi_code_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "co_kpi_code",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "2951041f-a443-4b5e-b753-083e3085cbc1",
            "sourceColumn": "co_kpi_code",
            "summarizeBy": "none"
          },
          {
            "name": "co_kpi_code_amt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "2af4b722-99ab-4451-a32b-e6a9fd1a7f56",
            "sourceColumn": "co_kpi_code_amt",
            "summarizeBy": "sum"
          },
          {
            "name": "group_key",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1f289b5f-0378-43dc-b056-d3627d184e4d",
            "sourceColumn": "group_key",
            "summarizeBy": "none"
          },
          {
            "name": "dt",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "e8954294-b6b0-41f8-a66d-8eddb7d031c8",
            "sourceColumn": "dt",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "",
                "defaultHierarchy": {
                  "hierarchy": " ",
                  "table": "LocalDateTable_884b4813-db7e-4c7d-83dc-10197a7ed0f3"
                },
                "isDefault": true,
                "relationship": "034e3c60-ee49-46d7-933f-0718922d73a6"
              }
            ]
          },
          {
            "name": "b_variant_cd",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a9e9c378-635f-4b40-a8ca-305d572f27e4",
            "sourceColumn": "b_variant_cd",
            "summarizeBy": "none"
          },
          {
            "name": "_group_name_new",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "expression": "RELATED(v_dim_group_sales[group_name(New)])",
            "isDataTypeInferred": true,
            "lineageTag": "7c6fc04e-53d6-403c-84aa-017f142294be",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "lineageTag": "5528c490-92b5-4f6a-8b68-60fdf54341ba",
        "measures": [
          {
            "name": "#_group_id_num_contract",
            "displayFolder": "_Forecast",
            "expression": [
              "",
              "var _1th = DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1) -- first day",
              "var _eomon = EOMONTH(_1th, 0) -- last day ",
              "var _today = SELECTEDVALUE(v_dim_calendar[date]) -- selected day",
              "",
              "var _num = CALCULATE(",
              "                                COUNTROWS(DISTINCT(v_sales_contract_forecast[_group_name_new]))",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"CONTRACT\"",
              "                                   ,v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _eomon",
              "                                )",
              "RETURN",
              "_num",
              ""
            ],
            "formatString": "0",
            "lineageTag": "4018e937-1fe7-4bea-9c87-368ac5d6f9ba"
          },
          {
            "name": "#_group_id_num_sales",
            "displayFolder": "_Forecast",
            "expression": [
              "",
              "var _1th = DATE(SELECTEDVALUE(v_dim_calendar[year]), SELECTEDVALUE(v_dim_calendar[month]), 1) -- first day",
              "var _eomon = EOMONTH(_1th, 0) -- last day ",
              "var _today = SELECTEDVALUE(v_dim_calendar[date]) -- selected day",
              "",
              "var _num = CALCULATE(",
              "                                COUNTROWS(DISTINCT(v_sales_contract_forecast[_group_name_new]))",
              "                                    , v_sales_contract_forecast[sa_kpi_code] = \"RETAIL_SALES\"",
              "                                   ,v_sales_contract_forecast[dt] >= _1th && v_sales_contract_forecast[dt] <= _eomon",
              "                                )",
              "RETURN",
              "_num"
            ],
            "formatString": "0",
            "lineageTag": "a1943478-6e75-4fd3-a621-b70794d14cf9"
          },
          {
            "name": "#__Progress_Sales_Blank_Filter",
            "displayFolder": "_Forecast",
            "expression": "IF([#_Sales_Target(M)]=0&&[#_Sales_Target(D)_MTD]=0&&[#_Sales_CurrentPace_MTD]=0&&[#_Sales_Gap]=0&&[#_Sales_Forecast(31th)_MTD]=0&&[#_Sales_Forecast_Gap]=0,0,1)",
            "formatString": "0",
            "lineageTag": "0ec6c9b4-3be6-456e-9db9-65de6e2617c0"
          },
          {
            "name": "#__Progress_Contract_Blank_Filter",
            "displayFolder": "_Forecast",
            "expression": "IF([#_Contract_Target(M)]=0&&[#_Contract_Target(D)_MTD]=0&&[#_Contract_CurrentPace_MTD]=0&&[#_Contract_Gap]=0&&[#_Contract_Forecast(31th)_MTD]=0&&[#_Contract_Forecast_Gap]=0,0,1)",
            "formatString": "0",
            "lineageTag": "a506be48-3c48-4afe-97b2-3bb2464196ef"
          }
        ],
        "partitions": [
          {
            "name": "v_sales_contract_forecast",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "     = Odbc.DataSource(\"dsn=TOYOTA1\", [HierarchicalNavigation=true]),",
                "    d_twice_Database = {[Name=\"d_twice\",Kind=\"Database\"]}[Data],",
                "    dev_twice_Schema = d_twice_Database{[Name=\"dev_twice\",Kind=\"Schema\"]}[Data],",
                "    v_sales_contract_forecast_View = dev_twice_Schema{[Name=\"v_sales_contract_forecast\",Kind=\"View\"]}[Data]",
                "in",
                "    v_sales_contract_forecast_View"
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_884b4813-db7e-4c7d-83dc-10197a7ed0f3",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "0a0f5ae1-9710-47b0-bc33-7fa98e558e9a",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "8e00986e-7141-4993-8fd5-1fbb816b3111",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "87971036-9dda-4afd-9363-138ae08248e4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "456ab9c6-f0b5-4c5a-9f1e-aeb90a4c9e92",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "985655b9-4b50-4791-9926-9b7ab69d74da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\" \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "60ee7d86-1354-4bc1-98b3-0d510a5fb166",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "01239c3d-66c0-43fd-819c-fb87335ca94c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": " ",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "",
                "column": "",
                "lineageTag": "7bf97e98-7881-402a-95d1-0d782a091b30",
                "ordinal": 0
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "707fd982-7ad4-4bf8-9428-c9eac6e38fb1",
                "ordinal": 1
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "3f8ffe7a-f1b9-4db4-b09a-8bd1c2da5263",
                "ordinal": 2
              },
              {
                "name": "",
                "column": "",
                "lineageTag": "b3f5d999-c137-4fce-a560-f3722e52159a",
                "ordinal": 3
              }
            ],
            "lineageTag": "c1440f90-e347-4159-a948-b4b995b87e73"
          }
        ],
        "isHidden": true,
        "lineageTag": "c32ef141-db17-4d7a-80e5-74867d9c7632",
        "partitions": [
          {
            "name": "LocalDateTable_884b4813-db7e-4c7d-83dc-10197a7ed0f3",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('v_sales_contract_forecast'[dt])), 1, 1), Date(Year(MAX('v_sales_contract_forecast'[dt])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}